:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:toc: preamble

= Continuous Integration with GitHub Actions

Continuous Integration (CI) refers to the process of frequently integrating changes created by various developers in your team, in order to have (almost) permanently underhand a current, integrated version of your software containing all the developments so far.

CI makes especially sense when you are able to control automatically that your software still runs successfully after the merge. This you normally do by having a sufficient coverage of (unit or functional or integration) tests.

This document presents https://help.github.com/actions[GitHub Actions], a service which provides Continuous Integration for free for open-source projects.

== Motivation
When developing in a team, it is frequent that a sub-team will branch the project and work on a feature on its own for a while. This may break other features of the software, or introduce changes incompatible with the parallel changes made by some other sub-team. If the branch is being developed for a long time apart from other developments in the project, it will become increasingly difficult to merge the changes. At some point, it may even be considered easier to start developing the feature again from scratch than to merge. Frequent merges reduce this risk.

Another motivation of CI is to always have a version of your software ready for demonstration.

A third motivation is that CI usually goes together with remote building: you set up a remote platform dedicated to building your project and running the tests. That ensures that your software builds and executes successfully in a clean environment (knowing that it builds and runs in the computers of the developers might be an insufficient guarantee, as those computers might have specific softwares and customization).

== Overview
The most important point to embrace CI is to decide to do it! All the team members have to commit their changes frequently to a common source control repository and to merge frequently (usually in a development branch). 

Once you have taken this decision, some tools may help.
CI tools can be used to automatically run a build (and trigger your tests) when you commit to your source control repository, and warn you when builds or tests fail.

== Set-up
. Add a file `.github/workflows/Maven CI.yaml` to your repository, with https://github.com/oliviercailloux/jmcda-utils/blob/master/.github/workflows/Maven%20CI.yaml[this content] (or adapt to your needs), and push it to GitHub.
. Go to your GitHub repository, and click the Actions tab to see your workflow being executed

Add the relevant badge to your README.adoc in your project repository: check https://raw.githubusercontent.com/oliviercailloux/jmcda-utils/master/README.adoc[this] and adapt it.

== Explanations
A workflow is defined in a `.github/workflows/{nameFile}.yaml` file. It contains at least one job, and these jobs in turn contain steps. These steps reference actions or commands. An action is a basic task unit (for example: check out a repository). Some actions are provided officially by GitHub, but many more are available by third parties.

In the above example, we create a workflow with one job containing these steps:
. an action that executes a https://github.com/marketplace/actions/checkout[git checkout] of the repository;
. an action that https://github.com/marketplace/actions/setup-java[sets up java] (and that takes an argument);
. an action that saves or restores a https://help.github.com/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows[cache] containing Maven required artifacts;
. and a command that triggers a build by maven.

== Useful links

* https://help.github.com/actions[Official documentation]
* https://help.github.com/en/actions/configuring-and-managing-workflows/using-variables-and-secrets-in-a-workflow[Using variables and secrets in a workflow]
* https://github.com/sdras/awesome-actions[An organized list of awesome actions to use on GitHub]
* Actions https://github.com/marketplace?type=actions[marketplace]

== Thanks
This document has been originally created by Avi Mimoun, a student of this course. Thanks go to him. (His version is https://github.com/oliviercailloux/java-course/blob/a38d61e96d261fec0734b4560b97b0ccacda5ebd/DevOps/CI-github-actions.adoc[here].)

