= Continuous Integration
//works around awesome_bot bug that used to be published at github.com/dkhamsing/awesome_bot/issues/182.
:emptyattribute:

Continuous Integration (CI) refers to the process of frequently integrating changes created by various developers in your team, in order to have (almost) permanently underhand a current, integrated version of your software containing all the developments so far.

CI makes especially sense when you are able to control automatically that your software still runs successfully after the merge. This you normally do by having a sufficient coverage of (unit or functional or integration) tests.

This doc indicates how to set up CI with Travis-CI, for a Java project using https://github.com/oliviercailloux/java-course/tree/master/Maven[Maven] and hosted on GitHub.

== Motivation

When developing in a team, it is frequent that a sub-team will branch the project and work on a feature on its own for a while. This may break other features of the software, or introduce changes incompatible with the parallel changes made by some other sub-team. If the branch is being developed for a long time apart from other developments in the project, it will become increasingly difficult to merge the changes. At some point, it may even be considered easier to start developing the feature again from scratch than to merge. Frequent merges reduce this risk.

Another motivation of CI is to always have a version of your software ready for demonstration.

A third motivation is that CI usually goes together with remote building: you set up a remote platform dedicated to building your project and running the tests. That ensures that your software builds and executes successfully in a clean environment (knowing that it builds and runs in the computers of the developers might be an insufficient guarantee, as those computers might have specific softwares and customization).

== Overview

The most important point to embrace CI is to decide to do it! All the team members have to commit their changes frequently to a common source control repository and to merge frequently (usually in a development branch). 

Once you have taken this decision, some tools may help.
CI tools can be used to automatically run a build (and trigger your tests) when you commit to your source control repository, and warn you when builds or tests fail.

== Set-up

. Register and log-in to https://travis-ci.com/[Travis-CI].
//. Tell Travis-CI which of your GitHub repository you want Travis to take care of.
. Add a file `.travis.yml` to your repository, with the contents indicated here below, and push it to GitHub.
. Look at your page on the Travis-CI web site, and watch your project being built. (You might have to wait for about 30 seconds for Travis to react to your last push.)
. Add the relevant https://docs.travis-ci.com/user/status-images/[badge] to your `README.adoc` in your project repository.

.Sample `.travis.yml` configuration file
[source,yaml]
----
language: java
git:
  depth: 1
dist: xenial
cache:  
  directories:  
    - $HOME/.m2  
----

Travis will start a new build each time you send a commit to your GitHub repository.

The configuration file is written in https://yaml.org/[YAML], a human friendly format. I recommend http://www.yamllint.com/[validating] your configuration file whenever you change it.

The sample configuration file suggested here tells Travis to:

* fetch only the tip of your git history (`git https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt[depth] 1`);
* run the build in a container-based https://docs.travis-ci.com/user/reference/overview/[environment] using the (Ubuntu 16) https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_16.04_LTS_.28Xenial_Xerus.29[Xenial] distribution (instead of (Ubuntu 14) https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_14.04_LTS_.28Trusty_Tahr.29[Trusty] or (Ubuntu 12) https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_12.04_LTS_.28Precise_Pangolin.29[Precise]{emptyattribute});
* cache the directory where Maven downloads its files (http://muelder.blogspot.com/2015/08/building-eclipse-plugins-with-maven.html[thanks]).

Travis allows you to configure automatic deployment, run scripts of your own, and https://docs.travis-ci.com/[much more]. For example, https://github.com/oliviercailloux/PDF-p/blob/97737ee5b628f3f5e9755819059c57b36f99483e/.travis.yml[this] configuration clones a project dependency from GitHub and installs it locally before the main project is built. (This may be useful in case one of the dependency is not pushed to a public Maven repository.)


