= IBM Cloud

This document explains how to host your Java EE application on an IBM server.

NOTE: The reader supposedly has read https://github.com/oliviercailloux/java-course/blob/master/CI.adoc[CI] and has configured Travis CI for her project, and has at least one working https://github.com/oliviercailloux/java-course/blob/master/Servlets.adoc[Servlet] in the project.

== Access
IBM offers time-limited access to its Cloud offering to academic partners. Check at https://onthehub.com/[OnTheHub] whether your institution is listed. (Students who follow the course: register at https://dauphine.onthehub.com/[Dauphine OnTheHub] using your @dauphine.eu address.) 

Then get the “IBM Cloud Promo Code - 6 Month Trial” in your cart. Follow the instructions. At the end of the process you should be able to enter your promo code on the IBM Cloud https://console.bluemix.net/[console], which will give you access to the products we need.

== Overview
We will use only one thing from the vast offering of IBM Cloud: its “Liberty” hosting service. This means we will deploy your project on a server hosted by IBM, so that it will become permanently reachable on the internet, instead of just on your developer computer. This is useful for demonstration purposes; and this closes the loop by showing one way of deploying a project to the real world. (Well, the real virtual world.)

The IBM Cloud https://console.bluemix.net/[console] is used to monitor and configure your applications running on the cloud. (We will not use OnTheHub anymore, it serves only to provide initial access.)

You can use the command-line tool https://console.bluemix.net/docs/cli/index.html[CloudFoundry], `cf`, together with the IBM Cloud console, to manually deploy your applications or do a lot of other things. This is useful for debugging and going further with IBM products, but in this introduction, we will automate the deployment thanks to Travis, so we will not need `cf`. (Travis actually uses `cf` behind the scenes.)

== Set-up
Add a file `manifest.yml` to the root of your repository, with the content below. This indicates to IBM Cloud how your application should be deployed to their server. (See https://console.bluemix.net/docs/manageapps/depapps.html#appmanifest[doc] for details.) Replace `MyAppName` appropriately.

.Sample `manifest.yml` configuration file
[source,yaml]
----
applications:
 - name: MyAppName
   path: target/MyAppName.war
   instances: 1
----

Now we need to tell Travis to deploy your application to IBM Cloud as a part of the continuous integration process. Edit your `.travis.yml` file to reflect the configuration in this https://github.com/oliviercailloux/sample-jax-rs/blob/master/.travis.yml[sample] (look at the `deploy` part). (Check the Travis Bluemix CloudFoundry Deployment https://docs.travis-ci.com/user/deployment/bluemixcloudfoundry/[doc] for details.)

You can find your organization, space and region by looking at your https://console.bluemix.net/dashboard/apps/[deployed apps] in the IBM Cloud console.

Go to https://travis-ci.org/[Travis CI]: in your application, `More options` / `Settings`, you will find a way to add environment variables. Add one named `BLUEMIX_PASSWORD` with your password as value. Make sure “Display value in build log” is off.

In your `pom.xml`, in the `build` element, add `<finalName>${project.artifactId}</finalName>`, so that maven will produce an artifact with no version number in it. (Check this https://github.com/oliviercailloux/sample-jax-rs/blob/master/pom.xml[sample].) Otherwise, the `path` we have indicated in the `manifest.yml` must be changed to reflect the version.

Push your changes. Watch in the Travis log your application getting built, then deployed to IBM Cloud (isn’t it beautiful?). If all went well, the log indicates the url where your application is reachable, probably `https://MyAppName.eu-gb.mybluemix.net` (this is its context root). Refresh your https://console.bluemix.net/dashboard/apps/[deployed apps] page, you should see it there. Its servlets should now be reachable.

