= Class path: Exercices

== The Hello project
* Create a new project "Hello" from Eclipse.
* Create a Java source code file from within Eclipse, having full name `mypackage.one.MyClass`, containing a method `sayHello()` that prints `Hello` and a method `main(String[])` that calls `sayHello()`.
* Check that when run from Eclipse, your program says Hello.
* Check which file Eclipse has put this code in. Explain its precise location on your hard disk.
* Check and explain the precise location of the compiled version of `mypackage.one.MyClass` that Eclipse creates automatically.
* Exit Eclipse, delete the compiled version that Eclipse has created for you.
* Compile `mypackage.one.MyClass` manually using a terminal, with `javac` (see Oracle https://docs.oracle.com/javase/8/docs/technotes/tools/#basic[tools]).
** Remember that `javac` requests that you give it /files/ as arguments, not class names.
* Move the just created compiled version to a new folder called `target` instead of `src` (thus into `target/mypackage/one`), to keep source files separated from compiled files.
* Run the program using a terminal, with `java` (see Oracle https://docs.oracle.com/javase/8/docs/technotes/tools/#basic[tools]). Check that it says Hello.
* Restart Eclipse, export your project as a JAR archive in a file named `hello.jar`.

== The Use Hello project
* Create a new project "Use Hello".
* In your project properties in Eclipse, in the build path, add your JAR archive `hello.jar`. 
* Create a single class in your new project, having full name `userpackage.MyClass`, containing a method `main()`, that calls `sayHello()` *twice* from your `mypackage.one.MyClass` class.
* Check that when run from Eclipse, your program says Hello.
* Run the program using a terminal, with `java`. Check that it says Hello.

== Solution
The https://github.com/oliviercailloux/java-course/tree/master/Class%20path/Solution/[solution] is available as a bash script and two folders containing the source code.

