= Procédure pour nouvelle correction d’un exercice noté
J’utilise fréquemment des éléments de corrections automatisées, ce qui me permet de voir systématiquement et précisément les proportions d’étudiants qui réussissent chaque question, d’assurer l’équité et d’assurer une fréquence d’exercices notés élevée.

Si vous pensez qu’une correction est incorrecte, veuillez prendre le temps de relire l’énoncé, de bien lire les commentaires dans la correction, de partager avec d’autres étudiants, afin de comprendre ce qui est attendu et la différence par rapport à votre rendu. C’est un excellent exercice pour s’améliorer. Cependant, il n’est bien sûr pas impossible qu’une erreur se soit produite lors de la correction. Je reste donc à l’écoute. Faites-moi de vos interrogations (de préférence de vive voix à un inter-séances) en suivant l’une des procédures ci-dessous, après avoir fait l’effort de réflexion demandé.

== Nouvelle chance
Si vous souhaitez une nouvelle chance, vous pouvez plaider votre cause (par e-mail ou en séance) en m’expliquant ce qui n’a pas fonctionné et pourquoi. Par exemple, je vous octroierai généralement une nouvelle chance si la correction automatique vous a donné zéro parce que votre code n’était pas dans la bonne branche, ou qu’une petite faute de frappe l’a empêché de compiler, alors qu’il est bon à part ce détail.
Voici la procédure à suivre pour bénéficier d’une nouvelle correction si je vous y autorise.

Effectuez un nouveau push avec une correction de votre rendu, de façon à permettre au code de correction automatique de trouver votre rendu correctement. Dans l’exemple précédent, il s’agirait sans-doute de fusionner une branche vers une autre, ou de corriger la faute de frappe.

Vous devriez minimiser les changements par rapport au code remis initialement, en fonction de l’accord obtenu entre nous. Ainsi, dans l’exemple donné ci-dessus, vous devez vous en tenir à la fusion de branche ou à la correction de la faute de frappe.
Envoyez-moi un e-mail m’indiquant que vous avez procédé au push, en indiquant précisément ce que vous avez changé par rapport à l’état qui a été corrigé précédemment, et en indiquant un lien vers une https://docs.github.com/en/github/committing-changes-to-your-project/comparing-commits[différence sur GitHub] entre ces deux états. Privilégiez pour ce lien des différences entre branches, si possible, plutôt qu’entre commits, ce qui me permet de voir ce que vous comparez plus facilement.

Je relancerai alors la correction, et vous attribuerai comme note une combinaison de l’ancienne et de la nouvelle note.

Si la nouvelle chance est donnée à toute la classe, alors vous obtiendrez une combinaison de vos notes évaluant la remise originale et la nouvelle, *dépendant du nombre de lignes modifiées*. Elles sont comptées en considérant la différence ensembliste symétrique entre les lignes de votre fichier original et les lignes de votre nouveau fichier (additionnées sur tous les fichiers modifiés). Les changements d’ordre entre les lignes ne comptent donc pas. Attention, les différences de simples caractères tels que les espaces, les tabulations, les fins de lignes comptent comme des différences comme les autres (voir https://github.com/oliviercailloux/java-course/blob/main/Git/Best%20practices.adoc#end-of-lines[end of lines] et https://github.com/oliviercailloux/java-course/blob/main/Style/Code.adoc#formatting[formatting]). Lisez https://docs.github.com/en/github/committing-changes-to-your-project/comparing-commits[comparing commits] pour savoir comment vérifier visuellement que vous n’introduisez pas de changements inutiles.

== Procédure en cas de soupçon de bug de la correction automatique
Si vous pensez que le code de correction s’est trompé, c-à-d qu’il ne vous a pas donné les points alors qu’il aurait dû, envoyez-moi un e-mail en expliquant clairement ce que vous attendiez et ce que vous avez obtenu à la place. Indiquez un ou plusieurs liens vers votre code sur GitHub pour que je puisse voir facilement votre code ou d’autres informations pertinentes pour comprendre et vérifier vos affirmations.

Si vous avez raison, vous ne devez pas suivre la procédure ci-dessus : je corrigerai mon code et vous octroierai une nouvelle note.

// == Suivi des instructions
// Comme d’habitude, si une de ces instructions n’est pas claire ou ne vous semble pas applicable, je vous prie de m’en faire part. Si vous n’indiquez rien, je supposerai que vous n’avez pas bien lu les instructions, et vous renverrai à ce document.
