= Projet collectif

Un jeu de https://world-geography-games.com/en/countries_world.html[localisation géographique] de pays

https://classroom.github.com/a/2tc61U1b

== Généralités
- Deux superviseurices auront connaissance de l’état actuel de la branche dev.
- Sur volontariat, le projet sera éventuellement livré en open source en fin d’année.

== Préparation
- Chaque étudiante et étudiant doit bloquer deux créneaux sur la feuille partagée (lien via Moodle)
- Aucun créneau bloqué précédemment ne peut être libéré sans mon consentement, par contre il est permis d’échanger des créneaux jusqu’à l’avant-veille

== Que livrer
- Aller dans la section Projects puis sélectionner "Project Roadmap", possibilité de:
    * Choisir une tâche déjà commencé, section "In Progress"
    * Commencer une nouvelle tâche, section "Ready"
    * Ajouter une tâche, section "Backlog"
- Documenter en https://docs.asciidoctor.org/asciidoc/latest/[Asciidoc] et en https://plantuml.com/[PlantUML] dans le répertoire `Doc`, d’une façon accessible depuis le README
- Minimisez les changements : ne changez pas les espaces en fin de ligne, ne reformatez pas le code existant…
- Formattez correctement _votre_ code !

== Comment livrer
Cas où un étudiant commence une nouvelle tâche :

- S'actualiser avec la branche dev : `git pull origin dev`
- Créer une nouvelle branche : `git branch nom_tache`
- Se rendre sur la branche créée : `git checkout nom_tache`

Cas où un étudiant reprend une tâche déjà commencée :

- S'actualiser avec la branche de la tâche : `git pull origin nom_tache`
- Se rendre sur la branche de la tâche : `git checkout nom_tache`

Méthode de rendu :

- Push sur la branche : `git push origin nom_tache`
- Créer une https://docs.github.com/en/pull-requests[Pull Request] ou s'associer à une déjà existante : onglet "Pull Requests"
- La Pull Request doit avoir pour base la branche dev (par défaut)
- Il sera impossible de valider une Pull Request avec un code qui ne compile pas
- Remettre sur Moodle : indiquer pour chaque tâche un lien vers la Pull Request associée, ainsi qu'une description claire des modifications apportées.
