= Projets : démarrage

== Choix
Formez des équipes de 3 à 6 personnes.

Projet conceptuellement le plus simple : https://github.com/oliviercailloux/java-course/blob/main/L3/7%20wonders.adoc[7 wonders].

Plus difficile. Choisissez un projet ci-dessous parmi J-Voting ou https://github.com/oliviercailloux/Assisted-Board-Games[Assisted Board Games], ou un autre de la liste si vous me convainquez.
En regardant les projets ci-dessous, parcourez rapidement la description globale ou la documentation pour comprendre le contexte (mais ne vous focalisez pas sur les détails), et voyez le fichier TODO.adoc pour vous faire une idée approximative des tâches auxquelles vous serez confrontés. Les énoncés sont parfois très vagues, ne vous en inquiétez pas : ils seront peaufinés au fur et à mesure de l’année, en fonction du rythme d’avancement et de vos intérêts.
En outre, il y a, pour chacun de ces projets, bien plus de choses qui peuvent être faites que vous ne pourrez faire en un an. N’imaginez pas arriver au bout, voyez plutôt votre travail comme une contribution à un édifice en cours de construction.

* https://github.com/oliviercailloux/J-Voting[J-Voting]
* https://github.com/oliviercailloux/Assisted-Board-Games[Assisted Board Games]

* https://github.com/oliviercailloux/2D-Library[2D Library]
* https://github.com/oliviercailloux/Apartments[Apartments]
* https://github.com/oliviercailloux/J-Confs[J-Confs]
* https://github.com/oliviercailloux/MIDO-SVG[MIDO SVG]
* https://github.com/oliviercailloux/Teach-spreadsheets[Teach spreadsheets]
* https://github.com/oliviercailloux/projets/blob/master/J-XMCDA.adoc[J-XMCDA]

Les énoncés contiennent _beaucoup_ plus de propositions que ce que vous serez capables d’implémenter cette année. Placez l’emphase sur ce qui vous intéresse.

== Instructions
Vous êtes encouragés à travailler par paire (pair programming). Mais vous devez être seul responsable de certaines classes et éventuellement aspects du logiciel final, dans une proportion correspondant à une répartition raisonnablement équitable du travail.

Vous procéderez à trois livraisons, à la manière agile. Chacune doit fournir un produit utilisable, qui « fait quelque chose ». Vous êtes encouragés à me montrer votre avancement au fur et à mesure des séances.

. Livraison 1 : fin du dimanche 14 mai
. Livraison 2 : fin du dimanche 4 juin
. Livraison 3 : fin du dimanche 25 juin

Chaque livraison doit s’accompagner d’une documentation compacte (c-à-d succincte et éclairante) expliquant la structure et le fonctionnement de votre logiciel et vos contributions. La structure est décrite typiquement via un ou plusieurs diagrammes de classe (qui peuvent être dessinés à la main puis scannés), et éventuellement de diagrammes de séquence. Vos contributions sont indiquées sous forme d’une liste de responsabilités.

Vos notes seront individuelles et reflèteront vos contributions telles qu’indiquées dans les responsabilités.
Je jugerai entre autres des aspects suivants, selon ce qui est applicable. Les intervalles de pondération sont approximatifs.

* Découpe conceptuelle, contrat : clarté des interfaces, javadoc appropriée (non exigée partout) (jusqu’à 10/20)
* Implémentation technique : algorithmes appropriés, code en anglais compréhensible, programmation défensive (jusqu’à 7/20)
** Si vous modifiez du code existant, vous êtes responsable d’améliorer raisonnablement le code qui l’entoure là où c’est facile, de corriger les bugs évidents. Ne vous dédouanez pas d’erreurs évidentes sous prétexte que ce n’est pas vous qui avez écrit telle ligne de code.
** Privilégier des collections (List, Set, etc.) plutôt que des tableaux de types primitifs. Cela simplifie généralement l’extension future, et clarifie le code. Choisissez bien vos collections !
* Java (jusqu’à 6/20)
** Génériques appropriés
** Interfaces appropriées
** Usage des collections
* Couverture de tests (non nécessairement unitaires), qui doivent couvrir seulement et effectivement les aspects non triviaux (jusqu’à −8/20 sinon)
* Usage approprié de bibliothèques (jusqu’à −3/20 sinon)
** Vous devez utiliser autant que possible les technologies vues au cours et les standards ISO, W3C et JSR Java dans votre projet (par exemple, JSON-B ou JSON-P et non Jackson).
** Ne réinventez pas la roue ! Cela augmente votre base de code, donc rend la maintenance plus difficile. Réutilisez les bibliothèques existantes. Si le problème que vous souhaitez résoudre est raisonnablement commun, il existe sûrement une bibliothèque de bonne qualité prête à être réutilisée.
* POM Maven correct (jusqu’à −3/20 sinon)
* Doc (jusqu’à 5/20)
** UML doc correct
** Correspondance de la doc avec le code (complétude, compacité)

La dernière séance (vendredi 23 juin) sera l’occasion d’une présentation de votre approche et logiciel à la classe. Un vote pour le meilleur logiciel s’ensuivra.

Concrètement, vous livrerez en livrant un tag release-1 (ou 2, ou 3).

Voici encore quelques instructions et conseils généraux.

* Pensez à découper vos ajouts en tâches simples. Exemple : coder une classe pour enregistrer des commandes de produit, plutôt que coder un GUI qui permet de commander des produits.
* [[SEP]] Je dois voir vos changements facilement et les distinguer de code auto-généré ou importé sans changements de votre part et de simples modifications de formatage. Si par exemple vous ajoutez un canevas HTML de 100 fichiers, ou si vous modifiez le formatage du code, faites-le dans une branche dédiée, et créez une autre branche pour vos modifications de contenu (SEP).
* [[PLAGIAT]] Ne https://fr.wikipedia.org/wiki/Plagiat[plagiez] pas ! Lorsque vous intégrez du code d’autrui, il faut indiquer _clairement_ que le code n’est pas de vous, et sa provenance. Par exemple, mentionner dans le README de votre projet la provenance de votre template html. Ou, indiquer la provenance dans la javadoc d’une méthode copiée depuis StackOverflow. Cette règle ne s’applique pas si vous ne copiez que quelques lignes de code triviales.
* L’usage de moteurs de langue (type Chat GPT) pour vous aider est autorisé. Attention, ces moteurs peuvent être très utiles mais sont aussi très forts pour vous https://www.youtube.com/watch?v=R2fjRbc9Sa0[induire en erreur]. Ne les croyez jamais sur parole.

== Démarrage
//Effectuez un fork du dépôt de base m’appartenant. Cela vous crée un dépôt personnel sur GitHub que vous utiliserez pour votre groupe et où vous pouvez organiser les contributions comme vous voulez. Faites-en un dépôt privé si vous 

Une personne de votre groupe doit effectuer les étapes suivantes pour initialiser le projet.

* Acceptez https://classroom.github.com/g/kQjleEgF[cette mission], choisissez un nom d’équipe. Cela crée un nouveau « remote » pour votre projet.
* Si vous partez d’un project existant (projet ≠ 7 Wonders) :
** Clonez le projet dont vous partez sur votre machine pour créer un dépôt local contenant l’historique actuel du projet.
** Utilisez la commande `git remote` pour renommer le « remote » `origin` en `cailloux` sur votre dépôt local.
** Ajoutez le nouveau « remote » que vous venez de créer à votre dépôt local, nommez-le `origin` (cf. instructions de GitHub, utilisez `git remote add origin` etc.).
* Si vous partez de zéro (projet 7 Wonders) :
** Clonez le remote localement, effectuez un push initial (un fichier suffit)
* M’ajouter comme collaborateur à votre projet pour pouvoir m’indiquer comme https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews[Reviewer] lors de vos itérations.
* Créez un tag `start` qui pointe vers l’état de départ de votre projet et éventuellement une branche `current-release` qui contiendra à terme vos contributions.

Chaque membre doit ensuite faire ceci.

* Cloner le projet ainsi créé sur sa machine locale
* Accepter la même mission ci-dessus et rejoindre la même équipe (pour devenir admin du projet et donc avoir accès en écriture)

Prenez le temps de réfléchir ensemble globalement au projet et tracez les grandes lignes de votre ambition à la fin de l’année. 
Placez l’emphase en fonction de vos intérêts (plutôt GUI, plutôt manipulation de fichiers, plutôt web, …).
Ceci est utile pour construire un sens commun de votre objectif global.
Inutile d’élaborer un plan détaillé ! 
