= Projets : Instructions générales

== Démarrage d’une itération

=== Rôles
* Une équipe de _n_ personnes est constituée de _n/2_ (arrondi au-dessus) sous-équipes
** une sous-équipe est constituée de un (si _n_ est impair) ou deux (si _n_ est pair) Scrum Master / Product Owner, nommée ci-après « le SM/PO » pour désigner la sous-équipe, même quand ils sont deux
** les autres sous-équipes sont constituées de binômes d’architectes développeurs
* Les sous-équipes doivent changer à chaque itération ; le rôle de SM/PO doit être réparti égalitairement

=== Responsabilités
* SM/PO : vérifie le respect des _tâches_ à délivrer ; réoriente les tâches en cas de problème de prérequis ; vérifie la qualité des rendus, entre autres, en relisant les propositions avant soumission ; vérifie que le projet fonctionne toujours après fusion ; est responsable de la cohérence du tout
* Un binôme d’architectes développeurs travaille sur une ou plusieurs tâches dans une itération. Une tâche peut consister à compléter une tâche précédente (ajout de tests unitaires, correction bugs, …).

=== Plan
* Le SM/PO commence l’itération en indiquant dans le README du projet un plan indiquant sur quoi portera cette itération, en accord avec l’équipe et le client. Ceci se fait par une PR, que je dois approuver avant le démarrage du travail (cf. ci-dessous).
* Le plan de l’itération contient une découpe en tâches et pour chacune une affectation à un binôme et ses pré-requis éventuels (d’autres tâches).
* Conseil : une découpe en tâches très élémentaires simplifiera grandement votre travail, surtout au début.
* Une mission importante de l’équipe est de s’assurer que le projet converge vers un ensemble cohérent de fonctionnalités exploitables dans la branche `main`. Tentez de terminer en priorité les tâches presque finies qui ne sont pas encore dans `main`, par exemple, avant de commencer de nouvelles choses.

En interne, réfléchissez à un calendrier pour éviter de coincer les sous-équipes qui dépendent des autres et à un plan de repli. C’est la responsabilité principale, mais pas exclusive, du SM/PO.

== Instructions de livraison
Chaque itération se conclut par une livraison.

Dates de livraison précisées dans le programme du cours. https://www.wolframalpha.com/input/?i=Plot%5BPiecewise%5B%7B%7B-1%2F2*x,x%3C+2%7D,%7B-2%2F22*(x-2)-1,+2%3C%3D+x+%3C+24%7D,%7B-1%2F24*x-2,+24%3C%3D+x%7D%7D%5D,+%7Bx,+0,+72%7D%5D[Non respect] des dates : −0.5/20 pour 2h de retard, −3 (en tout) pour 24h de retard puis −1 par jour supplémentaire.

* ENG : codez et documentez en anglais

* Interdiction de commettre sur votre branche `main` sans mon aval. À part ça, organisation interne libre. Suggestion : une branche par tâche, et fusionnez vos fcts sur une branche `dev` au fur et à mesure (https://fr.wikipedia.org/wiki/Int%C3%A9gration_continue[intégration continue]).
* M’ajouter comme collaborateur à votre projet pour pouvoir m’indiquer comme https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews[Reviewer].
* Créez une https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests[pull request] (PR) GitHub pour chaque tâche, dont le nom décrit succinctement la tâche (exemple : « unit-tests-Truc »), d’une de vos branches vers _votre_ branche `main`.
** https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users[Affectez] la PR aux membres de la sous-équipe responsable de la tâche. Si un membre d’un binôme n’a pas contribué, indiquez-le en affectant un seul membre, j’en tiendrai compte dans mon évaluation (travail de qualité plus difficile seul).
** Affectez votre PR à une https://help.github.com/en/github/managing-your-work-on-github/about-milestones[milestone] « Itération x UML » ou « Itération x Java », avec x = 1 si c’est la première itération, et ainsi de suite.
** M’ajouter comme Reviewer pour que je sois averti, _uniquement si vous êtes effectivement prêts pour une review_, c-à-d entre autres si la tâche n’a pas de pré-requis à reviewer et fusionner avant, et les auteurs et le SM/PO jugent le rendu de bonne qualité.
** Les changements visibles dans une PR doivent être tous en rapport avec votre tâche, elle-même focalisée sur un sujet bien défini (FOCUS).
** [[NICE]] Vous remettez un projet, pas un brouillon mal torché. Imaginez que c’est un rendu à un client. Soignez-le. Votre code, vos documents doivent être propres, bien formatés, vous devez prendre en compte d’éventuelles indications d’erreurs de vos outils (Eclipse, GitHub, …), etc. Faites tout ça _avant_ de m’indiquer comme reviewer sur une PR. (NO DRAFT)
* Je commente votre tâche pour indiquer les améliorations à effectuer avant de pouvoir fusionner dans `main`, ou je vous indique que vous pouvez fusionner.
** Tant que l’itération est en cours, vous pouvez (et vous devriez, si vos collègues attendent votre tâche) modifier directement sans attendre la prochaine livraison. Dans ce cas, effectuez des commits sur la branche de votre tâche (car vous pouvez compléter une PR après sa création en ajoutant des commit dans la branche associée), commentez, et ré-indiquez-moi comme reviewer pour que je sois averti quand vous êtes prêts pour une nouvelle review. 
** Ne réécrivez jamais l’historique dans `main`, il doit uniquement s’enrichir.
* [[FOLLOW-UP]] Une tâche est effectuée en une seule itération. Une fois notée, cette tâche doit être considérée comme définitivement terminée (cela permet de s’y retrouver dans les notes). Fermez SVP les PRs correspondantes, pour qu’on voie directement ce qui concerne l’itération en cours. (CLOSE) Si votre tâche poursuit une tâche d’une livraison précédente, il s’agit quand-même d’une nouvelle tâche. Créez une nouvelle branche (par exemple « unit-tests-Truc-it-3 ») partant de votre branche existante. Lorsque vous créez la nouvelle PR, indiquez en commentaire que la tâche fait suite à la PR #x, en respectant précisément cette syntaxe pour la liaison automatique de GitHub, et commentez en indiquant ce que vous avez changé par rapport à la version précédente. (FOLLOW-UP)

== Communication
* [[MENTION]] Évitez de me mentionner (`@oliviercailloux`) dans vos PR sur GitHub SVP : cela a pour effet de me noyer de notifications (que GitHub ne permet pas de désactiver facilement), or, je ne peux pas m’investir dans des discussions du tac-au-tac pour chaque groupe d’étudiants que je suis. Re-demandez plutôt une review quand vous êtes prêts, après avoir répondu à autant de points que possibles : je regarderai toutes vos réponses en même temps.
* Maintenez les conversations focalisées. Ce n’est pas une bonne idée, par exemple, d’indiquer dans un commentaire de la PR #37 que vous avez décidé d’abandonner la PR #22 pour telle et telle raison : quand j’évaluerai la PR #22 par la suite, il est peu probable que je me souvienne de vos explications se trouvant en PR #37.
* Si vous souhaitez contester mon évaluation ou me poser une question, commentez dans la PR adéquate, et re-demandez une review lorsque vous êtes prêts, comme ci-dessus.
* N’hésitez pas à m’écrire si vous êtes bloqués, n’attendez pas d’avoir perdu plusieurs heures. Cependant, je vous demande de faire l’effort de poser des questions raisonnablement claires et complètes, et de m’indiquer ce que vous avez essayé et votre analyse de la situation. Voyez ces https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/[directives] pour vous inspirer. Si votre question peut intéresser les autres membres du groupe ou qu’il est utile de conserver la discussion pour référence future, créez une issue sur votre projet GitHub où vous décrivez votre problème et demandez-moi (par e-mail par exemple) d’y répondre en me donnant le lien. (ISSUE)
* Envoyez-moi un e-mail sans délai si vous ne comprenez pas ce que j’attends, ou si vous n’avez pas de nouvelles de moi après 48h alors que vous attendez une réaction de ma part.
* Si vous souhaitez discuter de mon évaluation, ou préciser qqch. au sujet d’une tâche passée, de même que ci-dessus : commentez dans la PR correspondante, et re-demandez-moi une review pour que je sois averti de l’existence de nouveaux commentaires.

Lorsque j’utilise des abréviations (termes en majuscules), elles font référence aux documents donnant les consignes pour le projet, tels que celui-ci, ou aux https://github.com/oliviercailloux/java-course/tree/master/Best%20practices[bonnes pratiques] quand l’abréviation commence par BP.

J’indique (OPT) lorsque mon commentaire a pour but principal de vous indiquer comment vous auriez pu faire mieux. (Il s’agit généralement d’une erreur mineure ou d’une amélioration possible de la clarté du code mais qui ne l’empêche pas de fonctionner.) Vous êtes invités à modifer si cela ne vous retarde pas outre-mesure, mais je ne l’exige pas avant fusion dans `main` ; ou vous pouvez l’indiquer comme une issue (comme si c’était un FUTURE), ou simplement laisser tomber si vous trouvez que c’est un détail peu intéressant.

Lorsque j’ajoute (FUTURE?) à un commentaire, de même, je n’exige pas une résolution du problème avant fusion dans `main` (pour vous permettre d’avancer sur d’autres fonctionnalités à court terme). Si vous décidez de ne pas le résoudre toute suite, je vous prie d’ouvrir une Issue sur votre projet et d’y reporter mon commentaire (éventuellement reformulé par vos soins pour le clarifier) et un lien vers l’endroit où j’ai fait le commentaire (pour retrouver le contexte). Vous êtes priés de vous occuper de ces issues lors d’itérations futures, en discussion avec moi selon les besoins.

Veuillez noter que pour ce cours, je mets à disposition des étudiants des instructions de remise précises, qui me permettent de faciliter mon suivi. Ce serait une tâche déraisonnablement chronophage pour moi de tenter de fournir aux étudiants des commentaires personnalisés et détaillés sur leurs rendus s’ils ne jouent pas le jeu en essayant de suivre les instructions de remise ; ou de tenter de récapituler certaines instructions au cas par cas à chaque étudiant qui ne prend pas la peine de les lire.  C’est pourquoi je me permettrai d’insister pour que vous relisiez attentivement les instructions ici présentes lorsque la réponse à certaines de vos questions me semblent y figurer. Même si le manquement semble parfois relever du détail sans importance aux étudiants, j’insiste sur la lecture des instructions car elle permet une probable meilleure communication pour le reste de l’année, et pour traiter les étudiants également. Dans ce cas, je vous répondrai comme suit. _Je me permets de vous renvoyer à la lecture des instructions de remise et de communication, et en particulier le paragraphe (COMPLIANCE). Dites-moi SVP si qqch. n’est pas clair. Merci pour votre compréhension._ (Compliance)

Vous pouvez bien sûr remettre certaines de ces consignes en question si elles vous semblent non pertinentes. Mais dans ce cas, je vous demande au moins de me montrer que vous les avez lues en y faisant référence explicitement dans votre discussion avec moi et en m’expliquant pourquoi vous pensez qu’elles ne s’appliquent pas.

== Évaluation
* À la date de cloture de la livraison, j’évaluerai vos tâches effectuées durant toute l’itération. Je retarderai la date de livraison à la demande de l’équipe, mais cela induira une pénalité de retard sur tout 
le projet (cf. ci-dessus). 
* Chaque binôme d’architectes développeurs reçoit une note par livraison (agrégeant mon évaluation de l’ensemble de ses tâches durant cette itération). Le SM/PO reçoit la note moyenne de l’itération, sauf circonstances particulières (si par exemple le SM/PO a été particulièrement négligeant).
* Plus j’ai insisté sur des erreurs à éviter, plus la notation sera sévère si ces erreurs sont commises.
* Il faut impérativement respecter les pré-requis. Si par exemple, suite à un problème d’organisation dans le groupe, vous livrez une tâche qui n’apporte encore rien parce qu’elle dépend d’un pré-requis qui n’a pas été livré, vous serez nécessairement en échec, même si le retard sur le pré-requis n’est pas de votre faute. Exemple : développement d’un GUI alors que les fonctionnalités manquent. Le code livré doit fonctionner et je dois avoir les éléments en main pour comprendre son intérêt. (Des exceptions légitimes existent, à discuter au cas par cas avec moi au moment de l’élaboration de votre plan.)
* L’évaluation tient compte particulièrement de la qualité du travail fourni (potentiel de réutilisabilité, facilité d’appropriation par d’autres développeurs, facilité de maintenance à long terme, clarté de la documentation), et en second lieu seulement de la quantité (bonus / malus si le travail accompli prendrait sensiblement plus / moins que le temps attendu pour cette itération si effectué par un étudiant attentif au cours et suivant les recommandations), et prend fortement en compte la difficulté de la tâche (technologies non vues au cours, …).
* Note finale projet : moyenne de vos notes de livraison et de la présentation finale.

