= Projets

== Instructions générales
* Dates de livraison précisées dans le programme du cours. https://www.wolframalpha.com/input/?i=Plot%5BPiecewise%5B%7B%7B-1%2F2*x,x%3C+2%7D,%7B-2%2F22*(x-2)-1,+2%3C%3D+x+%3C+24%7D,%7B-1%2F24*x-2,+24%3C%3D+x%7D%7D%5D,+%7Bx,+0,+72%7D%5D[Non respect] des dates : −0.5/20 pour 2h de retard ou −3 pour 24h de retard, puis −1 par jour supplémentaire.
* Une équipe de _n_ personnes est constituée de _n/2_ (arrondi au-dessus) sous-équipes : des binômes de développeurs et une sous-équipe de un ou deux Scrum Master / Product Owner (nommée ci-après « le SM/PO » pour désigner la sous-équipe, même quand ils sont deux)
* Sous-équipes doivent changer à chaque itération ; le rôle de SM/PO doit être réparti égalitairement
* SM/PO : vérifie le respect des _tâches_ à délivrer ; fait appliquer les https://github.com/oliviercailloux/java-course/tree/master/Best%20practices/[bonnes pratiques] ; réoriente les tâches en cas de problème de prérequis ; vérifie que le projet fonctionne toujours après fusion ; est responsable de la cohérence du tout
* Un binôme de développeurs travaille sur une (typiquement) ou plusieurs tâches dans une itération (exemple : coder une classe pour enregistrer des commandes de produit). Une tâche peut consister à compléter une tâche précédente (ajout de tests unitaires, correction bugs, …).
* Vos fonctionnalités doivent être couvertes par des tests unitaires, considérés comme partie intégrante de chaque tâche et soumis en même temps que le code testé.

N’hésitez pas à m’écrire si vous êtes bloqués, n’attendez pas d’avoir perdu plusieurs heures. Cependant, je vous demande de faire l’effort de poser des questions raisonnablement claires et complètes, et de m’indiquer ce que vous avez essayé et votre analyse de la situation. Voyez ces https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/[directives] pour vous inspirer. Si votre question peut intéresser les autres membres du groupe ou qu’il est utile de conserver la discussion pour référence future, créez une issue sur votre projet GitHub où vous décrivez votre problème et demandez-moi (par e-mail par exemple) d’y répondre en me donnant le lien. (ISSUE)

== Pour commencer votre projet
Commencez par lire et appliquer les bonnes pratiques de https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Style.adoc[style].

Voici quelques points de départ possibles pour améliorer le projet.

* Indiquer par un bref commentaire sur chaque dépendance son utilité, vérifier versions, retirer les inutiles
* JUnit 5 et non JUnit 4
* Appliquer des créateurs statiques, constructeurs privés, immuabilité autant que possible, champs privés
* Éviter redondance (code dupliqué, logique dupliquée…)
* Améliorer lisibilité du code
* Prendre en compte warnings Eclipse
* Utiliser les https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Local%20design.adoc[canevas suggérés] pour implémenter `#toString()`, `#equals()`, `#hashcode()`

== Instructions de livraison
* Interdiction de commettre sur votre branche `main` sans mon aval. À part ça, organisation interne libre. Suggestion : une branche par tâche, et fusionnez vos fcts sur une branche `dev` au fur et à mesure (https://fr.wikipedia.org/wiki/Int%C3%A9gration_continue[intégration continue]).
* M’ajouter comme collaborateur à votre projet pour pouvoir m’indiquer comme https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews[Reviewer].
* Quand vous avez terminé une tâche, créez une https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests[pull request] (PR) GitHub pour cette tâche, dont le nom décrit succinctement la tâche (exemple : « unit-tests-Truc »), d’une de vos branches vers _votre_ branche `main`.
** https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users[Affectez] la PR au membre ou aux deux membres de la sous-équipe responsable de la tâche.
** Affectez votre PR à une https://help.github.com/en/github/managing-your-work-on-github/about-milestones[milestone] « Itération x », avec x = 1 si c’est la première itération, et ainsi de suite.
** M’ajouter comme Reviewer pour que je sois averti, uniquement si vous êtes effectivement prêts pour une review, c-à-d entre autres si la tâche n’a pas de pré-requis à reviewer et fusionner avant.
** [[SEP]] Je dois voir vos changements facilement et les distinguer de code auto-généré ou importé sans changements de votre part et de simples modifications de formatage. Si par exemple vous ajoutez un canevas HTML de 100 fichiers, ou si vous modifiez le formatage du code, faites-le dans une tâche dédiée, et créez une autre tâche pour vos modifications de contenu (SEP). Les changements visibles dans une PR doivent être tous en rapport avec votre tâche, elle-même focalisée sur un sujet bien défini (FOCUS).
** [[NICE]] Vous remettez un projet, pas un brouillon mal torché. Soignez-le. Votre code doit être mis en forme systématique, suivre les https://github.com/oliviercailloux/java-course/tree/master/Best%20practices[bonnes pratiques], vous devez prendre en compte d’éventuelles indications d’erreurs de vos outils (Eclipse, GitHub, Travis, …), etc. Faites tout ça _avant_ de m’indiquer comme reviewer sur une PR. (NICE)
* Si opportun, je commente votre tâche pour indiquer les améliorations à effectuer avant de pouvoir fusionner dans `main`, ou je vous indique que vous pouvez fusionner.
** Vous pouvez (et vous devriez, si vos collègues attendent votre tâche) modifier directement sans attendre la prochaine livraison. Dans ce cas, effectuez des commits sur la branche de votre tâche (car vous pouvez compléter une PR après sa création en ajoutant des commit dans la branche associée), commentez, et ré-indiquez-moi comme reviewer pour que je sois averti quand vous êtes prêts pour une nouvelle review. 
** [[MENTION]] Évitez de me mentionner (`@oliviercailloux`) SVP : je ne peux pas m’investir dans des discussions du tac-au-tac pour chaque groupe d’étudiants que je suis. Re-demandez plutôt une review quand vous êtes prêts, après avoir répondu à autant de points que possibles : je regarderai toutes vos réponses en même temps. (Je reste bien sûr disponible par e-mail si besoin de me contacter en privé.)
* [[FOLLOW-UP]] Une tâche est effectuée en une seule itération. Une fois notée, cette tâche doit être considérée comme définitivement terminée (cela permet de s’y retrouver dans les notes). Si votre tâche poursuit une tâche d’une livraison précédente, il s’agit quand-même d’une nouvelle tâche. Créez une nouvelle branche (par exemple « unit-tests-Truc-it-3 ») partant de votre branche existante. Lorsque vous créez la nouvelle PR, indiquez en commentaire que la tâche fait suite à la PR #x. (FOLLOW-UP)
* Si vous ne respectez pas les instructions et que cela m’empêche de donner une note, j’indiquerai INSTR, éventuellement associé de mots-clés (SEP, FOLLOW-UP, etc.). Dans ce cas, _cette PR n’est pas acceptée pour cette livraison_. J’attends une correction pour respect des instructions. (Suivez les instructions de modification sur une même branche, ci-dessus.) En attendant, votre délai de retard cours, si la date de livraison est dépassée. (Seule cette abréviation INSTR indique que votre PR n’est pas acceptée. Si j’utilise d’autres abréviations, elles se réfèrent généralement à la table ci-dessous, et font partie de mon évaluation normale de votre tâche.) Envoyez-moi un e-mail sans délai si vous pensez que vous avez bien respecté les instructions ou si vous ne comprenez pas ce que j’attends.

Lors de la dernière itération, vous ajouterez dans votre README de projet une ligne indiquant, pour chacun d’entre vous, la diversité des tâches auxquelles vous avez participé (exemple : GUI dans tâche Truc, test unitaire dans tâche Bidule, parsing XML dans tâche Machin), et éventuellement un commentaire bref indiquant les difficultés particulières auxquelles vous avez été confronté dans votre projet ou dans vos tâches en particulier, pour attirer mon attention lors de l’évaluation finale.

== Évaluation
* Chaque binôme de développeurs reçoit une note par livraison (agrégeant mon évaluation de l’ensemble de ses tâches durant cette itération). Le SM/PO reçoit simplement une appréciation `++`, `+`, `~`, `−`, `−−`. Cette appréciation sera transformée en la note moyenne de la personne évaluée au moment de l’agrégation finale, avec un bonus ou un malus.
* Plus j’ai insisté en cours sur des erreurs à éviter, plus la notation sera sévère si ces erreurs sont commises (par exemple, masquer les exceptions).
* Il faut impérativement respecter les pré-requis. Si par exemple, suite à un problème d’organisation dans le groupe, vous livrez une tâche qui n’apporte encore rien parce qu’elle dépend d’un pré-requis qui n’a pas été livré, vous serez nécessairement en échec, même si le retard sur le pré-requis n’est pas de votre faute. Exemple : développement d’un GUI alors que les fonctionnalités manquent. Le code livré doit fonctionner et je dois avoir les éléments en main pour comprendre son intérêt. (Vous pouvez parfois coder certaines choses par exemple qui dépendent d’une interface existante n’ayant pas encore d’implémentation finalisée ; mais c’est à discuter au cas par cas avec moi au moment de l’élaboration de votre plan.)
* L’évaluation tient compte particulièrement de la qualité du travail fourni (potentiel de réutilisabilité, facilité d’appropriation par d’autres développeurs, facilité de maintenance à long terme, clarté de la documentation), et en second lieu seulement de la quantité (bonus / malus si le travail accompli prendrait sensiblement plus / moins que le temps attendu pour cette itération si effectué par un étudiant attentif au cours et suivant les recommandations), et prend fortement en compte la difficulté de la tâche (technologies non vues au cours, …).
* Si un membre d’un binôme n’a pas travaillé durant une livraison, indiquez-le en affectant un seul membre aux tâches de cette livraison. J’en tiendrai compte dans mon évaluation (travail de qualité plus difficile seul).
* Note finale projet : moyenne de vos notes de livraison, avec bonus / malus pour la diversité de vos tâches, les éventuelles difficultés particulières, la cohésion de l’équipe et la cohérence globale de son projet, et la présentation finale.
* Vous devez utiliser autant que possible les technologies vues au cours et les standards ISO, W3C et JSR Java dans votre projet (par exemple, JSON-B ou JSON-P et non Jackson).
* Si vous modifiez du code existant, vous êtes responsable d’améliorer raisonnablement le code qui l’entoure là où c’est facile, de corriger les bugs évidents. Ne vous dédouanez pas d’erreurs évidentes sous prétexte que ce n’est pas vous qui avez écrit telle ligne de code.
* [[PLAGIAT]] Lorsque vous intégrez du code d’autrui, il faut indiquer _clairement_ que le code n’est pas de vous, et sa provenance. Par exemple, mentionner dans le README de votre projet la provenance de votre template html. Ou, indiquer la provenance dans la javadoc d’une méthode copiée depuis StackOverflow. Cette règle ne s’applique pas si vous ne copiez que quelques lignes de code triviales.
* Maintenez les conversations focalisées. Ce n’est pas une bonne idée, par exemple, d’indiquer dans un commentaire de la PR #37 que vous avez décidé d’abandonner la PR #22 pour telle et telle raison : quand j’évaluerai la PR #22 par la suite, il est peu probable que je me souvienne de vos explications se trouvant en PR #37.
* Une mission importante de l’équipe est de s’assurer que le projet converge vers un ensemble cohérent de fonctionnalités exploitables dans la branche `main`. Tentez de terminer en priorité les tâches presque finies qui ne sont pas encore dans `main`, par exemple, avant de commencer de nouvelles choses.

=== Abréviations
J’indique (OPT) lorsque mon commentaire a pour but principal de vous indiquer comment vous auriez pu faire mieux. (Il s’agit généralement d’une erreur mineure ou d’une amélioration possible de la clarté du code mais qui ne l’empêche pas de fonctionner.) Vous êtes invités à modifer si cela ne vous retarde pas outre-mesure, mais je ne l’exige pas avant fusion dans `main` ; ou vous pouvez l’indiquer comme une issue (comme si c’était un FUTURE), ou simplement laisser tomber si vous trouvez que c’est un détail peu intéressant ; mais tenez-en compte en tous cas pour vos prochaines PRs !

Lorsque j’ajoute (FUTURE?) à un commentaire, de même, je n’exige pas une résolution du problème avant fusion dans `main` (pour vous permettre d’avancer sur d’autres fonctionnalités à court terme). Si vous décidez de ne pas le résoudre toute suite, je vous prie d’ouvrir une Issue sur votre projet et d’y reporter mon commentaire (éventuellement reformulé par vos soins pour le clarifier) et un lien vers l’endroit où j’ai fait le commentaire (pour retrouver le contexte). Vous êtes priés de vous occuper de ces issues lors d’itérations futures, en discussion avec moi selon les besoins.

D’autres abbréviations sont indiquées ci-dessous, et dans ce document (en majuscules).

|===
| Abbrv | Pratique à respecter | Informations
| INSTR | Respect des instructions concernant la remise (création issues, etc.) | Instructions / project
| UNIK	| noms des ressources est unique et respecte les bonnes pratiques	| https://github.com/oliviercailloux/java-course/tree/master/Search%20path[Search path]
| HIST	| Ne pas écraser l’historique	| Git
| PLAG	| Citer la source quand on inclut du code d’autrui	| https://fr.wikipedia.org/wiki/Plagiat[Plagiat]
| ECL	| Le code est correct d’après Eclipse : pas de warnings, pas de `@SuppressWarnings` injustifiés	| https://github.com/oliviercailloux/java-course/blob/master/Tools.adoc#configuration[Tools]
| EXC	| Le code échoue rapidement et envoie des exceptions si approprié	| https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Exceptions.adoc#cath-exceptions-only-if-you-have-a-good-reason-to-do-so[BP Exc]
| REUSE	| Les bibliothèques existantes sont utilisées à bon escient plutôt que réinventer la roue	|  Code écrit non considéré positivement
| ARRAY	| Privilégier des collections (List, Set, etc.) plutôt que des tableaux de types primitifs	|
| EN	| Coder et commenter en anglais	|	
| FORE	| Privilégier boucles for each	| https://docs.oracle.com/javase/tutorial/java/nutsandbolts/for.html[Tutorial]
|===

