= Projets : Instructions Java

Voir aussi : https://github.com/oliviercailloux/java-course/blob/main/Projets%20-%20D%C3%A9marrage.adoc[Démarrage] ; https://github.com/oliviercailloux/java-course/blob/main/L3/Projets.adoc[Instructions générales].
Ce document contient les instructions spécifiques au cours de Java.

* Vos fonctionnalités doivent être couvertes par des tests unitaires, considérés comme partie intégrante de chaque tâche et soumis en même temps que le code testé.
* Pensez à découper vos ajouts en tâches simples. Exemple : coder une classe pour enregistrer des commandes de produit, plutôt que coder un GUI qui permet de commander des produits.
* [[SEP]] Je dois voir vos changements facilement et les distinguer de code auto-généré ou importé sans changements de votre part et de simples modifications de formatage. Si par exemple vous ajoutez un canevas HTML de 100 fichiers, ou si vous modifiez le formatage du code, faites-le dans une tâche dédiée, et créez une autre tâche pour vos modifications de contenu (SEP).
* Vous devez utiliser autant que possible les technologies vues au cours et les standards ISO, W3C et JSR Java dans votre projet (par exemple, JSON-B ou JSON-P et non Jackson).
* Ne réinventez pas la roue ! Cela augmente votre base de code, donc rend la maintenance plus difficile. Réutilisez les bibliothèques existantes. Si le problème que vous souhaitez résoudre est raisonnablement commun, il existe sûrement une bibliothèque de bonne qualité prête à être réutilisée. (Si vous ne tenz pas compte de ce conseil, je considérerai votre code écrit inutilement comme pénalisant pour votre note s’il contient des imperfections ; et jamais de façon positive.)
* Si vous modifiez du code existant, vous êtes responsable d’améliorer raisonnablement le code qui l’entoure là où c’est facile, de corriger les bugs évidents. Ne vous dédouanez pas d’erreurs évidentes sous prétexte que ce n’est pas vous qui avez écrit telle ligne de code.
* Privilégier des collections (List, Set, etc.) plutôt que des tableaux de types primitifs. Cela simplifie généralement l’extension future, et clarifie.
* [[PLAGIAT]] Ne https://fr.wikipedia.org/wiki/Plagiat[plagiez] pas ! Lorsque vous intégrez du code d’autrui, il faut indiquer _clairement_ que le code n’est pas de vous, et sa provenance. Par exemple, mentionner dans le README de votre projet la provenance de votre template html. Ou, indiquer la provenance dans la javadoc d’une méthode copiée depuis StackOverflow. Cette règle ne s’applique pas si vous ne copiez que quelques lignes de code triviales.

