= Projets : Instructions générales

== Démarrage d’une itération

=== Rôles
* Une équipe de _n_ personnes est constituée de _n/2_ sous-équipes, arrondi au-dessus
** une sous-équipe est constituée de une (si _n_ est impair) ou deux (si _n_ est pair) personnes, les Scrum Master / Product Owner, nommés ci-après « les SM/PO » pour désigner la sous-équipe, même quand une seule personne la constitue
** les autres sous-équipes sont constituées de binômes d’architectes développeuses et architectes développeurs (« binôme », ci-après)
* Les sous-équipes doivent changer à chaque itération ; le rôle de SM/PO doit être réparti égalitairement

=== Responsabilités
* SM/PO : planifient avec leur équipe les tâches à délivrer et le respect des instructions de livraison ; réorientent les tâches en cas de problème de prérequis ; vérifient la qualité des rendus, entre autres, en relisant les propositions avant soumission ; fusionnent les tâches approuvées en fin d’itération et vérifient que le projet fonctionne toujours après fusion ; sont responsables de la cohérence du tout
* Un binôme travaille sur une ou plusieurs tâches dans une itération. Une tâche peut consister à compléter une tâche précédente (ajout de tests unitaires, correction bugs, …).

=== Plan
* Commencez l’itération en choisissant son contenu, parmi les tâches à effectuer. Vous pouvez proposer des changements ou discuter de leurs priorités avec votre client. Conseil : une découpe en tâches très élémentaires simplifiera grandement votre travail, surtout au début.
* Répartissez les tâches choisies parmis les binômes. Réfléchissez à un calendrier pour éviter de coincer les sous-équipes qui dépendent des autres et à un plan de repli. C’est la responsabilité principale, mais pas exclusive, des SM/PO.
* Une mission importante de l’équipe est de s’assurer que le projet converge vers un ensemble cohérent de fonctionnalités exploitables et maintenables dans la branche `main`. Tentez d’améliorer en priorité les tâches à preaufiner, par exemple, avant de commencer de nouvelles choses.

== Instructions de livraison
Chaque itération se conclut par une livraison.

Dates de livraison précisées dans le programme du cours. https://www.wolframalpha.com/input/?i=Plot%5BPiecewise%5B%7B%7B-1%2F2*x,x%3C+2%7D,%7B-2%2F22*(x-2)-1,+2%3C%3D+x+%3C+24%7D,%7B-1%2F24*x-2,+24%3C%3D+x%7D%7D%5D,+%7Bx,+0,+72%7D%5D[Non respect] des dates : −0.5/20 pour 2h de retard, −3 (en tout) pour 24h de retard puis −1 par jour supplémentaire.

* Codez et documentez en anglais (ENG).
* Interdiction de commettre sur votre branche `main` sans mon aval. À part ça, organisation interne libre. Suggestion : une branche par tâche, et demandez-moi une review assez tôt si vous voulez fusionner en avance en cas de liens de prérequis (https://fr.wikipedia.org/wiki/Int%C3%A9gration_continue[intégration continue]).
* Créez une https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-requests[pull request] (PR) GitHub pour chaque tâche, dont le nom décrit succinctement la tâche (exemple : « unit-tests-Truc »), d’une de vos branches vers _votre_ branche `main`.
** https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users[Affectez] la PR aux membres de la sous-équipe responsable de la tâche. Si un membre d’un binôme n’a pas contribué, indiquez-le en affectant un seul membre, j’en tiendrai compte dans mon évaluation (le travail de qualité est plus difficile seul).
** Affectez votre PR à une https://help.github.com/en/github/managing-your-work-on-github/about-milestones[milestone] « Itération x UML » ou « Itération x Java », avec x = 1 si c’est la première itération, et ainsi de suite. (Respectez l’orthographe précise SVP, sinon mes liens ne fonctionnent pas.)
** M’ajouter comme Reviewer pour que je sois averti, _uniquement si vous êtes effectivement prêts pour une review_, c-à-d entre autres si la tâche n’a pas de pré-requis à reviewer et fusionner avant, et les auteurs et les SM/PO jugent le rendu de bonne qualité.
** Les changements visibles dans une PR doivent être tous en rapport avec votre tâche, elle-même focalisée sur un sujet bien défini (FOCUS).
** [[NICE]] Vous remettez un projet, pas un brouillon mal torché. Imaginez que c’est un rendu à un client. Soignez-le. Votre code, vos documents doivent être propres, https://github.com/oliviercailloux/java-course/blob/master/Style/Code.adoc[bien formatés], vous devez prendre en compte d’éventuelles indications d’erreurs de vos outils (Eclipse, GitHub, …), etc. Faites tout ça _avant_ de m’indiquer comme reviewer sur une PR. (NO DRAFT)
* Je commente votre tâche pour indiquer les améliorations à effectuer et je vous indique si vous pouvez fusionner en l’état (https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#about-pull-request-reviews[`Request changes` VS `Approve`]).
** Tant que l’itération est en cours, vous pouvez (et vous devriez, si vos collègues attendent votre tâche) modifier directement sans attendre la prochaine livraison. Dans ce cas, effectuez des commits sur la branche de votre tâche (car vous pouvez compléter une PR après sa création en ajoutant des commit dans la branche associée), commentez, et https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#re-requesting-a-review[re-demandez-moi une review] pour que je sois averti quand vous êtes prêts pour une nouvelle review. 
** Ne réécrivez jamais l’historique dans `main`, il doit uniquement s’enrichir.
* [[FOLLOW-UP]] Une tâche est effectuée en une seule itération. Une fois notée, cette tâche doit être considérée comme définitivement terminée (cela permet de s’y retrouver dans les notes). Fermez SVP les PRs correspondantes, pour qu’on voie directement ce qui concerne l’itération en cours. (CLOSE)
* Enrichissez le document listant les tâches à faire avec des liens vers mes commentaires sur les PRs pour indiquer ce qu’il faut améliorer. Ces améliorations constituent de nouvelles tâches, même si elles poursuivent une tâche d’une livraison précédente.
* Lorsque vous créez une PR correspondant à une tâche améliorant une PR précédente, indiquez en commentaire que la tâche fait suite à la PR #x, en respectant précisément cette syntaxe pour la liaison automatique de GitHub, et commentez en indiquant ce que vous avez changé par rapport à la version précédente, pour que je retrouve les discussions passées. (FOLLOW-UP)

== Communication
* [[MENTION]] Évitez de me mentionner (`@oliviercailloux`) dans vos PR sur GitHub SVP : cela a pour effet de me noyer de notifications (que GitHub ne permet pas de désactiver facilement), or, je ne peux pas m’investir dans des discussions du tac-au-tac pour chaque groupe d’étudiants que je suis. Re-demandez plutôt une review quand vous êtes prêts, après avoir répondu à autant de points que possibles : je regarderai toutes vos réponses en même temps.
* Maintenez les conversations focalisées. Ce n’est pas une bonne idée, par exemple, d’indiquer dans un commentaire de la PR #37 que vous avez décidé de changer la PR #22 pour telle et telle raison : quand j’évaluerai la PR #22 par la suite, il est peu probable que je me souvienne de vos explications se trouvant en PR #37.
* Si vous souhaitez discuter de mon évaluation, ou préciser qqch. au sujet d’une tâche passée, de même que ci-dessus : commentez dans la PR correspondante, et https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/about-pull-request-reviews#re-requesting-a-review[re-demandez-moi une review] pour que je sois averti de l’existence de nouveaux commentaires.
* N’hésitez pas à m’écrire si vous êtes bloqués, n’attendez pas d’avoir perdu plusieurs heures. Cependant, je vous demande de faire l’effort de poser des questions raisonnablement claires et complètes, et de m’indiquer ce que vous avez essayé et votre analyse de la situation. Voyez ces https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/[directives] pour vous inspirer. Si votre question peut intéresser les autres membres du groupe ou qu’il est utile de conserver la discussion pour référence future, créez une issue sur votre projet GitHub où vous décrivez votre problème et demandez-moi (par e-mail par exemple) d’y répondre en me donnant le lien. (ISSUE)
* Envoyez-moi un e-mail sans délai si vous n’avez pas de nouvelles de moi après 48h alors que vous attendez une réaction de ma part. Il est possible qu’une notification de GitHub m’ait échappé.
* Pour ce qui concerne la communication entre nous (PRs, README, e-mails), vous pouvez communiquer en français. Utilisez exclusivement l’anglais pour la documentation et le code de votre projet, de façon à ce qu’il soit accessible à une audience internationale.

Lorsque j’utilise des abréviations (termes en majuscules), elles font référence aux documents donnant les consignes pour le projet, tels que celui-ci, ou aux « bonnes pratiques » quand l’abréviation commence par BP (voir document correspondant dans le chapitre correspondant du cours, par exemple https://github.com/oliviercailloux/java-course/blob/master/Git/Best%20practices.adoc[BP Git]).

J’indique (OPT) lorsque mon commentaire a pour but principal de vous indiquer comment vous auriez pu faire mieux. (Il s’agit généralement d’une erreur mineure ou d’une amélioration possible, parfois subjective, de la clarté du code.) Vous êtes invités à modifier si cela ne vous retarde pas outre-mesure, ou vous pouvez l’indiquer comme partie d’une nouvelle tâche, ou simplement laisser tomber si vous trouvez que c’est un détail peu intéressant.

Ces instructions de remise précises me permettent de faciliter mon suivi. 
La correction détaillée de chaque rendu de chaque binôme est, je pense, d’un intérêt significatif pour l’apprentissage, mais est extrêmement chronophage et n’est raisonnable qu’à condition que les étudiants jouent le jeu en essayant sincèrement de suivre les instructions de remise.
Certaines de ces instructions peuvent paraitre relever du détail. Au contraire, leur respect est souvent nécessaire pour que mes outils partiellement automatisés fonctionnent.
C’est pourquoi je me permets d’insister pour que vous relisiez attentivement les instructions ici présentes lorsque la réponse à certaines de vos questions me semblent y figurer.

// Même si le manquement semble parfois relever du détail sans importance aux étudiants, j’insiste sur la lecture des instructions car elle permet une probable meilleure communication pour le reste de l’année, et pour traiter les étudiants égalitairement. Dans ce cas, je vous répondrai comme suit. _Je me permets de vous renvoyer à la lecture des instructions de remise et de communication, et en particulier le paragraphe (COMPLIANCE). Dites-moi SVP si qqch. n’est pas clair. Merci pour votre compréhension._ (Compliance)

Vous pouvez bien sûr remettre en question certaines de ces consignes si elles vous semblent non pertinentes : la contestation est très différente de l’ignorance. Mais dans ce cas, je vous demande de me montrer que vous les avez lues en y faisant référence explicitement dans votre discussion avec moi et en m’expliquant pourquoi vous pensez qu’elles ne s’appliquent pas.

== Évaluation
* À la date de clôture de la livraison, j’évaluerai vos tâches effectuées durant toute l’itération. Je retarderai la date de livraison à la demande de l’équipe, mais cela induira une pénalité de retard sur tout le projet (cf. ci-dessus). 
* Chaque binôme reçoit une note par livraison (agrégeant mon évaluation de l’ensemble de ses tâches durant cette itération). Les SM/PO reçoivent une note dépendant de la conduite de l’itération et du respect général des instructions de livraison. (Si une instruction n’est pas respectée par un binome mais que les SM/PO ont indiqué à temps un commentaire dans la PR demandant au binôme de corriger ce point, j’estimerai que les SM/PO ont fait leur travail correctement.)
* Plus j’ai insisté sur des erreurs à éviter, plus la notation sera sévère si ces erreurs sont commises.
* Il faut impérativement respecter les pré-requis. Si par exemple, suite à un problème d’organisation dans le groupe, vous livrez une tâche qui n’apporte encore rien parce qu’elle dépend d’un pré-requis qui n’a pas été livré, vous serez nécessairement en échec, même si le retard sur le pré-requis n’est pas de votre faute. Exemple : développement d’un GUI alors que les fonctionnalités manquent. Le code livré doit fonctionner et je dois avoir les éléments en main pour comprendre son intérêt. (Des exceptions légitimes existent, à discuter au cas par cas avec moi au moment de l’élaboration de votre plan.)
* L’évaluation tient compte particulièrement de la qualité du travail fourni (potentiel de réutilisabilité, facilité d’appropriation par d’autres développeurs, facilité de maintenance à long terme, clarté de la documentation), et en second lieu seulement de la quantité (bonus / malus si le travail accompli prendrait sensiblement plus / moins que le temps attendu pour cette itération si effectué par un étudiant attentif au cours et suivant les recommandations), et prend fortement en compte la difficulté de la tâche (technologies non vues au cours, …).
* Le poids d’une note dépend de l’ampleur des éléments sur lesquels mon évaluation peut s’appuyer.
* Note finale projet : moyenne pondérée de vos notes de livraison et de la présentation finale, avec un poids augmenté sur vos deux meilleures notes de livraison.

