= Commit
Sujet: commits, branches, et shell. Interdiction d’utiliser l’interface de GitHub pour vos commits. Votre `user.name` doit être égal à votre nom d’utilisateur sur GitHub (ID). Vous devrez entre autres indiquer votre n° d’étudiant dans un fichier. Documents du cours autorisés. Vous aurez 15 minutes (13h55 à 14h10). Chaque minute de retard vous coute 20% de votre note (décompte à la seconde).

Créez votre dépôt de remise https://classroom.github.com/a/wJaBYDn9[ici]. Créez un dépôt local (avec git init). Créez un commit initial contenant uniquement un fichier texte `afile.txt` contenant `coucou`. Connectez votre dépôt local au remote sur GitHub en suivant les instructions de GitHub. Créez une branche `coucou` pointant vers ce commit. Sur la branche `main`, créez un deuxième commit contenant, en plus du fichier `afile.txt` inchangé, un nouveau fichier `myid.txt` contenant uniquement votre numéro d’étudiant de Dauphine. Laissez la branche `main` sur ce commit, créez une nouvelle branche `dev` à cet endroit et basculez dessus. Créez dans cette branche un troisième commit, contenant en plus un fichier dont le chemin, relativement à un sous-répertoire `sub/` de votre répertoire de travail, serait `some sub sub folder/../a/another file.txt` (peu importe son contenu). Notez les espaces dans le nom. Vous devez donc créer les répertories intermédiaires nécessaires (inutile par contre de créer des répertoires vides). Utilisez la commande `git push origin main coucou dev` pour envoyer vos branches sur le dépôt distant.

//** [Énoncé an passé ! Cette année, inclusion : branches et Shell] Créez votre dépôt de remise https://classroom.github.com/a/hQKmTt6U[ici]. Créez dans un commit initial (COMMIT) un fichier texte `id.txt` (ID_FILE_EXISTS) contenant uniquement votre numéro d’étudiant de Dauphine (ID_FILE_CONTENTS). Faites en sorte que ce commit, et seulement ce commit (ONE_COMMIT), apparaisse dans votre dépôt de remise.

Stats : 26 remis ; 21 has commits ; 15 right identity ; 16 branche coucou ; 15 branche main ou master ; 7 fichier `another file.txt` ; 1 branche `dev` & chemin corrects.

