= Git branching 2
:xrefstyle: short

A modified version of a graded exercice that was given a few years ago.

In this graded exercice, we’ll simulate that we go back in time (to correct some problem in a previous version of a software), create two branches (to try two different approaches), and then merge those two branches.

* https://docs.github.com/en/get-started/quickstart/fork-a-repo[Fork] https://github.com/oliviercailloux/google-or-tools-java[this project] and clone your version locally.
* We’ll start with an existing commit that we will name `Start`. That is the commit representing the state of the application on `August 15, 2018, 15:00:00 +0200`, that is, the commit just before that time.
** For example, if there is a commit `C1` on that day at 14:30 and a commit `C2` just following it on that day at 15:20, then `Start = C1`.
* You must create four commits and three branches in total. The history should look like <<Goal>> when you are done. Make sure your pointers are exactly as pictured, and that the branches are named as in the figure.
** The three dots represent the rest of the history of that repository (you do not deal with this part).
** Commits `A`, `B`, `C`, `D` are your own commits.
** Commit `A` adds a file named `first.txt` containing “hello world”; its parent is `Start`.
** Commit `B` adds a file named `first.txt` containing “coucou monde”; its parent is `Start`.
** Commit `C` adds a file whose name, relative to the path `a/b/c/`, would be `x/y/../z/some file.txt` containing “hey”; its parent is `B`. Note the space in its name, and create any required intermediate folder.
** `D` is the result of merging `A` and `C` (after resolving the conflict). It keeps both the text “hello world” AND the text “coucou monde” (on the next line), thus, commit `D` contains a blob `first.txt` that contains two lines (in addition to the blob whose file name is `some file.txt` that has no change from `C`).

[[Goal]]
.Desired history at end of the exercice (italicized: your additions to the history)
image::https://raw.githubusercontent.com/oliviercailloux/java-course/main/Git/Git%20branching%202.svg[opts="inline"]

