= Git branching 4
:xrefstyle: short

In this graded exercice, we’ll create several branches and merge some of them.


* Accept the graded exercice: [branching bis]. This creates a repository for you.
* Your repository currently has one commit. I’ll refer to it as “Start” (you do not have to create it, it exists already).
* All the paths given here below are relative to the project root (where the file `pom.xml` lies).
* Create the branches so as to end up as illustated in the figure below (<<Goal>>). (You may have to create branches along the way, not necessarily now.)
* Commit `A` adds a file named `hello.txt` containing “Hello!”.
* Commit `B` adds a file named `another file.txt` containing “Second”.
* Commit `C` adds a file named `another file.txt` containing “Third”.
* Commit `D` adds a file whose relative path is `My folder/second file.txt` containing “Second”. You must thus create the required intermediate folder.
* Commit `C` adds a file named `first file.txt` containing “Coucou !”; its parent is `Start`.
* Commit `D` is the result of merging `B` and `C` (after resolving the conflict). It keeps both the text “Hello!” AND the text “Coucou !” (on the next line), thus, commit `D` contains a blob `first file.txt` that contains two lines (in addition to the other blobs coming from its parents).

To recap, you must create five commits and three branches in total. The history should look like <<Goal>> when you are done. Make sure your pointers are exactly as pictured, and that the branches are named as in the figure. (You may have more branches, and the only thing that matters with respect to branches is their final positions, not how they moved.)

[[Goal]]
.Desired history at end of the exercice
image::Git%20branching%204.svg[opts="inline"]

add a remote pointing to the original repository that can be found https://github.com/oliviercailloux/google-or-tools-java/[online].
fetch from this remote
find the right commit
push your branch to your repository
