= Git branching 5
:xrefstyle: short

In this graded exercice, we’ll create several commits and branches and merge some of them.

== Main instructions (indicative weight: 18/20)

* Accept the graded exercice: https://classroom.github.com/a/7vbbk09D[git branching]. This creates a repository for you.
** Your repository currently has one commit. I’ll refer to it as “Start”.
** All the paths given here below are relative to the project root (where the file `pom.xml` lies).
* Create commits and branches so as to end up as illustated in <<Goal>>, below. (You may have to create branches along the way, not necessarily now.)
* Commit `A` adds a file named `hello.txt` containing “Hello!”.
* Commit `B` adds a file named `afile.txt` containing “Second”.
* Commit `C` adds a file named `afile.txt` containing “Third”.
* Commit `D` adds a file whose relative path is `My folder/one more file.txt` containing “Something”. You must thus create the required intermediate folder.
* Commit `E` adds nothing more than what comes from its parents.
* Commit `F` keeps both the text “Second” AND the text “Third” (on the next line), thus, commit `F` contains a blob `afile.txt` that contains two lines (in addition to the other blobs coming from its parents).

To recap, at this stage, you must have created (at least) six commits and four branches in total. The history should look like <<Goal>> when you are done. Make sure your pointers are exactly as pictured, and that the branches are named as in the figure. (You may have more branches and commits, and the only thing that matters with respect to branches is their final positions, not how they moved.)

[[Goal]]
.Desired history at end of the exercice
image::Git%20branching%205.svg[opts="inline"]

== Supplementary instruction (indicative weight: 2/20)
This part proposes a challenge that goes beyond what has been covered in the exercices.
Our goal is to bring an old commit, coming from the original repository (that your repository originates from), back to your repository.

* Add a remote pointing to the original repository that can be found https://github.com/oliviercailloux/google-or-tools-java/[online]
* Fetch from this remote
* Add a branch `old` pointing to the commit whose SHA-1 contains `f88600` and push it to your repository
* This is _not_ illustrated in <<Goal>>

