= Git branching 3
:xrefstyle: short

In this graded exercice, we’ll simulate that we create several branches (to try different approaches) and merge some of them.

* Accept the graded exercice: https://classroom.github.com/a/BCWfgJNU[branching]
* Start with a first commit, that we will name `Start`, that contains a single file, `start.txt`, containing “A starting point”
* Create the branches so as to end up as illustated in the figure below (<<Goal>>). (You may have to create branches along the way, not necessarily now.)
* Commit `A` adds a file named `first.txt` containing “Hello world”; its parent is `Start`.
* Commit `B` adds a file whose relative path is `a/some file.txt` containing “Hey”; its parent is `A`. Note the space in its name, and create the required intermediate folder.
* Commit `C` adds a file named `first.txt` containing “Coucou monde”; its parent is `Start`.
* Commit `D` is the result of merging `B` and `C` (after resolving the conflict). It keeps both the text “Hello world” AND the text “Coucou monde” (on the next line), thus, commit `D` contains a blob `first.txt` that contains two lines (in addition to the blob whose file name is `some file.txt` that has no change from `C` and the one named `start.txt`).

To recap, you must create four commits and three branches in total. The history should look like <<Goal>> when you are done. Make sure your pointers are exactly as pictured, and that the branches are named as in the figure. (You may have more branches, and the only thing that matters with respect to branches is their final positions, not how they moved.)

[[Goal]]
.Desired history at end of the exercice
image::Git%20branching%203.svg[opts="inline"]

