= Git-Br-2018

Here are the instructions for this graded exercice.

(NB the link for the repository creation is not available any more. This is provided only for checking the wording of the exercice.)

* Create a repository for your exercice here. Your repository will be created as `+https://github.com/oliviercailloux-org/dep-git-yourGitHubUserName+`. (Sometimes GitHub seems stuck and does not tell you that it has been created, but it probably has been.) Your repository will be created with an existing project in it, your mission is to extend it and push your changes to that same repository.
* Clone it.
* Check out the commit `38da901544294bf2b5784e4de1456905a306a341`. We will call this the “starting” commit.
* Create and switch to a new branch, `my-branch`, departing from the starting commit.
* Change something in the `pom.xml` file. Commit into your branch (so that your commit has the starting commit as parent).
* Bring the changes of the commit that originally followed the starting commit into `my-branch` (by merging).
* Do not forget to send all your commits and your branch to the GitHub repository. Check that you see them online.

You will be graded as follows.

* One of the commits that you created must have the starting commit as parent, and be an ancestor of the final position of `my-branch`.
* One of the commits that you created must have two parents: a commit that you created; and one that you did not create; both parents having as parent the starting commit. The commit must be the final position of the branch `my-branch`, or be an ancestor of it.
* You must have changed the pom in your commit that has the starting commit as a parent.
* Commits created using the GitHub web site do not count.

