= Graded exercices

This document explains how to submit your solutions for the graded exercices of this course.

* Each graded exercice uses its own “GitHub assignment” (a mechanism proposed by GitHub classroom to dispatch exercices in a class).
* Each assignment has its own name and link. Start by clicking the link and accept the assignment
** This creates a GitHub repository that you own in my GitHub “organisation”, `oliviercailloux-org`
** Your repository will be created as `+https://github.com/oliviercailloux-org/assignmentName-yourGitHubUserName+`
** This repository will be initialized with some data
* Clone your new repository
** You have to work on your local repository, and regularly push your additions to the remote
** Both you and I have access to your remote repository. I use this access to grade your work
** I have of course no access to your local repository, so, whatever you do not push, I cannot grade
* Do whatever the assignment asks you to do (for example, add some code to some files, create new files, …) in your local repository
* Push your work to your remote
** Push regularly, do not wait the end of the allowed time, so as to prevent last minute problems
* Hint: Check with the GitHub web interface that your commits and branches have reached the remote repository

== The `training` assignment
* Here is https://classroom.github.com/a/uAsNcmqi[the link] for the “training” assignment. 
* You should be able to predict the name of the GitHub repository that will be created when you will accept this assignment.
* You can use this to practice as much as you want. 
* This repository will not be used to grade your work.
* In this assignment, you start with a file named `hello.txt` which contains `Hello, world.`

If you want to start fresh, https://docs.github.com/repositories/creating-and-managing-repositories/deleting-a-repository[delete] your “training” repository. (You should delete it before starting a new exercice, of course.)

== Exercice: hello world
Accept the https://classroom.github.com/a/uAsNcmqi[`training`] assignment and translate the content of the file `hello.txt` to say hello in another language of your choice. Make sure this is visible on your remote repository.

== Exercice: reinitialize the `training` assignment history
Read https://github.com/oliviercailloux/java-course/blob/master/Git/Reinitialization.adoc[Reinitialization].
Accept the https://classroom.github.com/a/uAsNcmqi[`training`] assignment and make it so that your resulting remote repository only contains, in its `main` branch, the history of the `master` branch of https://github.com/apache/cordova-plugin-compat[this project]. Second, push the `1.0.x` branch of the source project to your GitHub remote.

