= Git

Prerequisites:

* Install https://git-scm.com/download[git].
* We will start learning with the command line interface of git. If you are not used to using a shell, read the https://github.com/oliviercailloux/java-course/blob/master/Git/Shell.adoc[Shell] document.
Under Windows, use Git BASH (included in git https://gitforwindows.org/[for Windows]). (Power users may prefer to use https://www.develves.net/blogs/asd/articles/using-git-with-powershell-on-windows-10/[PowerShell].)
** This course uses Linux-like commands (in particular, uses forward slashes to separate paths), which you should be able to use in any of these environments: Git BASH emulates a Linux environment and PowerShell https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_path_syntax[authorizes] this use.

Then see:

* https://raw.githubusercontent.com/oliviercailloux/java-course/master/Git/Pr%C3%A9sentation/presentation.pdf[présentation] (or read below), 
* the git https://github.github.com/training-kit/[Cheat sheets],
* https://github.com/oliviercailloux/java-course/blob/master/Git/README.adoc#configure-git[configure] git,
* https://github.com/oliviercailloux/java-course/blob/master/Git/Step-by-step.adoc[step-by-step exercices], 
* https://github.com/oliviercailloux/java-course/blob/master/Git/Reinitialization.adoc[reinitializing] history,
* https://github.com/oliviercailloux/java-course/blob/master/Git/Git%20branching%201.adoc[Git branching 1] and https://github.com/oliviercailloux/java-course/blob/master/Git/Git%20branching%202.adoc[Git branching 2], 
* https://github.com/oliviercailloux/java-course/blob/master/Git/Best%20practices.adoc[best practices].

== Learning the basics
There are two ways to learn the basics of Git: the frustrating and long way, and the nice and short way. The frustrating and long way is the one you find yourself into if you do not read anything about git (because you do not have time) and just try to deal with it by running commands that you found on the web, that you do not fully understand, that you supposed would achieve just what you need, and that instead created a mess that you ignore how to repair.

To save time, read the https://git-scm.com/book[Pro Git] book. For the basics, you really only need to read the following sections.

* https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F[1.3] What is Git?
* https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup[1.6] Getting Started - First-Time Git Setup
* https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository[2.1] Getting a Git Repository
* https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository[2.2] Recording Changes to the Repository
* https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History[2.3] Viewing the Commit History
* https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes[2.5] Working with Remotes
* https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell[3.1] Git Branching - Branches in a Nutshell
* https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging[3.2] Git Branching - Basic Branching and Merging
* https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches[3.5] Git Branching - Remote Branches

Hint: do not try to remember all the shortcut commands and options git provides. You just need those ones: `git config --global …` (just for the initial configuration); `git clone <url>` or `git init` to start the fun; `git status`, `git diff`, `git add <files>`, `git commit` and `git merge` to enrich your local history; `git log` and `git checkout <commit>` to navigate in your history; `git branch <name>` to create branches; `git fetch` and `git push` to synchronize with your remote repository. You can learn the rest when and if you need it.

== Configure git
Git can be configured by associating string values to “options”. 
An option can be configured locally (for a given repository) or globally (for every time you use git on that system).

* Type `git config --global --list` to see which options are currently configured globally

Here we want to associate your name as a value to the option `user.name`. 
Git will use this to sign your commits.

* Type `git config --global --get user.name` to see the value currently associated to the option `user.name`
* Type `git config --global --add user.name MyUserName` to associate the value `MyUserName` to the option `user.name`
* Check again the value currently associated to the option `user.name`

For more info: https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup[initial setup]; GitHub usage of https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git#about-git-usernames[`user.name`] and https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/setting-your-commit-email-address[`user.email`]

== References
* https://git-scm.com/[Git-SCM]: Videos; Cheat Sheets; Book https://git-scm.com/book[Pro Git] (free, as in speech and beer); tryGit
* https://try.github.io/[Resources to learn Git]
* A quick and useful https://guides.github.com/introduction/flow/[guide] about workflow on GitHub; a branching https://nvie.com/posts/a-successful-git-branching-model/[model]
* Git https://stevelosh.com/blog/2013/04/git-koans/[Koans]
* Learning merging: https://longair.net/blog/2009/04/16/git-fetch-and-merge/[Prefer] fetch then merge to pull; http://think-like-a-git.net/sections/testing-out-merges/the-scout-pattern.html[the scout pattern]
* https://learngitbranching.js.org/[Learn Git Branching]
* https://rowanj.github.io/gitx/[GitX]; I’ve been recommended https://www.gitkraken.com/[GitKraken] (but it is https://www.gitkraken.com/pricing#git-gui-features[only free for public repos])

