= Shell

== Introduction
A shell (also called a terminal or a command line interface) permits to invoke programs by typing commands. Under Linux, use BASH (Bourne-again Shell) (or another compatible shell). Under Windows, use https://docs.microsoft.com/powershell/scripting/install/installing-windows-powershell[PowerShell], or, if you intend to use a shell to run git commands, use Git BASH, which emulates a Linux shell. (Different shells admit slightly different syntax and provide slightly different capabilities, and commands sometimes differ, but the commands we will need for this course are the same in most classical shells, except when indicated.)

See https://tutorial.djangogirls.org/en/intro_to_command_line/[Introduction to command line] for the very basics of using a shell. Use ↑ (keyboard up https://en.wikipedia.org/wiki/Arrow_keys[arrow]) to reuse previous commands.

[[Arguments]]
== About arguments
A shell command contains (typically) a program name, followed by arguments, separated by spaces. Example: `touch afile anotherfile` calls the program `touch` with two arguments. (This command creates two empty files, `afile` and `anotherfile`, if they do not exist already.) To form a single argument containing spaces, use quotes. Example: `touch "a file" "another file"` contains two arguments: `a file` and `another file`. Thus, this command creates two files, named `a file` and `another file`, with spaces in their names. The command `touch a file another file` (without quotes) would instead create four files. 

Exercice: open a shell, navigate (using `cd`) to some different place of your choice on your hard disk, create a file `my file.txt` there, delete it with your graphical file explorer, check in the terminal that it has disappeared (using `ls`).

Here are other examples for better understanding what an argument is: the command `ls -a` has one argument, `-a`. It is equivalent to `ls "-a"`. The command `ls --color=always "a file"` has two arguments. The https://git-scm.com/docs/git-config[command] `git config --type bool --get core.filemode` has five arguments (considering `git` as the command and `config` as its first argument).

[[Paths]]
== Relative and absolute paths
It is often necessary to refer to files or directories as arguments to commands in the terminal. You do this usually by using absolute or relative file or directory paths.

A file or a directory stored on your hard disk has an absolute “path” (or, less technically, “name”) that refers to it unambiguously. For example, under Linux (or MacOS): `/home/myuser/myprojectdirectory/README.txt`; and under Windows: `C:\Documents\myprojectdirectory\README.txt`. (Windows uses backslashes instead of slashes to separate path names and a slightly different naming scheme.) Examples in this course follow the Linux-like naming.

A file or a directory can also be referred to using a path that is _relative_ to another directory. For example, relative to the directory `/home/myuser/`, a relative path for the file in the above example is `myprojectdirectory/README.txt`. A path relative to `/home` is `myuser/myprojectdirectory/README.txt`. A path relative to `/home/myuser/myprojectdirectory` is simply `README.txt`. Relative paths can also use `..` segments to “climb up” one level in the hierarchy. That is, relative to `/home/myuser/anotherdirectory`, a path of the example file is `../myprojectdirectory/README.txt`. The mechanism for referring to directories using relative paths is similar. For example, a relative path to refer to the directory `/home/myuser/myprojectdirectory`, relative to `/home/`, is `myuser/myprojectdirectory`. A relative path never starts with a `/`, an absolute path always does (this is also true under Windows, if replacing `/` with `\` and neglecting the drive letter).

Referring to some file or directory as an argument of a command typed in a terminal can usually be done using its absolute path or its path relative to your current directory. For example, if you are in the directory `/home/myuser/`, you can use `myprojectdirectory/README.txt` to refer to the example file.

You can use the special name `.` to refer to the current directory. For example, you can use `ls somepath` to list the content of the directory specified by `somepath`, and thus typing `ls .` lists the content of your current directory.

Exercice: open a shell, navigate (using `cd`) to some directory of your choice `D1`. Use `ls` to list the content of a directory `D2` that is not a subdirectory of `D1`, using an absolute name for `D2`, then using a relative name. Still from `D1`, create a file in `D2`, using `touch`, by using an absolute file name as argument, then using a relative file name as argument.


