= Extractor

Here are the instructions to follow for the graded exercice “Extractor”.

//https://classroom.github.com/a/Ny5sBwFU
* Create a repository for your exercice here. This is where your project must be submitted. (For example, clone it and let your Maven project to be created at the next step become the root of this folder.)
* Create a Maven project. Use `groupId` `io.github.oliviercailloux` (or your own group id) and `artifactId` `extractor-` followed by your GitHub username.
* This project will build a simple class that is able to extract plain text from a PDF. For this, we will use Apache https://pdfbox.apache.org/[PDFBox]. Add the required dependency to your POM.
* There is a file already in your repository. It defines an interface `SimpleExtractor`. Move this file in the right folder, corresponding to its declared package (do not change its package).
* Now your project should compile (and do nothing). Commit your code so far.
* Implement the interface in a class `MySimpleExtractor`. Its package should be your group id, followed by your artifact id, with hyphens replaced by underscores (following the Maven https://github.com/oliviercailloux/java-course/blob/main/Best%20practices/Maven.adoc[Best practices])
** The method `getAllText` should return a Guava `ImmutableList`. (You will get two third of the mark for the method if you return a normal list.)
** Tips: to use PDFBox to extract text from a PDF, you only need to deal with two PDFBox classes: `PDDocument` and `PDFTextStripper`. Keep it simple: only a few lines of code are necessary to implement each method in `SimpleExtractor`. Remember you can use a `StringWriter` to write in memory.
** You can use http://www.xmlpdf.com/manualfiles/hello-world.pdf[this] PDF if you want to test your code. The extracted test should be `hello world\n`.

_Important_: Make sure your code compiles (according to `mvn compile`). Otherwise, almost no points will be granted. If you don’t know how to implement some method, at least write a minimal code that satisfies your compiler.

Supplementary information that you do not have to read: here are various aspects that will be graded (the list is not exhaustive).

* You committed before half-time (in supplement to your last commit) using `git`
* Your POM is at the root of your git repository
* POM satisfies the best practices
* Dependencies in the POM (to PDFBox and Guava) are well configured
* Your methods fail if an exception is thrown at any point during execution of the code
* `groupId`, `artifactId`, package are chosen according to instructions and best practices
* All `Closable` objects you create are correctly closed
* Implementation of `SimpleExtractor` satisfies its contract
* Your code in your last commit counts, not the code committed earlier

Time allowed: 40 minutes.

* Late: −0.05/20 per second. (Timestamp given by GitHub server.)

