= Configure Application Servers in Eclipse
:toc: preamble
:sectanchors:

This document briefly explains how to configure Java EE Application Servers from Eclipse. We illustrate with WildFly 14.

== Runtime environment

* First, you need a Runtime Environment (RE). This contains the various libraries that implement (part of) the Java EE specifications.
* You must have already installed the `JBoss AS Wildfly, EAP & Server Tools` plugin for Eclipse (see https://github.com/oliviercailloux/java-course/blob/master/Tools.adoc[Tools]). If you want another server, you probably need another plugin.
* Within Eclipse: `Preferences / Server / Runtime Environments`. Add your local WildFly installation there. Name it `My WildFly 14.0 Runtime`. (You should not mix up Runtime Environments and servers!)

Now you may add this RE to any of your existing Eclipse Java EE projects. This will add the corresponding libraries in the classpath.

* Go to the project properties and `Targeted Runtime`, select `My WildFly 14.0 Runtime`.

You should now be able to deploy your project to your application server manually.
From Eclipse, export your project as an archive. Note that Eclipse is clever enough not to include the Runtime Environments libraries in your archive. (You can see that by uncompressing the produced archive.) Put the archive inside the relevant directory in your application server. Check that your application is reachable.

== Servers
In order to deploy your application from within Eclipse, Eclipse must “see” your server.

* Show the Servers view in Eclipse. It lists the servers known to Eclipse.
* Use the context menus: `New` (name your server `My WildFly 14 server`, set it as controlled by Management Operations), then use `Add and Remove`, `Publish`, and other options as needed.
* (https://stackoverflow.com/questions/20213032/eclipse-kepler-and-jboss-wildfly-hot-deployment[This] advice might be useful.)
