= Automated Eclipse install

Here is how I automate my Eclipse installation.

* Uncompress `eclipse-jee-2019-12-R-linux-gtk-x86_64.tar.gz`
* `sudo mv eclipse-jee-2019-12-R-linux-gtk-x86_64/eclipse/ /usr/local/share/eclipse-jee-2019-12-R-linux-gtk-x86_64`
* Install any desired shared plugins (optional, see below)
* `sudo chown -R root:staff /usr/local/share/eclipse-jee-2019-12-R-linux-gtk-x86_64/`
* Delete your `.eclipse` folder and your previous Eclipse workspace to forget possible unwanted residuals from previous installations

////
== Automatic workspace selection
Tried the following; fails at start, Eclipse seems confused.
mkdir -p ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/.settings" ; printf "RECENT_WORKSPACES=/home/olivier/Local/eclipse-workspace\nSHOW_WORKSPACE_SELECTION_DIALOG=false" > ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/.settings/org.eclipse.ui.ide.prefs"
mkdir -p ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/.settings" ; echo "SHOW_WORKSPACE_SELECTION_DIALOG=false" > ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/.settings/org.eclipse.ui.ide.prefs"

// tried to “install” again the Checkstyle plug-in for the local user. This creates ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/", but not …/.settings.
////

== Shared plugins
This uses the https://help.eclipse.org/2019-12/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/misc/multi_user_installs.html[shared configuration] approach.

To install https://checkstyle.org/eclipse-cs/[Eclipse Checkstyle Plug-in] and “Checkstyle configuration plugin for M2Eclipse” (part of https://marketplace.eclipse.org/content/m2e-code-quality[`m2e-code-quality`]): `"/usr/local/share/eclipse-jee-2019-12-R-linux-gtk-x86_64/eclipse" -nosplash -application "org.eclipse.equinox.p2.director" -repository "http://checkstyle.org/eclipse-cs/update/, http://m2e-code-quality.github.io/m2e-code-quality/site/latest/" -installIU "net.sf.eclipsecs.feature.group, com.basistech.m2e.code.quality.checkstyle.feature.feature.group"`. (The installation process seems to hang for about one minute.) This installs 2 features in `/usr/local/share/eclipse-jee-2019-12-R-linux-gtk-x86_64/features` and 7 plugins in the `plugins` subfolder, so that they are available for all users in the system. 

To install https://www.eclipse.org/papyrus/[Papyrus]: `"/usr/local/share/eclipse-jee-2019-12-R-linux-gtk-x86_64/eclipse" -nosplash -application "org.eclipse.equinox.p2.director" -repository "http://download.eclipse.org/modeling/mdt/papyrus/components/designer/, http://download.eclipse.org/releases/2019-12, http://download.eclipse.org/modeling/mdt/papyrus/components/marte/" -installIU "org.eclipse.papyrus.designer.languages.java.feature.feature.group"`. (This installs `org.eclipse.papyrus.designer.languages.java.feature.feature.group`, which gives the Java profile (not sure it is really useful, though), and `org.eclipse.papyrus.designer.languages.common.feature.feature.group`, required for most Papyrus features. Perhaps `org.eclipse.papyrus.designer.transformation.main.feature.feature.group` is useful, I don’t know, but this requires C++ and Java profiles (and code generation) and MARTE static profile. Oddly enough, `org.eclipse.papyrus.sdk.feature.feature.group` is provided in http://download.eclipse.org/releases/2019-12 and not in Papyrus Designer, Marte or Moka update sites. The Papyrus https://www.omg.org/omgmarte/[Marte] update site is required because “Papyrus base elements for code generation (Incubation)” (`org.eclipse.papyrus.designer.languages.common.feature.feature.group`) depends on “Papyrus common code generation UI” (`org.eclipse.papyrus.designer.languages.common.codegen.ui`), depending on “Papyrus designer: transformation core (Incubation)” (`org.eclipse.papyrus.designer.deployment.tools`), depending on “osgi.bundle; org.eclipse.papyrus.marte.static.profile 1.2.2”.)

// Create a new project with Java profile: Java profile does not appear in the project. Import afterwards works (both before and after installing the transformation.main).

https://stackoverflow.com/a/38956772[This] lets you find the data for other plugins.

== Others
In Gnome, consider https://bugs.eclipse.org/bugs/show_bug.cgi?id=473562[disabling] the Alt+F5 shortcut so that the Eclipse one works.

