= Automated Eclipse install

Here is how I automate my Eclipse installation.

* Uncompress `eclipse-java-2019-06-R-linux-gtk-x86_64.tar.gz`
* `sudo mv eclipse-java-2019-06-R-linux-gtk-x86_64/eclipse/ /usr/local/share/eclipse-java-2019-06-R-linux-gtk-x86_64`
* Install any desired shared plugins (optional, see below)
* `sudo chown -R root:staff /usr/local/share/eclipse-java-2019-06-R-linux-gtk-x86_64/`

To install https://checkstyle.org/eclipse-cs/[Eclipse Checkstyle Plug-in] and “Checkstyle configuration plugin for M2Eclipse” (part of https://marketplace.eclipse.org/content/m2e-code-quality[`m2e-code-quality`]): `"/usr/local/share/eclipse-java-2019-06-R-linux-gtk-x86_64/eclipse" -nosplash -application "org.eclipse.equinox.p2.director" -repository "http://checkstyle.org/eclipse-cs/update/, http://m2e-code-quality.github.io/m2e-code-quality/site/latest/" -installIU "net.sf.eclipsecs.feature.group, com.basistech.m2e.code.quality.checkstyle.feature.feature.group"`. This installs 2 features in `/usr/local/share/eclipse-java-2019-06-R-linux-gtk-x86_64/features` and 7 plugins in the `plugins` subfolder, so that they are available for all users in the system. This uses the https://help.eclipse.org/2019-06/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/misc/multi_user_installs.html[shared configuration] approach.

To know how to find the data for other plugins, look https://stackoverflow.com/a/38956772[here].

//TODO consider installing auto Papyrus. Works when installing manually from the normal Eclipse release update site just after the rest of the installation as described above.

