= awesome-test

Just a file with links to test awesome_bot.

link https://central.sonatype.org/pages/ossrh-guide.html#create-a-ticket-with-sonatype[create a ticket] with Sonatype. 

link https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Maven.adoc#naming-conventions[right]. 

link (see https://central.sonatype.org/pages/requirements.html#s0ufficient-metadata[metadata requirements]). 

link (“we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.”, https://central.sonatype.org/pages/requirements.html#s1ufficient-metadata[requirements])

link http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference[lifecycle]. 

link https://search.maven.org/[search] interface within https://central.sonatype.org/pages/ossrh-guide.html#releasing-to-central[two hours]). 

link (“we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.”, https://central.sonatype.org/pages/requirements.html#s2ufficient-metadata[requirements]

link ( https://central.sonatype.org/pages/requirements.html#s3ufficient-metadata[requirements])

link https://central.sonatype.org/pages/requirements.html#s4ufficient-metadata[requirements])

link (“we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.”, https://central.sonatype.org/pages/requirements.html#s5ufficient-metadata[requirements]).

link (“we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.”, https://central.sonatype.org/pages/requirements.html#s6ufficient-metadata[requirements])

https://www.wikipedia.org/#two[two words]

https://www.wikipedia.org/#word[word]

https://www.wikipedia.org/#dot[dot].

https://www.wikipedia.org/#dotpar[stuff]).

https://www.wikipedia.org/#par[stuff])

a sentence https://www.wikipedia.org/#sent[stuff]).

a sentence, https://www.wikipedia.org/#comma[comma].

a sentence, https://www.wikipedia.org/#commapar[commapar])

link (“we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.”, https://www.wikipedia.org/#longsentpardot[stuff]).

link (“we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.”, https://www.wikipedia.org/#longsentdot[stuff])

