= Continuous Integration

Continuous Integration (CI) refers to the process of frequently integrating changes created by various developers in your team, in order to have (almost) permanently underhand a current, integrated version of your software containing all the developments so far.

CI makes especially sense when you are able to control automatically that your software still runs successfully after the merge. This you normally do by having a sufficient coverage of (unit or functional or integration) tests.

This doc indicates how to set up CI with Travis-CI, for a Java project using Maven and hosted on GitHub.

== Motivation

When developing in a team, it is frequent that a sub-team will branch the project and work on a feature on its own for a while. This may break other features of the software, or introduce changes incompatible with the parallel changes made by some other sub-team. If the branch is being developed for a long time apart from other developments in the project, it will become increasingly difficult to merge the changes. At some point, it may even be considered easier to start developing the feature again from scratch than to merge. Frequent merges reduce this risk.

Another motivation of CI is to always have a version of your software ready for demonstration.

A third motivation is that CI usually goes together with remote building: you set up a remote platform dedicated to building your project and running the tests. That ensures that your software builds and executes successfully in a clean environment (knowing that it builds and runs in the computers of the developers might be an insufficient guarantee, as those computers might have specific softwares and customization).

== Overview

The most important point to embrace CI is to decide to do it! All the team members have to commit their changes frequently to a common source control repository and to merge frequently (usually in a development branch). 

Once you have taken this decision, some tools may help.
CI tools can be used to automatically run a build (and trigger your tests) when you commit to your source control repository, and warn you when builds or tests fail.

== Set-up

. Register and log-in to https://travis-ci.org/[Travis-CI].
. Tell Travis-CI which of your GitHub repository you want Travis to take care of.
. Add a file `.travis.yml` to your repository, with the contents indicated here below, and push it to GitHub.
. Refresh your page on the Travis-CI web site, and watch your project being built.
. (Optional, but cool.) Add the relevant https://docs.travis-ci.com/user/status-images/[badge] to your `README.adoc` in your project repository.

.Sample `.travis.yml` configuration file
[source,yaml]
----
language: java
git:
  depth: 1
jdk:
  - oraclejdk8
dist: trusty
----

Travis will start a new build each time you send a commit to your GitHub repository.

The configuration file is written in http://yaml.org/[YAML], a human friendly format. I recommend https://docs.travis-ci.com/user/travis-lint[validating] your configuration file whenever you change it.

The sample configuration file suggested here tells Travis to:

* fetch only the tip of your git history (`git https://git-scm.com/docs/git-clone#git-clone---depthltdepthgt[depth] 1`);
* use JDK 8 (default is 7);
* run the build in a container-based https://docs.travis-ci.com/user/ci-environment/[environment] using the (Ubuntu 14) https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_14.04_LTS_.28Trusty_Tahr.29[Trusty] distribution (the default being (Ubuntu 12) https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_12.04_LTS_.28Precise_Pangolin.29[Pangolin]).

Travis allows you to configure automatic deployment, run scripts of your own, and https://docs.travis-ci.com/[much more].

