= Flows

About manipulation of flows (including byte streams, character flows, files) in Java.

NOTE: The reader should understand https://github.com/oliviercailloux/java-course/blob/master/Shell.adoc#Paths[Relative and absolute paths]. The reader should know the https://docs.oracle.com/javase/tutorial/java/javaOO/arguments.html[Varargs] construct. (The last exercice uses https://github.com/oliviercailloux/java-course/blob/master/Maven/README.adoc[Maven].)

== Overview
There are four essential kinds of objects that represent flows of information in Java.

* https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html[InputStream]: to read flows of bytes.
* https://docs.oracle.com/javase/8/docs/api/java/io/OutputStream.html[OutputStream]: to write flows of bytes.
* https://docs.oracle.com/javase/8/docs/api/java/io/Reader.html[Reader]: to read flows of characters.
* https://docs.oracle.com/javase/8/docs/api/java/io/Writer.html[Writer]: to write flows of characters.

It is typical for a flow of character to be encoded as a flow of bytes. For example, to store the string `Hello, world` in a text file on your hard disk, using the https://en.wikipedia.org/wiki/UTF-8[UTF-8] encoding standard, the string would be first https://en.wikipedia.org/wiki/UTF-8#Codepage_layout[encoded] as the bytes _48_, _65_, _6C_, _6C_, _6E_, _2C_, _20_, _77_, _6F_, _72_, _6C_, _64_ in hexadecimal (or equivalently in decimal, _72_, _101_, _108_, _108_, _110_, _44_, _32_, _119_, _111_, _114_, _108_, _100_), then written (as a bit stream) on the disk. In Java, a mapping between characters and bytes is called a _character set_. You should always opt for the https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/charset/StandardCharsets.html#UTF_8[`UTF-8`] character set when you have a choice, as it is the standard general purpose character set.

The most common way of obtaining a flow is to read from a file. To designate the file, you typically use a path relative to your project directory (the place where `pom.xml` is stored, when you use Maven). 

Two essential classes help you deal with files: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Path.html[`Path`] and https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Files.html[`Files`]. For example, use `Files#newBufferedWriter()` to obtain a `Writer` that writes to a file.

Classes that represent flows (such as the four above) implement `Closeable`. This signals that they must be _closed_ after use. (This serves to release resources that might have been reserved by the operating system, or to proceed with finalizing operations, such as effectively writing to disk by flushing the cache.) Do not forget to close your flows after use by calling `close()`. Use the https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html[try-with-resources] statement for this, as it is a simple way of making sure `close()` is duly called.

NOTE: Many examples on the internet still use the `File` class. This approach should now be considered https://docs.oracle.com/javase/tutorial/essential/io/legacy.html[deprecated]. Using `Path` and `Files`, as illustrated here, should be favored: among other advantages, it readily adapts to other kinds of file systems such as https://github.com/google/jimfs[in-memory file systems], as explained below.

== Exercice: read using a byte flow
* Create a file `in.txt` in your project directory, containing `Hello, world`. 
* In Java, create a `Path` object designating that file.
* Use the appropriate static method from the `Files` class to obtain an `InputStream` representing the content of that file.
* Read and print the bytes from that stream using a loop, one by one.
* Check that the bytes are as expected.

Here is a https://github.com/oliviercailloux/sample-flows/tree/master/src/main/java/io/github/oliviercailloux/sample_flows[solution]. Don’t cheat! Try it for yourself before looking.

* Move the file around in your hard disk (for example, put in into the `src/main` sub-directory, or put in into a directory higher up the hierarchy, one that is not included in your project). Adapt the code.

In this example, the specific encoding used for encoding characters to bytes does not matter much, because all encodings used in practice encode the basic latin alphabet in the same way. Problems can arise when using “more exotic” characters. For example, the character `é` is encoded as the bytes https://www.fileformat.info/info/unicode/char/00e9/index.htm[_C3_, _A9_] under `UTF-8`, but as https://en.wikipedia.org/wiki/%C3%89#Character_mappings[_E9_] under `ISO-8859-1`.

== Exercice
Create a text file containing `Hé !` using your favorite text editor, and print its byte content using a stream, as previously. From this, determine if your editor possibly used the `UTF-8` encoding.

== Reading from character flows
Character flows should be used preferably to byte flows when reading or writing text data (as in the exercice above). Such a flow usually reads from (or writes to) a byte flow, decoding from or encoding to bytes as demanded. Note that this conversion will depend on the character set specified to the object representing the character flow.

== Exercice
Adapt the strategy used in the first exercice in order to use a `Reader` to print the content of your file containing `Hé !`. Use various character sets. Check that it prints `Hé !` or prints something else, depending on the character set your editor uses to encode the characters, and the character set your `Reader` object uses to decode the bytes.

== A more realistic exercice
* Create (manually) a text file containing multiple persons. Each person is described by two lines: her first name then her last name. Thus the file contains _n_ times 2 lines for describing _n_ persons. Create a class `Person` with a first name and a last name. Create a method `readPersons` that accepts a `Reader` as parameter, uses it to read such a file, and returns a list of persons.

We now want to test this method. We could create a file, let the method read from that file, and then delete the file, but we prefer to avoid creating a file unnecessarily. This is possible thanks to the abstraction represented by `Reader`: remember that such an object represents a flow of characters, and this may come from a file, from memory, from the network, …

* Create a unit test that creates a `String` equal to `firstname\nlastname`. The test gives the string to your `readPersons` method created in the previous exercice. To do this, use a https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/io/StringReader.html[`StringReader`]. The test asserts that the created person has the right first and last names.

== Path operations
A `Path` represents a path in a tree, and that tree represents a “file” system. Read https://docs.oracle.com/javase/tutorial/essential/io/path.html[here] about this important concept.

From a given `Path` instance (representing, thus, a path in a file system), you can obtain other `Path` instances, representing relative or absolute paths that relate to that first path. See https://docs.oracle.com/javase/tutorial/essential/io/pathOps.html[here] for the essentials about this. 

== File system providers
Each `Path` instance is bound to a `FileSystemProvider`. The _default_ file system provider permits to access the “normal” file system, thus, the files and folders sitting on the hard disk where your code runs. When building a path from `String` instances, using the `https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/Path.html#of(java.lang.String,java.lang.String...)[Path.of(String, String…)]` method, the returned instance is bound to that (default) file system provider. For example, `Path.of("/home/user/stuff.txt")` represents the file `stuff.txt` sitting in the folder `/home/user`. 

The `Path` mechanism in Java is actually more general than this, as it can represent a path in a file system that is not the “normal” file system. Such `Path` instances are bound to other (non default) `FileSystemProvider` instances. For example, an in-memory file system, or a file system that can access the content of a zip (or a jar) file.

== Constructing paths from other paths
There are two important ways of obtaining a `Path` instance. One is to build it from `String` instances, as illustrated here above. Another is to obtain a path _from another path_. The crucial difference is that when you obtain your instance from another path, _your instance is bound to the same provider as the other path provider_. Thus, if you receive a `Path` instance that is bound to an in-memory file system, and obtain, say, a child of that path (by calling `resolve(String)` on that path), you obtain another `Path` instance bound to this same in-memory file system. This is very handy: in this way, you can create general code that deals with any file system given by your user, even if you know nothing about the specifics of those other file systems.

== Exercice
In this exercice we will create a unique general code that writes two files, `hello.txt` and `subfolder/bye.txt`, and will use it to write at different places in our default file system and to a zip file.

* Define a method `helloBye(Path)` that accepts a `Path` (considered to represent a folder). Define another path instance from that path, representing the file `hello.txt` sitting in the folder represented by that path (thus, for example, if given a path representing `/home/user/afolder/`, your new path instance should represent `/home/user/afolder/hello.txt`). Write the string `Hello, world` in that file. Check that it works.
* Extend your method so that it creates a path representing the folder `subfolder` as a child folder of the path received as argument, create that folder, and in that folder, create a file `bye.txt` containing `Bye bye!`. Check that this works.
* Create somewhere (manually, with your file browser) some folders `test1/` and `test2/asubfolder/`. Define a `main` method that calls `helloBye()` twice, giving it paths representing `test1/` and then `test2/asubfolder/`. Check that your code has created the four expected files.
* Create a new `zip` file and obtain the `FileSystem` instance that represents it, thanks to this https://docs.oracle.com/javase/7/docs/technotes/guides/io/fsp/zipfilesystemprovider.html[sample code]. Obtain the root path of this file system with `https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/nio/file/FileSystem.html#getPath(java.lang.String,java.lang.String...)[getPath("")]`. Pass this path to `helloBye()`. Check (manually) that you have successfully created a zip file containing the expected files.

== References
See Oracle’s https://docs.oracle.com/javase/tutorial/essential/io/index.html[Basic I/O] tutorial.

