= An overview of the Glassfish Java EE application server
:toc: preamble
:sectanchors:

This document gives a (rough and incomplete) overview of Glassfish, a Java EE application server. This document may serve as an introduction to application servers in Java EE.

== Application servers
Java EE defines a http://www.oracle.com/technetwork/java/javaee/tech/index.html[set] of specifications, known as Java Specification Requests (JSR). Application servers have to implement [small]#(parts of)# these standards in order to be compliant with [small]#(a subset of)# Java EE. An important standard among those is the Servlet API, or https://www.jcp.org/en/jsr/detail?id=369[JSR 369].

A Java EE application server is a piece of software that ease the development of web applications, by providing services to the Java web developer. Your application server provides containers in which you, the web developer, embed your code. The container calls your code whenever adequate. For example, we use the web container in the link:Servlets.adoc[Servlets] document.

Examples of Java EE compliant application servers: GlassFish (Oracle, open source, reference implementation of Java EE), WildFly (Red Hat / JBoss, open source), WebSphere AS (IBM)…

== Running Glassfish
* Download and install a local copy of Glassfish (see link:Tools.adoc[Tools]).
* Note in particular the important `…/glassfish/bin` and `…/glassfish/domains/domain1/autodeploy` directories.
* The server is commanded thanks to the `asadmin` command (in the `bin` subfolder). This command is to be run in a terminal.
* Start the server with `asadmin start-domain`: this starts domain1, the default configured domain.
* Stop the server by typing `asadmin` then `stop-domain`. (Equivalently: `asadmin stop-domain`.)

== Embedded database
Any compliant Java EE server comes with an embedded SQL database, that will be used by default if none other is configured.

* Start the database with `asadmin start-database`. Guess how to stop it?

== Manipulating the server
Supplementary to the somewhat austere `asadmin` command line utility, it is possible to configure many aspects of the server using its graphical administration console.

When the server starts, it tells you (on the terminal) its admin port (usually 4848); and the place it logs to (usually `…/glassfish/domains/domain1/logs/server.log`).

Browse to http://localhost:4848/ to open the Administration console. Open `Configurations / server-config / Network Config / Network Listeners / http-listener-1`. Check where the server is listening for normal operation (usually 8080).

Browse to http://localhost:8080/ and check that you see the “Your server is now running” page. Browse to your external IP address on the port 8080 (for example, http://192.168.0.1:8080) and check that you see the same thing. That’s because `http-listener-1` is listening to the address `0.0.0.0`, meaning every address.

For increased security, in the Administration Console, change the address field and indicate there `localhost`. Click `Save`. Check that your server is no more reachable (on port 8080) from your external IP address, but is still reachable from the localhost address.

Open the server log file in a text editor and check that you see the logs related to what you just did.

== Deploying applications
The autodeploy directory is used to deploy your application, once it is packaged appropriately (e.g. as a WAR file). Simply drop the file there. Glassfish will then create a file in the same folder to tell you whether the application was deployed successfully. (Check the link:Servlets.adoc[Servlets] document to learn how to create an adequate file.)

== Technical tips
=== Does Glassfish see my servlets?
When you can’t reach your servlet, check whether Glassfish sees it. (Tested under Glassfish 4.1.2.)

* Start your domain
* Run `asadmin`
* `list-applications` ⇒ check that your application appears, otherwise, it is most probably not deployed correctly
* `list-sub-components` <app-name> ⇒ check that your servlet appears.

If your application deploys but your servlet isn’t seen, you may have forgotten an annotation. Do check the server log, it probably contains useful information.

=== Clear log
Run `asadmin rotate-log` to clear the log.

