= HTML to DOM

A short note about parsing HTML documents in Java using W3C’s DOM (Document Object Model). Learning to parse using the DOM is good because the DOM is a widely implemented standard: once you know how it works, you can parse HTML (and XML) documents in Javascript, https://docs.python.org/3/library/xml.dom.html[Python], https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xml-document-object-model-dom[.NET], …

== Valid HTML

This should successfully parse any document that can be transformed to a DOM according to W3C standard, including valid HTML documents in HTML syntax or XHTML syntax. It uses the https://www.w3.org/TR/DOM-Level-3-Core/core.html#Bootstrap[bootstrapping] approach (described in the DOM Level 3 Core Specification) and the LS feature (described in the DOM Level 3 https://www.w3.org/TR/2004/REC-DOM-Level-3-LS-20040407/[Load and Save] specification).

.Obtain a DOM object from a valid HTML document
[source,java]
----
Document doc;
File inputFile = new File("input.html");
String inputUrl = inputFile.toURI().toURL().toExternalForm();

DOMImplementationRegistry registry = DOMImplementationRegistry.newInstance();
DOMImplementationLS impl = (DOMImplementationLS) registry.getDOMImplementation("LS");
LSParser builder = impl.createLSParser(DOMImplementationLS.MODE_SYNCHRONOUS, null);
doc = builder.parseURI(inputUrl);

Element docE = doc.getDocumentElement();
LOGGER.info("Main tag name: {}.", docE.getTagName());
----

== XHTML

This approach uses https://en.wikipedia.org/wiki/Simple_API_for_XML[SAX] rather than the standard bootstrapping approach. I recommend using the previous one instead where applicable. (It might also be specific to loading XML documents, though I have had successes loading an HTML document in HTML syntax with it.)

.Obtain a DOM object from a valid XHTML document
[source,java]
----
Document doc;
File inputFile = new File("input.html");
String inputUrl = inputFile.toURI().toURL().toExternalForm();

DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
DocumentBuilder builder = factory.newDocumentBuilder();
doc = builder.parse(inputUrl);

Element docE = doc.getDocumentElement();
LOGGER.info("Main tag name: {}.", docE.getTagName());
----

== Real-life HTML

HTML documents in the wild are seldom valid. You may use the https://jsoup.org/[jsoup] library for these cases.

.Obtain a DOM object from a real-life HTML document
[source,java]
----
Document doc;
File inputFile = new File("input.html");

org.jsoup.nodes.Document jsoupDoc = Jsoup.parse(inputFile, StandardCharsets.UTF_8.name());
doc = new W3CDom().fromJsoup(jsoupDoc);

Element docE = doc.getDocumentElement();
LOGGER.info("Main tag name: {}.", docE.getTagName());
----

== Writing XHTML
Here is how to programmatically write an XHTML document (with namespaces). Assuming a `private static final String XHTML_NAME_SPACE = "http://www.w3.org/1999/xhtml";` field.

.Write XHTML
[source,java]
----
DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
DocumentBuilder builder = factory.newDocumentBuilder();
Document document = builder.newDocument();

Element html = document.createElementNS(XHTML_NAME_SPACE, "html");
html.setAttribute("lang", "en");
document.appendChild(html);
Element head = document.createElementNS(XHTML_NAME_SPACE, "head");
html.appendChild(head);
Element meta = document.createElementNS(XHTML_NAME_SPACE, "meta");
meta.setAttribute("http-equiv", "Content-type");
meta.setAttribute("content", "text/html; charset=utf-8");
head.appendChild(meta);
Element body = document.createElementNS(XHTML_NAME_SPACE, "body");
html.appendChild(body);
/** And so on. */
----

== Document to String
And here is now to print your document to a string.

.Pretty print a Document into a String
[source,java]
----
DOMImplementationRegistry registry = DOMImplementationRegistry.newInstance();
DOMImplementationLS impl = (DOMImplementationLS) registry.getDOMImplementation("LS");
LSSerializer ser = impl.createLSSerializer();
ser.getDomConfig().setParameter("format-pretty-print", true);
/** Do not use ser.writeToString: it uses UTF-16. */
LSOutput output = impl.createLSOutput();
StringWriter writer = new StringWriter();
output.setCharacterStream(writer);
ser.write(document, output);
return writer.toString();
----

== Validate your XML
Validating the XML on the fly while writing it using an `LSSerializer` seems https://hg.openjdk.java.net/jdk/jdk11/file/tip/src/java.xml/share/classes/com/sun/org/apache/xml/internal/serializer/dom3/LSSerializerImpl.java#l140[unsupported]. An alternative approach is to use the Java Validation API, as illustrated below (https://stackoverflow.com/questions/15732/whats-the-best-way-to-validate-an-xml-file-against-an-xsd-file[thanks]).

.Validate a XHTML document
[source,java]
----
Schema schema = SchemaFactory.newDefaultInstance().newSchema(getClass().getResource("xhtml1-strict.xsd"));
DOMSource docAsSource = new DOMSource();
docAsSource.setNode(document);
schema.newValidator().validate(docAsSource);
----

== Refs

* Parsing from DOM and related technologies in Java: see https://docs.oracle.com/javase/tutorial/jaxp/TOC.html[JAXP] tutorial (focus on the parts related to the DOM)
* https://dom4j.github.io/[<dom4j>], a well-written library for simpler DOM manipulation
* https://en.wikipedia.org/wiki/Comparison_of_HTML_parsers[Comparison] of HTML parsers (Wikipedia)
* W3C https://www.w3.org/TR/2015/REC-dom-20151119/[DOM4] (Recommendation 19 November 2015), a snapshot of the DOM Living Standard
* https://github.com/elharo/xom/[xom], seems to be high-quality

