= HTML to DOM

A short note about parsing HTML documents in Java using W3C’s DOM (Document Object Model). Learning to parse using the DOM is good because the DOM is a widely implemented standard: once you know how it works, you can parse HTML (and XML) documents in Javascript, https://docs.python.org/3/library/xml.dom.html[Python], https://docs.microsoft.com/en-us/dotnet/standard/data/xml/xml-document-object-model-dom[.NET], …

== Valid HTML

This should successfully parse any document that can be transformed to a DOM according to W3C standard, including valid HTML documents in HTML syntax or XHTML syntax. It uses the https://www.w3.org/TR/DOM-Level-3-Core/core.html#Bootstrap[bootstrapping] approach (described in the DOM Level 3 Core Specification) and the LS feature (described in the DOM Level 3 https://www.w3.org/TR/2004/REC-DOM-Level-3-LS-20040407/[Load and Save] specification).

.Obtain a DOM object from a valid HTML document
[source,java]
----
Document doc;
File inputFile = new File("input.html");
String inputUrl = inputFile.toURI().toURL().toExternalForm();

DOMImplementationRegistry registry = DOMImplementationRegistry.newInstance();
DOMImplementationLS impl = (DOMImplementationLS) registry.getDOMImplementation("LS");
LSParser builder = impl.createLSParser(DOMImplementationLS.MODE_SYNCHRONOUS, null);
doc = builder.parseURI(inputUrl);

Element docE = doc.getDocumentElement();
LOGGER.info("Main tag name: {}.", docE.getTagName());
----

== XHTML

This approach uses https://en.wikipedia.org/wiki/Simple_API_for_XML[SAX] rather than the standard bootstrapping approach. I recommend using the previous one instead where applicable. (It might also be specific to loading XML documents, though I have had successes loading an HTML document in HTML syntax with it.)

.Obtain a DOM object from a valid XHTML document
[source,java]
----
Document doc;
File inputFile = new File("input.html");
String inputUrl = inputFile.toURI().toURL().toExternalForm();

DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
DocumentBuilder builder = factory.newDocumentBuilder();
doc = builder.parse(inputUrl);

Element docE = doc.getDocumentElement();
LOGGER.info("Main tag name: {}.", docE.getTagName());
----

== Real-life HTML

HTML documents in the wild are seldom valid. You may use the https://jsoup.org/[jsoup] library for these cases.

.Obtain a DOM object from a real-life HTML document
[source,java]
----
Document doc;
File inputFile = new File("input.html");

org.jsoup.nodes.Document jsoupDoc = Jsoup.parse(inputFile, StandardCharsets.UTF_8.name());
doc = new W3CDom().fromJsoup(jsoupDoc);

Element docE = doc.getDocumentElement();
LOGGER.info("Main tag name: {}.", docE.getTagName());
----

== Refs

* Parsing from DOM and related technologies in Java: see https://docs.oracle.com/javase/tutorial/jaxp/TOC.html[JAXP] tutorial (focus on the parts related to the DOM)
* https://en.wikipedia.org/wiki/Comparison_of_HTML_parsers[Comparison] of HTML parsers (Wikipedia)
* W3C https://www.w3.org/TR/2015/REC-dom-20151119/[DOM4] (Recommendation 19 November 2015), a snapshot of the DOM Living Standard

