= SOAP in brief
:toc:
:toc-placement: preamble
:sectanchors:

This document gives a _rough_ and _incomplete_ overview of SOAP 1.2.

NOTE: The reader supposedly has basic knowledge of link:HTTP.adoc[HTTP] and XML.

////
:toc: macro
...
toc::[]
https://github.com/jbake-org/jbake/issues/80#issuecomment-60754340
////

== Overview
The Simple Object Access Protocol (SOAP) specification defines [small]#(non exhaustive list)#:

* an _abstract_ exchange protocol of [small]#(specific species of)# XML Infosets;
* a binding that specifies how those XML Infosets are to be serialized [small]#(and more, see below)#.

=== XML Infoset

* An XML Infoset is an abstract data type. _Serialization_ transforms the XML Infoset into a concrete representation in bytes.
* An obvious example of serialization of an XML Infoset is the XML serialization (`<book><title>Sir</title></book>`), but others are conceivable (some encrypted serialization for example) or exist. As an example, the W3C _SOAP Message Transmission Optimization Mechanism_ (https://www.w3.org/TR/2005/REC-soap12-mtom-20050125/[MTOM]) spec defines an optimized serialization of SOAP messages.

=== SOAP transmission
A SOAP transmission may involve several nodes having distinct roles. Two special roles are the _Initial SOAP sender_ and the _Ultimate SOAP receiver_ roles.

== SOAP message
SOAP [small]#typically# transmits _SOAP messages_. A SOAP message is a species of XML Infoset. It has an `env:Envelope` root element, which may contain two sub-elements. [small]#(The `env` prefix corresponds to the namespace name `\http://www.w3.org/2003/05/soap-envelope`.)#

* The `env:Header` optional sub-element may serve to give informations to SOAP processing nodes (and may be altered by those nodes) on the way from the initial sender to the ultimate receiver.
* The `env:Body` mandatory sub-element has application-specific content. It is empty or contains a sub-element from a possibly application-specific namespace.

See https://www.w3.org/TR/2007/REC-soap12-part1-20070427/#firstexample[example 1] (from SOAP spec part 1).

== Binding
A binding makes SOAP transmission concrete. It specifies:

* how to serialize XML Infosets;
* mechanisms to support _features_ (that extend the transmission protocol), such as the SOAP Web Method feature, the Message Exchange Patterns (MEPs) feature (see below), or the SOAP Action feature (not explained here).

=== The Message Exchange Patterns feature
The spec defines two basic MEPs:

* SOAP Response: involves a non-SOAP request and a SOAP response;
* SOAP Request-Response: involves a SOAP request and a SOAP response.

[[HTTP_binding]]
== The HTTP binding
The spec specifies what a SOAP binding is in general (see above), and specifies one such concrete binding, namely the HTTP one.

This binding has two MEPs (that consist in further specifying the two basic MEPs seen above).

* SOAP Response: an HTTP `GET` followed by an HTTP response that contains a SOAP message as a body;
* SOAP Request-Response: an HTTP `POST` containing a SOAP body, followed by a response as above.

The `application/soap+xml` media type is [small]#(typically)# used in those exchanges.

Despite forceful argumentation in the spec in favor of applying the SOAP Response MEP when appropriate, most implementations only consider the SOAP Request-Response MEP (possibly with an empty body in the request).

== SOAP RPC
The spec defines how SOAP may be used for Remote Procedure Calls (RPCs).

* A procedure is viewed as a named operation that has input parameters, output parameters, possibly a return value, and fault types (that can be used instead of outputs and return values). Some parameters may be both input and output.
* A RPC invocation has, as SOAP body, a struct named after the invoked operation and with children corresponding to the input parameters.
* A RPC response has, as SOAP body, a struct with a child `response` in namespace `\http://www.w3.org/2003/05/soap-rpc` (if the procedure declares a return value) and other children for other output parameters.
* Encoding of such structs into the SOAP body is left to be defined by the application.

== Refs

* W3C https://www.w3.org/TR/soap/[SOAP] recommendation
* W3C https://www.w3.org/TR/2007/REC-soap12-part0-20070427/[SOAP primer] (I recommend it, it’s clear and short)
* Web Services Interoperability (WS-I) http://www.ws-i.org/deliverables/workinggroup.aspx?wg=basicprofile[Basic Profile] (BP) clarifies and modifies SOAP and related specifications to promote interoperability.

== Supplementary details

The spec defines a specific encoding, SOAP encoding, for structs used in RPCs, but it is not used anymore. (See link:WSDL.adoc[WSDL in brief].)

A SOAP Web Method is one of `GET`, `POST`, `PUT`, `DELETE`, understood as their HTTP equivalent. The SOAP Web Method feature permits to specify which SOAP Web Method is to be used for a given SOAP message exchange. This feature is available for use in any binding.

The HTTP binding also requires support for the SOAP Action feature and for the SOAP Web Method feature. The latter is restricted to value `"GET"` or `"POST"`, depending on the chosen MEP.

The SOAP spec permits multiple elements inside a body element inside the envelope, but BP http://ws-i.org/Profiles/BasicProfile-2.0-2010-11-09.html#R9981[R9981] modifies this.

