= Various tools
:sectanchors:

Various useful tools for Java and Java EE developers.

== Java

* http://www.oracle.com/technetwork/java/javase/downloads/index.html[Java] 8 (or 9)
** Important advice. Uninstall every version of Java you have, keep only one: the latest JDK (which includes a JRE).
** On Debian: https://packages.debian.org/search?keywords=openjdk-8-jdk&searchon=names&exact=1&suite=all&section=all[openjdk-8-jdk] (optionally, install https://packages.debian.org/search?keywords=openjdk-8-source&searchon=names&exact=1&suite=all&section=all[openjdk-8-source] to have the Javadoc accessible even when coding offline).
* https://maven.apache.org/download.cgi[Maven]

For Java SE, add:

* https://www.eclipse.org/downloads/[Eclipse IDE] “for Java Developers”

For Java EE, add:

* https://www.eclipse.org/downloads/[Eclipse IDE] “for Java EE Developers”
* `GlassFish Tools` plug-in: from Eclipse, Help / Eclipse Marketplace…
* https://javaee.github.io/glassfish/download[GlassFish] (Full Platform)
** `GlassFish Tools` (hence Eclipse) does not yet (as of October 2017) work with GlassFish 5. Therefore I suggest to download and install GlassFish 4.x (that implements Java EE 7). The differences with Java EE 8 are small, for what concerns this course.

== Git

* Git https://git-scm.com/downloads[client]
** Optional: https://git-for-windows.github.io/[Git for Windows]; https://tortoisegit.org/[TortoiseGit].
** https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup[Configure] your git identity: `user.name` and `user.email`. (Specific for GitHub: https://help.github.com/articles/setting-your-username-in-git/[user.name], https://help.github.com/articles/setting-your-email-in-git/[user.email].)

== Eclipse
For Eclipse users, I strongly recommend reading the following. It does take some time, but will pay off as it will greatly increase your productivity and pleasure of coding.

* Eclipse Workbench User Guide, http://help.eclipse.org/neon/topic/org.eclipse.platform.doc.user/gettingStarted/qs-02a.htm?cp=0_1_0_0[Basic tutorial]
* Workbench User Guide, http://help.eclipse.org/neon/topic/org.eclipse.platform.doc.user/tips/platform_tips.html?cp=0_5[Tips and Tricks]
* Java development user guide, http://help.eclipse.org/neon/topic/org.eclipse.jdt.doc.user/gettingStarted/qs-2.htm[Basic tutorial]
* Java development user guide, http://help.eclipse.org/neon/topic/org.eclipse.jdt.doc.user/tips/jdt_tips.html?cp=1_5[Tips and Tricks] (JDT) (bit by bit!)

[[Eclipse-strict]]
=== Configuration
I recommend configuring Eclipse to show more errors and warnings in order to help spot mistakes and code smells early.

* From Eclipse, import my sample link:++Best practices/Eclipse-prefs.epf++[epf] (Eclipse preference) file. 
* You can read the file contents to see what this changes to your Eclipse configuration.
* Check in `Windows / Preferences` whether the changes were applied. For example, check in `Java / Code Style / Code Templates` that the `Catch block body` contains `throw new IllegalStateException(e);`.
* Check in your project properties, `Java Compiler / Errors/Warnings` that the project uses your global Eclipse compiler settings.
* Clean and recompile your project to see the effect.

== VM (beta)
https://universitedauphine-my.sharepoint.com/personal/olivier_cailloux_lamsade_dauphine_fr/_layouts/15/guestaccess.aspx?docid=03887190377294e79a8a63c8f063ffe9b&authkey=AdV4WjBgnfjLa2IRffbav5s&e=10400376c63043138b324257b2c8c6a6[Here] is a Virtual Machine (VM) file that contains all the tools above. (SHA-1: f4c13d7426a2e4a2f68a22b6b4db13da90fdb988.) It features https://www.debian.org/doc/user-manuals[Debian] stretch (9.2), a GNU/Linux system. The VM file is in a standard format (OVA). You can import it in https://www.virtualbox.org/[Virtual Box] for example.

The file is in beta version, please report any issues https://github.com/oliviercailloux/Deb-9-VM[here].

Note that you will get (much) better performance by installing the tools directly on your machine rather than using them through a VM.

