= Logging framework usage

A short note about apparent usage of two prominent logging frameworks: JUL and SLF4J.

== Java Utils Logging
JUL is the “official” logging approach for Java. See Oracle’s https://docs.oracle.com/javase/8/docs/technotes/guides/logging/index.html[tutorial] about JUL

To log using Java Utils Logging (JUL), in case you prefer this to SLF4J, proceed as follows. First, declare a logger in your class using this code.

----
@SuppressWarnings("unused")
private static final Logger LOGGER = Logger.getLogger(MyClassName.class.getCanonicalName());
----

You can then write logging statements such as `LOGGER.info("Hello, world.");`.

== Usage
I did a very quick comparison for attempting to measure the popularity of each approach.

* https://github.com/search?l=java&q=%22org.slf4j%22&type=Code[SLF4J]: 6M (or https://github.com/search?l=java&q=%22org.slf4j.Logger%22&type=Code[org.slf4j.Logger]: 6M)
* https://github.com/search?l=java&q=%22java.util.logging%22&type=Code[JUL]: 4M (or https://github.com/search?l=java&q=%22java.util.logging.Logger%22&type=Code[java.util.logging.Logger]: 2.5M)

This is of course very crude. A more solid comparison would attempt to estimate how many “big” and “recent” projects use each one, for example. (But at this stage I honestly do not think it is worth the effort, see below.)

== Conclusion
I usually favor standards, but in this case, I think SLF4J is to be preferred for technical reasons (which you can read elsewhere, see e.g. the Stack Overflow post below). It also helps that it seems to be hugely popular, so it is arguably a “de facto standard”, though not the “official” one.

== More information
* https://stackoverflow.com/questions/11359187/why-not-use-java-util-logging
* Antonio Goncalves’ https://antoniogoncalves.org/2012/09/06/i-need-you-for-logging-api-spec-lead/[blog post] about the sad multiplicity of logging frameworks in Java
* https://www.overops.com/blog/is-standard-java-logging-dead-log4j-vs-log4j2-vs-logback-vs-java-util-logging/

