= Maven best practices

== Naming conventions

Summary:

* Make sure your Maven `groupId` is unique. For this, prefix it with a domain name you control (or that you can use), inverted, with underscores replaced by hyphens. Example, in my case: `io.github.oliviercailloux.something`.
* As Maven `artifactId`, use your project name, with spaces replaced by hyphens, in lowercase. Example: `my-project-name`.
* In Maven identifiers (`groupId` and `artifactId`), avoid Java keywords and “words” starting with a digit.
* As Java base package name, use your Maven coordinates, to ensure uniqueness, with hyphens removed (example: `io.github.oliviercailloux.something.myprojectname`).

.Details
[%collapsible]
====
* Maven coordinate identifiers (`groupId` and `artifactId`) should contain lowercase letters, digits, and hyphens only (https://maven.apache.org/maven-conventions.html[source]).
* To make sure they are unique, use a domain name you control as a `groupId`, and invert it (https://maven.apache.org/guides/mini/guide-naming-conventions.html[source]).
* Java conventions suggest to ensure uniqueness of your package names using the same rule (source: https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html[tutorial], or see the non-normative note “Package names” in the https://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html#jls-6.1[specs]).
* Thus, I suggest naming your packages according to your `groupId` followed by a dot followed by your `artifactId`.
* Hyphens are not allowed in package names, but underscores are:
** package names consist in dot-separated identifiers, see https://docs.oracle.com/javase/specs/jls/se8/html/jls-7.html#jls-7.4.1[JLS 7.4.1];
** identifiers consist in a `JavaLetter` then a set of `JavaLetterOrDigit`, a `JavaLetter` being a character for which `Character.isJavaIdentifierStart(int)` returns `true`, see https://docs.oracle.com/javase/specs/jls/se8/html/jls-3.html#jls-Identifier[JLS Identifiers];
** this includes the ASCII underscore (known as LOW LINE in Unicode, U+005F) but not the hyphen, see https://docs.oracle.com/javase/8/docs/api/index.html?java/lang/Character.html#isJavaIdentifierStart-int-[Character], http://www.fileformat.info/info/unicode/category/Pc/list.htm[Unicode], https://stackoverflow.com/a/32065830[SO].
** BUT Google Java Style Guide recommends using no hyphens or underscores in package names.
* Thus, I suggest to remove hyphens used in `artifactId` when converting to package name.
* In Maven identifiers, avoid Java keywords and “words” starting with a digit: they are legal in Maven but not convertible to Java identifiers.
* See also https://central.sonatype.org/pages/choosing-your-coordinates.html[Sonatype: Choosing your Coordinates].
====

== Encoding
Include the property `<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>` in your POM to ensure platform-independent behavior (and get rid of the warning Maven prints otherwise).

== Java version
Include the property `<maven.compiler.release>17</maven.compiler.release>` (or adjust to the desired java version) to indicate which java version you develop in (and for). This is https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html[officially supported] and is thus to be preferred to the more verbose explicit https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html[configuration] of the `maven-compiler-plugin`. (The https://stackoverflow.com/questions/43102787/what-is-the-release-flag-in-the-java-9-compiler[`release`] attribute makes the `source` and `target` ones redundant.)

== Understand the code you reuse
The POM may include a https://maven.apache.org/pom.html#More_Project_Information[`<url>`] element. If you use it, make sure it refers to your project. I often see `<url>` pointing to \http://maven.apache.org, that is wrong! Do not copy templates without understanding their contents!

