= Maven central

How to deploy Maven artifacts to OSSRH and to Maven central.

== Prerequisites
You know how to build a https://github.com/oliviercailloux/java-course/blob/master/Maven/README.adoc[Maven] package.

== Overview
Maven artifacts can be deployed to remote repositories, or repository hosting (RH) locations, to make them accessible to other developers. 
The RH of choice for most open source projects is Sonatype’s Open Source Software Repository Hosting (OSSRH). (OSSRH is managed by the Sonatype Nexus https://maven.apache.org/repository-management.html[repository manager].)

You can deploy to OSSRH both development versions of your artifacts (snapshots), or releases (whose contents will never change). A Maven artifact is a snapshot iff its version number ends with `-SNAPSHOT`.

One good thing about OSSRH is that it is an approved RH, in Apache parlance, meaning that it is authorized to send releases to Maven central. Only releases can be sent to Maven central, not snapshots (https://maven.apache.org/repository/guide-central-repository-upload.html[Apache Guide]).

Maven central, also called the Central Repository, is a sort of “default” remote repository for Maven artifacts: Maven will search by default in Maven central for dependencies required by your project. In turn, deploying your artifacts to Maven central make them easily accessible to other developers.

== Preparation
Artifacts must be signed with a https://central.sonatype.org/pages/working-with-pgp-signatures.html[PGP] key. Follow the link to set up the required tool on your system and distribute your key.

You need to get your project authorized in OSSRH. (Sonatype essentially checks that you do not usurp someone’s identity with your groupId.) For this you need to https://central.sonatype.org/pages/ossrh-guide.html#create-a-ticket-with-sonatype[create a ticket] with Sonatype. Wait that your ticket is resolved before trying to deploy. (In my experience answers come within a few hours.)

== POM

. Make sure your Maven coordinates are https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Maven.adoc#naming-conventions[right]. Make sure your version ends with `-SNAPSHOT` (the suggested initial version number being `0.0.1-SNAPSHOT`): for the moment we’ll practice deployment using snapshots.
. Provide metadata to your project: project name, description, url, license, developer information, scm information (see https://central.sonatype.org/pages/requirements.html#sufficient-metadata[metadata requirements]). You can simply copy and adapt the relevant XML elements in this https://github.com/oliviercailloux/pom/blob/master/pom.xml[sample].
** Apache Guide insists that providing good quality metadata is important. “The POM being deployed with the artifact is part of the process to make transitive dependencies a reality in Maven. The logic for getting transitive dependencies working is really not that hard, the problem is getting the data. The other applications that are made possible by having all the POMs available for artifacts are vast, so by placing them into the repository as part of the process we open up the doors to new ideas that involve unified access to project POMs.” From the Apache Metadata https://maven.apache.org/project-faq.html[FAQ]: “The quality of the metadata in the Maven repository is important to your users as they list dependencies on your metadata, and link in the information into their own projects.” (That FAQ is otherwise outdated.)
** I recommend using only the `scm/connection` and `scm/url` elements, and not the `scm/developerConnection` one, because the first two permit to read your source code and thus is precious metadata; whereas the latter gives write access, and is therefore not useful for persons external to your project, and furthermore only serves with the `maven-scm-plugin` and `maven-release-plugin`, which I do not recommend to use.
. Make sure your dependencies have the right scope. See https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html[Dependency Mechanism] (or https://maven.apache.org/pom.html[POM Reference]). Provide only dependencies that exist in Maven central, if possible. (“we discourage the usage of <repositories> and <pluginRepositories> and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.”, https://central.sonatype.org/pages/requirements.html#sufficient-metadata[requirements])
. Create a `release` profile section
** Add into the `release` profile a `distributionManagement` element containing the `snapshotRepository` element (again, see sample above). (See also the Sonatype https://central.sonatype.org/pages/apache-maven.html[Maven guide].) 
** Add some plugins into the `release` profile: `maven-source-plugin`, `maven-javadoc-plugin`, `maven-gpg-plugin`, `org.sonatype.plugins:nexus-staging-maven-plugin` (again, see sample above). (Note that the Sonatype documentation indicates old version numbers, see https://maven.apache.org/plugins/index.html[Apache Maven Plugins].)
. Change your `~/.m2/.settings.xml` file, or create it, to make it look like https://gist.github.com/oliviercailloux/3cc79ed504f986b5ea3442fa6e83f053[this]. This lets `mvn deploy` know the credentials to access the OSSRH repository.

== Deploy a snapshot
Run `mvn -Prelease deploy`. Maven activates the `release` profile and goes through all the phases of the default http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference[lifecycle]. If everything goes well, it will compile your project, run the tests, attach the sources and javadoc, sign those artifacts with GPG, and deploy them to OSSRH.

If deployment is successful, your artifacts should be immediately visible https://oss.sonatype.org/content/repositories/snapshots/io/[here] (replace the “io” part of this URL with your maven coordinates, for example, my snapshots are visible https://oss.sonatype.org/content/repositories/snapshots/io/github/oliviercailloux/[here]).

You can deploy several times using the same version number, provided it is a snapshot.

== Deploy a release
When you are ready to release, remove the `-SNAPSHOT` suffix from your Maven coordinates version number. Run `mvn -Prelease deploy`.

If successful, your release will immediately appear in the https://repo1.maven.org/maven2/io/[public release] section of OSSRH (replace the “io” part of this URL with your maven coordinates), and within https://central.sonatype.org/pages/ossrh-guide.html#releasing-to-central[ten minutes] (https://stackoverflow.com/questions/23235892/how-long-does-sonatype-staging-take-to-sync-my-artifacts-with-maven-central#comment45591048_23236185[thanks]) it will automatically transfer to Maven central (your artifact should appear in the https://search.maven.org/[search] interface within https://central.sonatype.org/pages/ossrh-guide.html#releasing-to-central[two hours]). Remember that you publish a release version once and for all, contrary to snapshots: no overwrite is allowed. 

As soon as you have successfully published a release, commit it to your SCM, tag the commit with the corresponding version number, then increase the version number in the POM and put the `-SNAPSHOT` suffix back, and commit again, in order to start a new development cycle. See https://github.com/oliviercailloux/Deploy-script/blob/master/Deploy.bash[this bash script] if you want to automate these steps.

