= Maven

See https://github.com/oliviercailloux/java-course/raw/master/Maven/Pr%C3%A9sentation/presentation.pdf[présentation], https://github.com/oliviercailloux/java-course/blob/master/Maven/Exercices.adoc[exercices], https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Maven.adoc[best practices], https://github.com/oliviercailloux/java-course/blob/master/Tools.adoc[Tools] for installation. When you’re ready, publish your open source artifacts to https://github.com/oliviercailloux/java-course/blob/master/Maven/Maven%20central.adoc[Maven central]!

== Eclipse
To import a Maven project into Eclipse, use `File` / `Import` / `Existing Maven Projects`.

=== Hint
If Eclipse is lost, first try to update the Eclipse configuration from the Maven configuration. From your project properties, run `Maven` / `Update project` / `Update project configuration from pom.xml`.

If Eclipse is still lost, make sure it uses the configuration from Maven (sometimes the above procedure does not suffice):

* Delete the project from Eclipse
* Using a file navigator, manually delete the Eclipse configuration from within your project: `.project`, `.classpath` and the folder `.settings`.
* Re-import the project into Eclipse. This forces Eclipse to re-create the configuration from scratch (based on Maven).

== References
* Simple, recommended https://github.com/oliviercailloux/java-se-1.8-archetype/blob/master/src/main/resources/archetype-resources/pom.xml[POM]
* https://maven.apache.org/guides/getting-started/index.html[Tutorial] Apache Maven
* https://books.sonatype.com/mvnref-book/reference/index.html[Book] Maven: The Complete Reference
* https://books.sonatype.com/mvnex-book/reference/index.html[Book] Maven by Example
* Apache http://maven.apache.org/guides/[website]
* Apache Maven Cookbook, Raghuram Bharathan, 2015
* Archetypes: http://maven.apache.org/archetype/maven-archetype-plugin/usage.html[maven-archetype-plugin]
//* Packaging
* Assemblies: http://maven.apache.org/plugins/maven-assembly-plugin/[maven-assembly-plugin]
//== Refs
//* http://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging

