= Resources

Scenario: your class `MyClass` requires a resource `data_file.csv` to work. Where should you put it and how to access it from code?

You first decision is to either access the resource through the file system, or through the class path. I favor class path access. Here we assume the resource is accessed through the class path.

== Use unique names
You need to give your resource a unique name. Otherwise, conflicts may happen with other packages (another package might come with a resource named like yours). The full name of a resource is its package name, a dot, and its file name. For example, a resource with package name `com.mydomain.myproject.mysubpackage` and file name `data_file.csv` has the full name `com.mydomain.myproject.mysubpackage.data_file.csv`. To get things nicely sorted out, I suggest to use the package name of the (main) class that uses the resource. (Remember that your class must also have a https://github.com/oliviercailloux/java-course/blob/main/Maven/Best%20practices.adoc[unique package name].)

Example: the resource is processed by some class `MyClass` in the package `com.mydomain.myproject.mysubpackage`, and therefore you adopt the full name `com.mydomain.myproject.mysubpackage.data_file.csv` for your resource.

== Locate the resource
You must now put your resource into a folder whose path, relative to the root of your project resources, must correspond to its package.

Example: your resource has full name `com.mydomain.myproject.mysubpackage`, and therefore you put it into the folder `com/mydomain/myproject/mysubpackage` in your resource folder.

== Access the resource
Here is a simple way to access your resource.

[source,java]
----
URL resourceUrl = MyClass.class.getResource("data_file.csv");
----
With this statement you ask the class loader to get your resource from the class path, relative to the path of `MyClass`. You obtain a reference to the said resource. You can then use https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/net/URI.html#create(java.lang.String)[`URI.create`] to transform this `URL` into an `URI` then https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/nio/file/Path.html[`Path`] to transform the resulting `URI` into a `Path` instance (but note that this approach will https://stackoverflow.com/a/36021165/[fail] to read from a non modular jar); or invoke `resourceUrl.openStream()`, for example. (See https://github.com/oliviercailloux/java-course/blob/main/Flows.adoc[Flows] about reading from byte or character streams.)

== Do not write in your class path or in your source folder
By design, the class path contains data that your program can *read*, but not write. If you want to write data, this should not be on the class path. Rather write into memory; on the user’s hard disk; on the network… (See https://github.com/oliviercailloux/java-course/blob/main/Flows.adoc[Flows] about writing byte or character streams.)

Similarly, do not write in your source folder (for example, do not write to `src/test/resources`). Your *source* folder, by convention, is there to hold resources that serve as sources for your program, not as a place to store data or to write temporary data.

== Exercice: read from class path
. Create manually a file `Hello.txt` containing “Hello, world”.
. Choose a suitable full name for this resource.
. Place this resource in your class path accordingly.
. Write a unit test that reads the content of this file and checks that it is indeed “Hello, world”.

