= Projets

== Affectation initiale
* https://github.com/oliviercailloux/projets/tree/master/SE[Énoncés]
* Max. une équipe par sujet
* Équipes de 4 à 7
* Obligation d’accepter membres supplémentaires à la demande si < 7
* Inscription dans colonne : noter tous les noms. Il faut être au moins 4 pour noter son nom. Indiquer le numéro d’ordre d’inscription de l’équipe (numérotation par sujet). S’effacer d’une colonne si on s’inscrit dans une autre.
* Si conflit : plus grosse équipe prioritaire ; puis première équipe inscrite (lexicographiquement)

== Instructions générales
* Quatre itérations au total, chacune clôturée par une livraison
* Une livraison par 2 (ou 3) séances, environ 12h (ou 18h) de travail sur projet par sous-équipe (calendrier dans programme du cours)
* Une équipe de _n_ personnes est constituée de _n/2_ (arrondi au-dessus) sous-équipes : des binômes de développeurs et une sous-équipe de un ou deux Scrum Master / Product Owner (nommée ci-après « le SM/PO » pour désigner la sous-équipe, même quand ils sont deux)
* Sous-équipes doivent changer à chaque itération ; être maximum deux fois SM/PO en tout
* SM/PO : planifie avec son équipe les _tâches_ à délivrer, documente, fournit des diagrammes (exigences un peu plus grandes si binôme que si seul) ; réoriente les tâches en cas de problème de prérequis ; vérifie que le projet fonctionne toujours après fusion ; est responsable de la cohérence du tout
* La sous-équipe SM/PO délivre (typiquement) une tâche en début d’itération, pour annoncer le travail à effectuer, et une ou plusieurs tâches pendant la livraison (documentation, diagrammes, réorientation du planning). Un binôme dev. travaille sur une (typiquement) ou plusieurs tâches dans une itération (exemple : coder une hiérarchie de classe pour enregistrer des commandes de produit). Une tâche peut consister à compléter une tâche précédente (ajout de tests unitaires, correction bugs, …).

== Démarrage du projet
Au départ, prenez le temps de réfléchir ensemble globalement au projet et tracez les grandes lignes de votre ambition à la fin de l’année. Inutile d’élaborer un plan détaillé, car il serait impossible à respecter, mais cette étape de réfléxion dans les grandes lignes est utile pour vous donner un sens commun de votre objectif global.

Allez où vous voulez en fonction de vos intérêts (plutôt GUI, plutôt génération de graphiques, plutôt web, …). Soyez imaginatifs. Vous pouvez proposer de sortir du cadre imposé. Cependant, je joue le rôle du client et je dois approuver la direction que vous voulez donner au projet.

Il n’est pas nécessaire d’obtenir un logiciel très beau ou très utile pour un utilisateur final : vous pouvez développer une bibliothèque solide pour des programmeurs ultérieurs (qui eux pourront en faire un programme pour utilisateurs finaux).

Au départ, vous créez un dépôt pour votre projet (un https://help.github.com/en/articles/fork-a-repo[fork] si vous repartez d’un existant). Vous travaillez tous uniquement sur votre dépôt de groupe. 

La première itération doit _commencer_ par une tâche nommée Livraison 1 de la responsabilité du SM/PO qui indique, dans le `README.adoc` du projet, les grandes lignes des quatre itérations, et avec plus de détails le contenu de l’itération à venir avec une découpe en tâches. Il n’indique pas nécessairement qui fait quoi, je laisse l’équipe s’organiser comme elle veut. Bien sûr, ce plan est élaboré par tous les membres du projet, le SM/PO n’est pas un dictateur qui attribue des tâches comme il veut. Le plan prend bien soin de détailler les pré-requis entre tâches éventuels, et dans ce cas, indique un calendrier pour éviter de coincer les sous-équipes qui dépendent des autres (je ne vérifierai pas que ce calendrier est respecté, ça sert en interne à l’équipe). Le SM/PO crée aussi un squelette initial de projet avec Maven, si ce n’est pas un fork. Tout ceci est commis non pas directement dans la branche `master`, mais en suivant les instructions de livraison indiquées dans ce document. Le SM/PO s’attribue une ou plusieurs tâches de documentation (rapport concernant l’état actuel du projet en cas de fork, diagramme de classe montrant l’issue envisagée de la première itération, …). Toute tâche doit être associée à un livrable : généralement mais pas nécessairement, pour un binôme de développeurs, du code, et pour le SM/PO, un document au format Asciidoctor ou un ou plusieurs graphiques.

Commencez à coder seulement lorsque j’ai approuvé votre proposition de plan de livraison, pour éviter le travail inutile.

== Instructions de livraison
* Interdiction de commettre sur votre branche `master` sans mon aval. À part ça, organisation interne libre. Suggestion : fusionnez vos fcts sur une branche `dev` dès que possible (https://fr.wikipedia.org/wiki/Int%C3%A9gration_continue[intégration continue]).
* M’ajouter comme collaborateur à votre projet pour pouvoir m’indiquer comme https://help.github.com/en/articles/about-pull-request-reviews[Reviewer].
* Quand vous avez terminé une tâche, créez une pull request (PR) GitHub pour cette tâche, d’une branche dont le nom décrit succinctement la tâche (exemple : « unit tests Truc ») vers _votre_ branche `master`. La branche peut être créée après coup, il faut alors y placer manuellement (par exemple) les modifications en rapport avec cette tâche.
** https://help.github.com/en/articles/assigning-issues-and-pull-requests-to-other-github-users[Affectez] à la PR tous les membres de la sous-équipe responsable de la tâche.
** M’ajouter comme Reviewer pour que je sois averti. Si opportun, je commente votre tâche pour indiquer les améliorations à effectuer avant de pouvoir fusionner dans `master` (à faire lors d’une prochaine itération), ou je vous indique que vous pouvez fusionner.
** Si vos collègues dépendent de votre tâche, vous pouvez bien sûr (ou devriez) modifier directement sans attendre la prochaine livraison. Ce sera en particulier le cas si vous êtes le SM/PO et que votre tâche définit le plan à suivre pour cette livraison. Dans ce cas, effectuez des commits sur la branche de votre tâche, puis commentez en me https://github.blog/2011-03-23-mention-somebody-they-re-notified/[@mentionnant] (`@oliviercailloux`) quand vous êtes prêt pour une nouvelle review.
** Si votre tâche poursuit une tâche d’une livraison précédente, il s’agit quand-même d’une nouvelle tâche. Créez une nouvelle PR, pour que je m’y retrouve, et indiquez le binôme qui s’en occupe (qui devrait avoir au moins partiellement changé).
** Vous remettez un devoir, pas un brouillon mal torché. Soignez-le. Votre code doit être mis en forme systématique, suivre les https://github.com/oliviercailloux/java-course/tree/master/Best%20practices[bonnes pratiques], vous devez prendre en compte d’éventuelles indications d’erreurs de vos outils (Eclipse, GitHub, Travis, …), etc. Faites tout ça _avant_ de m’indiquer comme reviewer sur une PR. (Vous pouvez compléter une PR après sa création en ajoutant des commit dans la branche associée.)
* Si vous ne respectez pas une des instructions notées ici, j’indiquerai simplement INSTR SVP, car je n’ai pas le temps de rappeler les instructions à chacun en détail. Dans ce cas, _votre livraison n’est pas acceptée_. J’attends une correction pour respect des instructions. (Suivez les instructions de modification sur une même branche, ci-dessus.) En attendant, votre délai de retard cours, si la date de livraison est dépassée. (Seule cette abréviation INSTR indique que votre livraison n’est pas acceptée. Si j’utilise d’autres abréviations, elles se réfèrent généralement à la table ci-dessous, et font partie de mon évaluation normale de votre tâche.)

Lors de la dernière itération, vous ajouterez dans votre README de projet une ligne indiquant, pour chacun d’entre vous, la diversité des tâches auxquelles vous avez participé (exemple : GUI dans tâche Truc, test unitaire dans tâche Bidule, parsing XML dans tâche Machin), et éventuellement un commentaire bref indiquant les difficultés particulières auxquelles vous avez été confronté dans votre projet ou dans vos tâches en particulier, pour attirer mon attention lors de l’évaluation finale.

Don’t hesitate to send me your question by e-mail if you’re blocked in your project, instead of wasting hours. However, I do expect that you make some research before you ask, and that your question be clear. See these https://codeblog.jonskeet.uk/2012/11/24/stack-overflow-question-checklist/[guidelines].

== Évaluation
* Chaque sous-équipe reçoit une note par livraison (agrégeant mon évaluation de l’ensemble de ses tâches durant cette itération).
* Plus j’ai insisté en cours sur des erreurs à éviter, plus la notation sera sévère si ces erreurs sont commises (par exemple, masquer les exceptions).
* Si vous livrez une tâche qui n’apporte encore rien parce qu’elle dépend d’un pré-requis qui n’a pas été livré (suite par exemple à un problème d’organisation dans le groupe), vous serez nécessairement en échec. Exemple : développement d’un GUI alors que les fonctionnalités manquent. Le code livré doit fonctionner et je dois avoir les éléments en main pour comprendre son intérêt. (Vous pouvez parfois coder certaines choses par exemple qui dépendent d’une interface existante n’ayant pas encore d’implémentation finalisée ; mais c’est à discuter au cas par cas avec moi au moment de l’élaboration de votre plan.)
* Dates de livraison précisées dans le programme du cours. https://www.wolframalpha.com/input/?i=Plot%5BPiecewise%5B%7B%7B-1%2F2*x,x%3C+2%7D,%7B-2%2F22*(x-2)-1,+2%3C%3D+x+%3C+24%7D,%7B-1%2F24*x-2,+24%3C%3D+x%7D%7D%5D,+%7Bx,+0,+72%7D%5D[Non respect] des dates : −0,5/20 pour 2h de retard, −3 pour 24h de retard puis −1 par jour supplémentaire.
* L’évaluation tient compte particulièrement de la qualité du travail fourni (potentiel de réutilisabilité, facilité d’appropriation par d’autres développeurs, facilité de maintenance à long terme, clarté de la documentation), et en second lieu seulement de la quantité (bonus / malus si le travail accompli prendrait sensiblement plus / moins que les 12h ou 18h attendus pour cette itération si effectué par un étudiant attentif au cours et suivant les recommandations), et prend fortement en compte la difficulté de la tâche (technologies non vues au cours, …).
* Si un membre d’un binôme n’a pas travaillé durant une livraison, indiquez-le en affectant un seul membre aux tâches de cette livraison. J’en tiendrai compte dans mon évaluation (travail de qualité plus difficile seul).
* Note finale projet : moyenne de vos quatre notes de livraison, avec bonus / malus pour la diversité de vos tâches, les éventuelles difficultés particulières, la cohésion de l’équipe et la cohérence globale de son projet, et la présentation finale.
* Vous devez utiliser autant que possible les technologies vues au cours et les standards ISO, W3C et JSR Java dans votre projet (par exemple, JSON-B ou JSON-P et non Jackson).
* Privilégiez les méthodes statiques aux constructeurs.
* Si vous modifiez du code existant, vous êtes responsable d’améliorer raisonnablement le code qui l’entoure là où c’est facile, de corriger les bugs évidents. Ne vous dédouanez pas d’erreurs évidentes sous prétexte que ce n’est pas vous qui avez écrit telle ou telle ligne de code précisément.
* Lorsque vous intégrez du code d’autrui, il faut indiquer que votre projet l’utilise. Cette mention doit être claire, pas être noyée dans un flot de texte où vous décrivez d’autres choses. Par exemple, mentionner dans le README de votre projet la provenance de votre template html. Ou, indiquer la provenance dans la javadoc d’une méthode copiée depuis StackOverflow. Cette règle ne s’applique pas si vous ne copiez qu’une ou deux lignes de codes triviales.
* Je dois voir vos changements facilement et les distinguer de code auto-généré ou importé sans changements de votre part. Si par exemple vous ajoutez un canevas HTML de 100 fichiers, faites-le dans une tâche dédiée, et créez une autre tâche pour vos modifications.
* Maintenez les conversations focalisées. Ce n’est pas une bonne idée, par exemple, d’indiquer dans un commentaire de la PR #37 que vous avez décidé d’abandonner la PR #22 pour telle et telle raison : quand j’évaluerai la PR #22 par la suite, il est peu probable que je me souvienne de vos explications se trouvant en PR #37.
* Une mission importante du SM/PO est de s’assurer que le projet converge vers un ensemble cohérent de fonctionnalités exploitables dans la branche `master`. Tentez de terminer en priorité les tâches presque finies qui ne sont pas encore dans `master`, par exemple, avant de commencer de nouvelles choses.

=== Abréviations

|===
| Abbrv | Pratique à respecter | Informations | Sanction (/ 10, indicatif)
| INSTR | Respect des instructions concernant la remise (création issues, etc.) | Instructions / project | −2
| UNIK	| noms des ressources est unique et respecte les bonnes pratiques	| https://github.com/oliviercailloux/java-course/tree/master/Search%20path[Search path]		| −1
| CASING	| respect des conventions de nommage	| https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Style.adoc[BP Style]	| −0,5
| FORMAT	| le code est mis en forme systématiquement	| https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Style.adoc[BP Style]	| −1
| WEB	| commit effectué via git	| Git	| −1
| DOC	| Javadoc pour documentation du contrat lorsque utile | | −1
| NOISE	| Sans commentaires auto-générés | Réduit le bruit | −2
| DER	| le dépôt ne contient pas de produits dérivés	| https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Git.adoc[BP Git]	| −1
| FOLDER	| la racine du dépôt est la racine du projet	| https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Git.adoc[BP Git]	| −0,5
| HIST	| Ne pas écraser l’historique	| Git	| 0
| PLAG	| Citer la source quand on inclut du code d’autrui	| https://fr.wikipedia.org/wiki/Plagiat[Plagiat]	| -3
| ECL	| Le code est correct d’après Eclipse : pas de warnings	| https://github.com/oliviercailloux/java-course/blob/master/Tools.adoc#configuration[Tools]	| -1
| CP	| Le code est séparé des autres ressources du class path	| https://github.com/oliviercailloux/java-course/tree/master/Search%20path[Search path]	| −1
| EXC	| Le code échoue rapidement et envoie des exceptions si approprié	| https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Exceptions.adoc#cath-exceptions-only-if-you-have-a-good-reason-to-do-so[BP Exc]	| −2
| REUSE	| Les bibliothèques existantes sont utilisées à bon escient plutôt que réinventer la roue	| 	| −2
| ARRAY	| Privilégier des collections (List, Set, etc.) plutôt que des tableaux de types primitifs	|	| −1
| TEST	| Des tests unitaires ou fonctionnels couvrent les fonctionnalités demandées	| https://github.com/oliviercailloux/java-course/blob/master/JUnit.adoc[JUnit]	| −1
| ENC	| Préciser l’encodage des flux lus ou écrits	| https://github.com/oliviercailloux/java-course/blob/master/Flows.adoc[Flows]	| −1
| EN	| Coder et commenter en anglais	|	| −0,5
| FORE	| Privilégier boucles for each	| https://docs.oracle.com/javase/tutorial/java/nutsandbolts/for.html[Tutorial]	| −0,5
| LOG	| Utiliser des loggers	| https://github.com/oliviercailloux/java-course/blob/master/Log/README.adoc[Log]	| −1
| STREAMS	| Utiliser des streams pour plus de généralité quand approprié	| https://github.com/oliviercailloux/java-course/blob/master/Flows.adoc[Flows]	| −1
| POM	| Respecter les conventions de nommage et autres bonnes pratiques Maven, simplifier le POM autant que possible	| https://github.com/oliviercailloux/java-course/tree/master/Maven[Maven]	| −1
|===


