= Eclipse to WildFly

If you use a Java EE application server, it comes preconfigured with a default DB (that the server will connect to when requested by JPA, for example). Follow the instructions below for connecting Eclipse to the WildFly default DB, or adapt the instructions for your use case. This is not mandatory, but may be useful for debugging as it allows to manually inspect the content of the DB.

== Access to the default WildFly DB from Eclipse
The properties of the default (H2) DB used by WildFly (such as the default database name) can be seen by following the instructions https://github.com/oliviercailloux/java-course/blob/master/WildFly.adoc[here]. Our first mission is to change them. This is because by default, WildFly uses H2 in http://h2database.com/html/features.html#connection_modes[embedded] mode, meaning that only the process in which WildFly executes has access to the DB. This prevents us to connect to that same DB with Eclipse (or anything else). (http://www.mastertheboss.com/jboss-server/jboss-datasource/h2-database-tutorial[Thanks], https://developer.jboss.org/thread/173042[see also].)

* Change in the `${wildfly-dir}/standalone/standalone.xml` file, where `${wildfly-dir}` refers to the WildFly directory, `jdbc:h2:mem:test` to `jdbc:h2:tcp://localhost/mem/test` (or run in the `jboss-cli`: `/subsystem=datasources/data-source=ExampleDS/:write-attribute(name=connection-url, value="jdbc:h2:tcp://localhost/mem:test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE")`)
* With this change, WildFly will use H2 in server mode instead of embedded mode. This requires that an external H2 server runs before WildFly tries to connect (otherwise, you will get a “Connection refused” message from WildFly). To start the H2 server, run `java -jar ${wildfly-dir}/modules/system/layers/base/com/h2database/h2/main/h2-1.4.193.jar`, using the H2 JAR file that comes with WildFly. You will need to have the H2 server running each time you start and use WildFly.

Restart WildFly to apply the new connection settings.

* Within Eclipse: `Preferences / Data Management / Connectivity / Driver Definitions`
* Eclipse needs a JDBC driver to access your DB. Let’s register the H2 driver that comes with WildFly.
** This does _not_ create a connexion: it only declares a new driver definition, that is, a _kind_ of connexion (that you will use in the next step)
** As type, choose simply the `Generic JDBC Driver`.
** As JAR file, point Eclipse to `${wildfly-dir}/modules/system/layers/base/com/h2database/h2/main/h2-1.4.193.jar`.
** As properties, use `Connection URL` = `jdbc:h2:tcp://localhost/mem/test`; `Database Name` = `test`; for `Driver Class`, use the `Browse` option (there’s only one match, `org.h2.Driver`); `user` = `sa`; `password` = `sa`.
* From the `Data Source Explorer` view, create a connexion to your DB (using the driver definition created previously)
* You can now view and edit data from the `Data Source Explorer` view
* The `Tables` folder in the `PUBLIC` schema lists the current tables in this DB. (At start, you will see no tables there, as the DB is empty.)
* You can write and send SQL commands from the `SQL Scrapbook` (with completion!)

* See the http://h2database.com/html/grammar.html[Reference] about H2’s flavor of SQL (and more)

