= Exceptions
//works around awesome_bot bug that used to be published at github.com/dkhamsing/awesome_bot/issues/182.
:emptyattribute:

== Cath exceptions only if you have a good reason to do so
Beginner programmers sometimes catch an exception just to get rid of the problem, and do not do anything in the catch block (or just log or print the exception). This is very bad style as it contradicts the fail-fast principle. Consider rather to re-throw the exception, or to wrap it in an unchecked exception.

== Do not log and throw
If you throw an exception, avoid logging the exception as well. This would lead to double logging, as the caller of the code would also possibly log upon receiving the exception. Only the part of the code that finally deals with the exception and does not re-throw it, if any, should decide of the appropriate action.

== Exception declaration
A method must declare all exception that it can possibly throw that do not extend `RuntimeException`. Runtime exceptions should generally not be declared. Declare those only if you see a specific reason to draw attention to it.

== Throw `NullPointerException` when receiving an incorrect `null` argument
There’s some debate about whether `NullPointerException` or `IllegalArgumentException` should be thrown when receiving an incorrect `null` argument in a method. 

The argument in favor of the latter is that it is clear to the caller that a fault occurred because of an incorrect argument, rather than because of the designer of the API having by mistake tried to access some `null` value. I admit this is a good argument but there’s also good arguments against. 

Thus, I consider it sensible to follow the standard. And the standard is to throw `NullPointerException`.

* Many APIs in the JDK pro-actively throws `NullPointerException`, e.g. https://docs.oracle.com/javase/10/docs/api/java/util/Map.html#containsKey(java.lang.Object)[`Map.containsKey`], https://docs.oracle.com/javase/10/docs/api/java/util/Objects.html#requireNonNull(T)[`Objects.requireNonNull`] (https://stackoverflow.com/questions/3881/illegalargumentexception-or-nullpointerexception-for-a-null-parameter/6358#6358[thanks]{emptyattribute}.)
* https://google.github.io/guava/releases/snapshot/api/docs/com/google/common/base/Preconditions.html#checkNotNull-T-[Guava] also favors `NullPointerException` over `IllegalArgumentException`.
* “Effective Java” agrees, see https://stackoverflow.com/a/6358[SO].
