= Local design
//works around awesome_bot bug that used to be published at github.com/dkhamsing/awesome_bot/issues/182.
:emptyattribute:

Various tips for good code from the local structure point of view (as opposed to architectural design questions), that do not fit in the other categories on this site.

== Method parameters
Avoid method with numerous parameters, especially if they are of the same type. It increases the risk of passing a parameter for another one. For example, avoid `buildPerson(firstName: String, lastName: String, description: String, phoneNumber: String, address: String)` (use a https://codereview.stackexchange.com/a/127509[builder] instead).

== Factor
In algebra, you factor an expression such as `ax+bx+cx` by transforming it into `x(a+b+c)`. View this as a way of not repeating yourself: we say only once to multiply by `x`. Similarly, you can often factor your code. When two methods have some code in common, and only differ by a small portion, there is certainly a way of putting what is common to both methods in a method, and let both methods call this one method, or re-use the code in some other way. You thereby make your code more concise (thus easier to understand and verify) and make sure that there is only one place to change if you spot a bug.

== Avoid important effects in constructors
It is typically expected that merely constructing an object does not produce “important” effects on the running system (unless that’s clearly expressed by the contract, for example, in case of a static factory method). What’s an “important” effect depends on the context, but typical examples are: starting intensive computations, or displaying a GUI on the screen. Rather put this behavior in a method that annonces more clearly that this will happen, and that the user has to call expressly after constructing the object.

== The `#toString()` method
Consider overriding `#toString()` on your model classes, and use the Guava https://github.com/google/guava/wiki/CommonObjectUtilitiesExplained#tostring[helper] to implement it. Favor the form `MoreObjects.toStringHelper(this)`.

== The `#equals(Object)` method
Consider overriding `#equals(Object)` on your model classes. Use the following idiom.

[source,java]
----
@Override
public boolean equals(Object o2) {
	if (!(o2 instanceof Person)) {
		return false;
	}
	if (this == o2) {
		return true;
	}
	Person p2 = (Person) o2;
	return firstName.equals(p2.firstName) && secondName.equals(p2.secondName);
}
----

If the fields may be `null`, use https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/util/Objects.html#equals(java.lang.Object,java.lang.Object)[`Objects.equals(Object, Object)`] instead.

== The `#hashCode()` method
If you override `#equals(Object)`, you must override `#hashCode()` as well. Use simply something like: `return Objects.https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/util/Objects.html#hashCode(java.lang.Object)[hashCode](firstName, secondName)`.

