= Style
//works around awesome_bot bug that used to be published at github.com/dkhamsing/awesome_bot/issues/182.
:emptyattribute:

I mainly refer here to http://google.github.io/styleguide/javaguide.html[GJSG]: Google Java Style Guide, which generally makes sense.

== Most important

* GJSG http://google.github.io/styleguide/javaguide.html#s5.2-specific-identifier-names[5.2], Rules by identifier type
* GJSG http://google.github.io/styleguide/javaguide.html#s2.2-file-encoding[2.2], File encoding: UTF-8
* “Tip: Never make your code less readable simply out of fear that some programs might not handle non-ASCII characters properly. If that should happen, those programs are broken and they must be fixed.” (GJSG http://google.github.io/styleguide/javaguide.html#s2.3.3-non-ascii-characters[2.3.3]{emptyattribute})

== Diff from Google
I disagree with the following in GJSG.

http://google.github.io/styleguide/javaguide.html#s2.3.1-whitespace-characters[2.3.1], “the ASCII horizontal space character (0x20) is the only whitespace character that appears anywhere in a source file”. I rather use tab characters to indent. Tabs for indentation encode intent rather than forcing a specific display behavior. The reader of my source code can then choose (by configuring its editor) to make tabs appear as x number of white spaces, with x its preferred number. (GJSG use whitespace, I believe, because it suggests using a different number of whitespace characters for different types of indent, which I do not do.)

http://google.github.io/styleguide/javaguide.html#s5.2.1-package-names[5.2.1], “Package names are all lowercase, with consecutive words simply concatenated together (no underscores)”. I use underscores to separate words in packages (see https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Maven.adoc[Maven]).

== Compiler settings
Ask your compiler to enable strict checks of possible errors. See link:../Tools.adoc#Eclipse-strict[Eclipse configuration].

As an exception to strict checking, I authorize boxing and unboxing without warnings. This is because first, the warning has drawbacks and second, it is not very effective. First, this warning sometimes encourage writing more obscure code, for example `myMap.put(Integer.valueOf(myInt), myValue)` instead of `myMap.put(myInt, myValue)`. (And stuffing your code with a lot of `@SuppressWarnings("boxing")` is not very clean either.) Second, this warning only helps avoiding possible null pointer exceptions (when unboxing), and this anyway is a problem that happens when dealing with objects. It feels unjustified to spend so much energy specifically on this risk when dealing with numeric types.

== Formatting
Use your IDE mechanisms to format your source code systematically and automatically. Make sure everybody use the same conventions in your team. This reduces the number of conflicts when merging concurrent modifications; and ensures that git comparison works (otherwise, for example, git sees modifications when only the spaces have been changed to tabs, and thus real modifications become hard to find).

== Outdated references
* https://www.oracle.com/technetwork/java/namingconventions-139351.html[Oracle J2EE] (I don’t think this should be taken seriously as it is very old, apparently unmaintained, and not included in recent documentation of Oracle).
* Code https://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html[Conventions] for the Java TM Programming Language contains many https://www.javacodegeeks.com/2012/10/java-coding-conventions-considered-harmful.html[incorrect] suggestions

