= Style

I mainly refer here to http://google.github.io/styleguide/javaguide.html[GJSG]: Google Java Style Guide, which generally makes sense.

== Most important

* GJSG http://google.github.io/styleguide/javaguide.html#s5.2-specific-identifier-names[5.2], Rules by identifier type
* GJSG http://google.github.io/styleguide/javaguide.html#s2.2-file-encoding[2.2], File encoding: UTF-8
* “Tip: Never make your code less readable simply out of fear that some programs might not handle non-ASCII characters properly. If that should happen, those programs are broken and they must be fixed.” (GJSG http://google.github.io/styleguide/javaguide.html#s2.3.3-non-ascii-characters[2.3.3])

== Diff from Google
I disagree with the following in GJSG.

http://google.github.io/styleguide/javaguide.html#s2.3.1-whitespace-characters[2.3.1], “the ASCII horizontal space character (0x20) is the only whitespace character that appears anywhere in a source file”. I rather use tab characters to indent. Tabs for indentation encode intent rather than forcing a specific display behavior. The reader of my source code can then choose (by configuring its editor) to make tabs appear as x number of white spaces, with x its preferred number. (GJSG use whitespace, I believe, because it suggests using a different number of whitespace characters for different types of indent, which I do not do.)


== Outdated references
* http://www.oracle.com/technetwork/java/namingconventions-139351.html[Oracle J2EE] (but Oracle themselves say it’s outdated, https://bugs.openjdk.java.net/browse/JDK-8039151[apparently]).
* Code http://www.oracle.com/technetwork/java/javase/documentation/codeconvtoc-136057.html[Conventions] for the Java TM Programming Language contains many http://www.javacodegeeks.com/2012/10/java-coding-conventions-considered-harmful.html[incorrect] suggestions

