= Various

== Use URI rather than URL
The `URL` class has a flaw: its `URL#equals` method accesses the network. This makes it inadequate for a wide range of uses. Furthermore (and perhaps for the same reason), `URL` seems to be not much https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/net/class-use/URL.html[used] in recent libraries and `URI` is https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/net/class-use/URI.html[priviledged], for example, in the https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/nio/file/spi/FileSystemProvider.html[FileSystemProvider] and in the JAX-RS client API. `URI` is also nicer to use thanks to its https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URI.html#create(java.lang.String)[constructor] which does not throw checked exceptions.

From the point of view of what it can represent, `URL` is more constrained than `URI` in that it allows only absolute URLs; more constrained in the protocols it allows; but less constrained in the sense of the syntax it allows (see https://stackoverflow.com/a/23384891[SO]).

== Consider suppressing the warning about missing serialVersionUID
Use `@SuppressWarnings("serial")` rather than adding a `serialVersionUID` field to your class when you do not want to support serialization: it documents your intent better. (See https://stackoverflow.com/a/7636578[SO].)

