= Various
//works around awesome_bot bug that used to be published at github.com/dkhamsing/awesome_bot/issues/182. NB this is a peculiar occurrence of that bug.
:emptyattribute:

== Use URI rather than URL
The `URL` class has a flaw: its `URL#equals` method accesses the network. This makes it inadequate for a wide range of uses. Furthermore (and perhaps for the same reason), `URL` seems to be not much https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/net/class-use/URL.html[used] in recent libraries and `URI` is https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/net/class-use/URI.html[priviledged], for example, in the https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/nio/file/spi/FileSystemProvider.html[FileSystemProvider] and in the JAX-RS client API. `URI` is also nicer to use thanks to its https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/URI.html#create(java.lang.String){emptyattribute}[constructor] which does not throw checked exceptions.

From the point of view of what it can represent, `URL` is more constrained than `URI` in that it allows only absolute URLs; more constrained in the protocols it allows; but less constrained in the sense of the syntax it allows (see https://stackoverflow.com/a/23384891[SO]).

== Consider suppressing the warning about missing serialVersionUID
Use `@SuppressWarnings("serial")` rather than adding a `serialVersionUID` field to your class when you do not want to support serialization: it documents your intent better. (See https://stackoverflow.com/a/7636578[SO].)

== Installing the JDK
* Important advice. Uninstall every version of Java you have, keep only one: the latest JDK (which includes a JRE). This prevents problems with tools selecting the wrong JDK or JRE.
* On Debian: https://packages.debian.org/search?keywords=openjdk-11-jdk&searchon=names&exact=1&suite=all&section=all[openjdk-11-jdk] (install https://packages.debian.org/search?keywords=openjdk-11-source&searchon=names&exact=1&suite=all&section=all[openjdk-11-source] to have the Javadoc accessible even when coding offline).
* On Windows, to install the https://jdk.java.net/13/[OpenJDK] build, simply extract the compressed file into `C:\Program Files\Java\` (or elsewhere) and add to your `PATH` the value `"C:\Program Files\Java\jdk-13.0.1\bin"`, or adapt according to the name of the extracted `bin` subfolder (https://stackoverflow.com/a/52531093[thanks]).
* To check that it is correctly installed, open a shell, and verify that both the `java --version` and `javac --version` commands print the correct java version.

Remark: When installing the JDK, it is often recommended to set two https://superuser.com/q/284342[environment variables]: JAVA_HOME and PATH (https://stackoverflow.com/a/52531093[example]). I suggest to set only the PATH variable, because it is simpler and conceptually more elegant. Luckily, more and more programs do not need JAVA_HOME but will find your Java installation using the PATH variable, if set correctly (refs: Oracle https://docs.oracle.com/en/java/javase/11/install/installation-jdk-microsoft-windows-platforms.html#GUID-96EB3876-8C7A-4A25-9F3A-A2983FEC016A[docs] do not mention JAVA_HOME; https://sources.debian.org/src/openjdk-11/11.0.4+11-1%7Edeb10u1/debian/JAVA_HOME/[Debian]; https://wiki.eclipse.org/FAQ_How_do_I_run_Eclipse%3F#Find_the_JVM[Eclipse]; Maven is more tricky as the Windows https://github.com/apache/maven/blob/master/apache-maven/src/bin/mvn.cmd[script] claims it requires JAVA_HOME, but it is actually satisfied when only the PATH is set, and once Maven is launched, it https://git-wip-us.apache.org/repos/asf?p=maven.git;a=blob;f=maven-embedder/src/main/java/org/apache/maven/cli/CLIReportingUtils.java[does not refer] to JAVA_HOME any more (https://stackoverflow.com/a/15279640[thanks]), and its http://maven.apache.org/install.html[documentation] is https://issues.apache.org/jira/browse/MNG-6003[outdated]).

//** Note: some https://www.java.com/en/download/help/path.xml[doc] indicates that setting the PATH is not necessary to run Java programs. However, http://wiki.eclipse.org/FAQ_How_do_I_run_Eclipse%3F#Find_the_JVM[Eclipse] (for example) will apparently not start if it does not find Java in the path (unless specifically configured). Perhaps the https://docs.microsoft.com/windows/desktop/shell/app-registration[App Paths] mechanism could be used instead? (See also https://parsiya.net/blog/2017-10-23-run-line-vs.-cmd-vs.-powershell/[here].) TODO: check whether .jar starts.

