= Planning

== Prerequisites
You know algorithmics and the basic (non object-oriented) programming concepts in Java. If you have followed an algorithmics course with illustrations and exercices in Java, you satisfy the prerequisites.

== Abbreviations

* [SK]: Supposedly Known
* [I]: Important (some parts may be both SK and I)
* [O]: Optional
* [M]: Mandatory exercices
* Markers apply to the whole line. Example: "4.3 intro to 4.3.2, 4.6.1 [I]" means that everything in between 4.3 and 4.3.2 plus 4.6.1 are important.
* ESx.y(.z): designates section x.y (or x.y.z) in Eck’s http://math.hws.edu/eck/cs124/javanotes7/[book] (in chapter x)
* EQx.y: question number y in Eck’s book, from quiz chapter x
* EEx.y: exercice number y in Eck’s book, from exercices chapter x
* Ranges are always given with ends included (EQ1.3 to 1.9 means 3 and 9 included)

== Advices

* Skim lightly over the [SK] parts, just to check whether you know it indeed. Do read the non-[SK] and non-[O] parts.
* Use the quiz as a test: read the text, _then_ check that you can answer the quiz.
* Don’t feel obliged to implement all exercices (especially the simple ones): try to estimate whether you’re able to solve the problem; do implement some of them to check whether you really can.

== S1

* Basic concepts and structures of Java: variables; types; subroutines; control structures; identifiers… [SK]
* Git
* http://math.hws.edu/eck/cs124/javanotes7/c1/[ES1.1], 1.2, 1.3, 1.4, 2 intro, 2.1, 2.2, 2.3.3, 2.4.1, 2.5, 2.6.6 [SK]
* For beginners in Java: ES3 intro to 3.6 [SK]
* ES1.5
* ES2.2.1, 2.3.1, 2.3.2, 2.4.6 [I]
* ES1.6, 1.7 [O]
* Read link:../Tools.adoc#eclipse[parts] of Eclipse doc [I]

Approximatively: 10p. (+ 30p. [SK])

* http://math.hws.edu/eck/cs124/javanotes7/c1/quiz.html[EQ1.3] to 1.9
* http://math.hws.edu/eck/cs124/javanotes7/c2/quiz.html[EQ2.1] to 2.4; 2.6 to 2.9; 2.11
* (link:http://math.hws.edu/eck/cs124/javanotes7/c2/exercises.html[EE2.1] to 2.6)
* EE2.7: you may use user input (Scanner) instead of file input; do not use TextIO (I suggest you do only this one among the exercices of chapter 2, unless you lack some prerequisites)
* http://math.hws.edu/eck/cs124/javanotes7/c3/exercises.html[EE3.1] to 3.3
* EE3.4, 3.6 [M]
* EE3.8, 3.9 [O]

== S2

* Exceptions; sub-routines; design: contract, black-box, preconditions.
* EE4.5 together?
* Mosaic together?
* ES3.7 (except 3.7.3), 4 intro to 4.7.
* ES4.3 intro to 4.3.2, 4.6.1 [I]

Approximatively: 48p.

* http://math.hws.edu/eck/cs124/javanotes7/c4/exercises.html[EE4]?
* EE4.5, EE4.6, comment with Javadoc [M]

== S3

* Objects.
* http://math.hws.edu/eck/cs124/javanotes7/c5/[ES5] intro to 5.7
* ES5.3.4, 5.7 [I]

Approximatively: 50p.

== S4

* Robustesse, programmation défensive
* http://math.hws.edu/eck/cs124/javanotes7/c8/[ES8] intro to 8.4

== Then

T5 Th Générique. 

2.3.4 Enums, nouveau.
Bibliothèques. Maven.
Logging ?
SWT ?
Annotations ?
	Fichiers et flux
	REST client ?

