= WS client using curl
:toc: preamble
:sectanchors:

It is important to understand how web services that you develop will be used by your clients. Here we will adopt the role of the client and get some training at using web services. It will also be useful when you will want to test your own web services.

NOTE: The reader supposedly has basic knowledge of https://github.com/oliviercailloux/java-course/blob/master/HTTP.adoc[HTTP] and has read in particular the https://github.com/oliviercailloux/java-course/blob/master/HTTP.adoc#curl[section] about curl.

== curl
First, https://stackoverflow.com/a/16216825/[install] curl on your machine, unless you have it already.

=== Using curl
First: Warm up. We download an HTML page.

* Choose your favorite Wikipedia article. Obtain its URI using your normal web browser.
* Use curl in a command line to retrieve the HTML page you have chosen.
* Open that local HTML page in your browser. What do you observe? What do you deduce your browser does when surfing to a normal HTML page, as compared to the use you just did of curl?

Second: Simple API use. We use https://httpbin.org/[httpbin], a test web service.

* Use curl to get an image at the URL https://httpbin.org/image in JPEG format, then, in PNG. httpbin expects you to send an `Accept` header, for example `Accept: image/jpeg`. What is the return code? What is the content type?

Third: Real-life API use. We get some data from Wikipedia.

Our goal is to programmatically retrieve all the modifications (revisions) that have occurred at the  Bertrand Russel https://en.wikipedia.org/wiki/Bertrand_russel[page] in between 29th of July and 1st of August, 2017.

The information we search for can be seen in human readable version https://en.wikipedia.org/w/index.php?title=Bertrand_Russell&action=history[here]. We could of course retrieve this exact page using curl, and parse the resulting HTML. But this is very impractical and inefficient, as that page is made for humans and not for machines, and it is fragile, as nothing guarantees that the HTML code in that page will not change.

* Read Wikipedia’s API https://www.mediawiki.org/wiki/API:Main_page[doc] to find out how to retrieve the data we want in json format (Wikipedia has a newer, cleaner https://www.mediawiki.org/wiki/REST_API[API], but it is not complete yet, so we use the old one).
* Retrieve this data using curl.
* More specifically, we want the return to contain, for each revision, the revision id, parent id, user name (who made the revision), and timestamp.

You should obtain the following result.

.Return from Wikipedia
[source, json]
----
{
    "batchcomplete": "",
    "query": {
        "pages": {
            "4163": {
                "pageid": 4163,
                "ns": 0,
                "title": "Bertrand Russell",
                "revisions": [
                    {
                        "revid": 793293850,
                        "parentid": 793250564,
                        "user": "Worldbruce",
                        "timestamp": "2017-07-31T21:20:40Z"
                    },
                    {
                        "revid": 793250564,
                        "parentid": 793247860,
                        "user": "Rjwilmsi",
                        "timestamp": "2017-07-31T15:53:12Z"
                    },
                    {
                        "revid": 793247860,
                        "parentid": 793063433,
                        "user": "Rjwilmsi",
                        "timestamp": "2017-07-31T15:32:40Z"
                    },
                    {
                        "revid": 793063433,
                        "parentid": 792753782,
                        "user": "Str1977",
                        "timestamp": "2017-07-30T11:19:45Z"
                    }
                ]
            }
        }
    }
}
----

=== Supplements
If desired, you may also get trained at using curl for POSTing data and making HTTP requests using other verbs. Use the https://jsonplaceholder.typicode.com/[JSONPlaceholder] or https://httpbin.org/[httpbin] web service, or choose one of the numerous APIs from https://www.programmableweb.com/[ProgrammableWeb] (but be aware that many require registration and may be non free).
I suggest to leave curl for now, and switch to Java.

