= JAX-RS Client

JAX-RS Client API permits to easily access RESTful web services. This page provides a simple example use.

NOTE: The reader supposedly has basic knowledge of https://github.com/oliviercailloux/java-course/blob/master/HTTP.adoc[HTTP] and (preferrably) https://github.com/oliviercailloux/java-course/blob/master/Maven/README.adoc[Maven].

== Dependency
If you use Java SE, you need to add the https://search.maven.org/search?q=g:jakarta.ws.rs%20AND%20a:jakarta.ws.rs-api&core=gav[JAX-RS API] and a JAX-RS https://search.maven.org/search?q=g:org.glassfish.jersey.bundles%20AND%20a:jaxrs-ri&core=gav[implementation] to your Maven dependencies: you’ll need https://search.maven.org/search?q=g:org.glassfish.jersey.core%20AND%20a:jersey-client&core=gav[Jersey client] and https://search.maven.org/search?q=g:jakarta.activation%20AND%20a:jakarta.activation-api&core=gav[jakarta.activation-api] and https://search.maven.org/search?q=g:org.glassfish.jersey.inject%20AND%20a:jersey-hk2&core=gav[jersey-hk2] which jersey client requires at runtime. (Alternatively there’s the Jersey https://search.maven.org/search?q=g:org.glassfish.jersey.bundles%20AND%20a:jaxrs-ri&core=gav[bundle] but it brings many supplementary packages such as a JAX-RS server, bindings for Json and XML, and containers. You might also need some https://search.maven.org/search?q=g:org.glassfish.jersey.media[media] bindings.) 

See this example https://github.com/oliviercailloux/sample-rest-client/blob/master/pom.xml[POM].

If you use Java EE, this is already provided by your application server.

== Example use
You may now use the JAX-RS Client API.

[source,java]
----
Client client = ClientBuilder.newClient();
WebTarget t1 = client.target("http://…/users");
WebTarget t2 = t1.path("{uId}");
WebTarget t3 = t2.resolveTemplate("uId", "123");
WebTarget t4 = t3.queryParam("prof", "1");
/** http://…/users/123?prof=1 */
String result = t4.request(MediaType.TEXT_PLAIN).get(String.class);
client.close();
----

== Appendix
* If you do not know Maven, you may simply clone https://github.com/oliviercailloux/sample-rest-client[this] to get started quickly. The project already includes the right dependency to a Java JAX-RS client library.
** In Eclipse, use `File` / `Import…` / `Existing Maven Projects`, give it the name of the folder where you cloned the project.

