= JUnit: Overview

A brief introduction to unit testing in Java with JUnit Jupiter.

== Principle
Instead of running your program with various input parameters manually, test a single part of your program at a time, in an automated way.

== Goal
* Automated tests: When you refactor or add functionalities to your program, you simply re-run the tests to make sure you didn’t break existing functionality.
* Test a single part at a time: instead of having to debug a whole program when you observe an incorrect behavior, you know exactly which part fails.
* Document usage
* Improve your code by making sure you can test it in isolated parts, which thus require that you program using loosely coupled blocks.

== Basics
Define a new https://github.com/oliviercailloux/java-course/blob/main/Maven/README.adoc[Maven] project by using the `io.github.oliviercailloux:java-archetype` archetype (this already includes the dependency to JUnit Jupiter that we require for this tutorial), OR clone https://github.com/oliviercailloux/Sample-JUnit-5/[this project].

Say you have a class `SuperComputer` with a method declared as `public int complicatedComputation(int parameter)`. (You can copy https://github.com/oliviercailloux/Sample-JUnit-5/blob/master/src/main/java/io/github/oliviercailloux/sample_junit_5/SuperComputer.java[this], or you will find it in the project you just cloned.)

Let us write a test for this method!

* Define a new class, named `SuperComputerTests`. 
* Add a method `void testComplicatedComputationWithParameter0()`.
* Annotate the header with https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Test.html[`@Test`].
* In the method, create an object, invoke `complicatedComputation(0)` and store the result in a variable `actual`.
* Finally, invoke `https://junit.org/junit5/docs/current/api/org.junit.jupiter.api/org/junit/jupiter/api/Assertions.html#assertEquals(int,int)[Assertions.assertEquals](3, actual)`, where the first parameter is the value you expect to obtain (in this example, we test that `complicatedComputation(0)` returns `3`).
** You need to have Jupiter on the build path in order to compile and run this.
** You should obtain something like https://github.com/oliviercailloux/Sample-JUnit-5/blob/with-test/src/test/java/io/github/oliviercailloux/sample_junit_5/SuperComputerTests.java[this].
* See https://help.eclipse.org/latest/topic/org.eclipse.jdt.doc.user/tips/jdt_tips.html[Writing and running JUnit tests] to run your test. (That documentation is about a much older version of JUnit, but the part about running the tests still applies.)
* Check whether the test succeeds or fails depending on your source code.

== Usage
* In real-world projects, you would write many tests and run them all each time you change the code.
* You should test non-trivial code: do not test simple getters or `toString` methods; do not test that your method throws an `NullPointerException` when a parameter is `null`, … Such tests only duplicate your intent in the sense that if you change your mind (remove a getter, change the `toString` form), you will _also_ have to change the test.
* Your test can have a documentary purpose: the test indicates the expected result of a code, with the added value (compared to a textual documentation) that this documentation is proven up-to-date by the simple fact that the test passes.
* It is important in particular to check boundary conditions: what happens when the value is zero? Negative? Infinite (for a `double`)? `null` (for an object)? 
* You should follow some specified naming patterns for naming your test classes, otherwise they might be https://junit.org/junit5/docs/current/user-guide/#running-tests-build-maven[ignored], depending on your build tool. Ending their names with “Tests” is a best practice.
* Your test class should lie in the same package as the class it tests.
* Your test classes should be in the `src/test/java` source directory, distinct from the rest of your code (lying in `src/main/java`): you do not want to distribute your test classes to users, this is only for internal use; and it makes it easy to find them.
* Instead of `import `org.junit.jupiter.api.Assertions;` and `Assertions.assertEquals(…)`, write `static import `org.junit.jupiter.api.Assertions.assertEquals;` (which permits to use the short name of a single method) and `assertEquals(…)`.
* Order the parameters of `assertEquals` correctly, otherwise you get confusing messages when tests fail. Check the numerous other assert-like methods that you can use and learn to use the right one.

== References
* JUnit 5 official https://junit.org/junit5/docs/current/user-guide/[User Guide] and https://github.com/junit-team/junit5-samples[samples]
* JUnit 5 https://nipafx.dev/junit-5-basics/[basics] on nipafx
* https://site.mockito.org/

