= Syntax

Here we learn the basic syntax of Java, and train using jshell.

See: https://raw.githubusercontent.com/oliviercailloux/java-course/master/Syntax/Pr%C3%A9sentation/presentation.pdf[présentation].

== Hint
In jshell, as with many shells, use ↑ (keyboard up https://en.wikipedia.org/wiki/Arrow_keys[arrow]) to recall previous commands.

== Short exercices
You can achieve all these tasks with only the syntax seen in this presentation, in particular, without using explicit conversions from String to integer or conversely. Try it!

. Assign your first name to a variable and use it to print `Hello <your-first-name>.`
. Assign your age to a integer variable and use it to print `<your-age> is my age!`
. Assign each digit of your age to different integer variables; use them to print `<your-age> is my age!`
. Create a boolean variable whose value is `true`, another one whose value is `false`, and use them to create an expression that evaluates to `true` and one that evaluates to `false`
. Assign any number you like to an integer variable. Create an expression that evaluates to `true` if, and only if, that variable equals your age. (Test it by changing the value of the variable and running the expression again.)
. Assign the value `"true"` to a variable of type `String`. Create an expression that evaluates to `true` if, and only if, the value of that variable is equal to the String `"true"`. Use the method `s1.equals(s2)` to test for equality of two strings `s1` and `s2`.

== Methods
. Assign 4659 and 23 to variables, and show the result of multiplying these variables
. Compute the greatest divisor of 4659 that is different than 4659 (use the `%` operator and a loop) (to check your answer, look at https://www.wolframalpha.com/input?i2d=true&i=factor%5C%2840%294659%5C%2841%29[its factors])
. Define a method that returns the greatest divisor of 4659 that is different than 4659
. Define a method `greatestDivisor` that accepts an integer parameter and returns its greatest divisor except itself; use it to show the greatest divisor of 4659.

== Classes
In a text editor, define a class `MyMathClass` containing a method that accepts an integer parameter and returns its greatest divisor except itself, and a method that returns the smallest divisor of its parameter except one; and a class `MyBooleanClass` containing a method `xor` returning `true` iff exactly one of its two boolean parameters is `true`. Copy-paste this in jshell and call all these methods from jshell.

== More about classes
Define a class `MovingThing` that has a static variable `currentSpeed` and a static variable `totalLength`; and a static method declared as `static void move(double time)` that computes the distance an object moving at `currentSpeed` moves in `time` and adds it to the current total length. Copy-paste this in jshell and use your class to check that it works well. For example, after calling `MovingThing.currentSpeed = 10` then `MovingThing.move(50)`, the variable `MovingThing.totalLength` should have a value of `500`.

Once this works, make all your variables private so that nobody but your own class can touch them. Modify your class to make it still useable by providing appropriate methods to get or set their values as required. Make sure to restrict access as much as reasonable, for example, an external user should not be able to modify the `totalLength` directly.

== More exercices
Our goal here is to reach exercice 3.6 (here below), which requires to print out all numbers that have the maximum number of divisors. This requires to achieve exercice 3.2 first. Optionally, you may also want to attempt exercices 3.1, and 3.8 and 3.9 if you want some more advanced challenges.

* https://math.hws.edu/javanotes/c3/exercises.html[3.2]
* 3.6
* EE3.1, EE3.8, 3.9 (optional)

The following two subsections are here for reference; we will come back to it later in the course.

== Varargs
See Oracle doc about the varargs syntax: https://docs.oracle.com/javase/tutorial/java/javaOO/arguments.html[Varargs]

*Exercice*: call the static method `String.link:https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#format(java.lang.String,java.lang.Object.%2E.)[format]()` with no arguments, then with only one string as argument, then two strings, then three strings. Predict which calls will be accepted by the compiler. Explain in each case what parameters are effectively passed to the method, by considering the method declaration (hint: exactly two parameters are passed for each permissible call).

== More syntax
* https://github.com/oliviercailloux/java-course/blob/main/Syntax/Interfaces.adoc[Interfaces]
* https://github.com/oliviercailloux/java-course/blob/main/Syntax/Classes%20as%20concept.adoc[Classes as concept]: instance variables and instance methods
* https://github.com/oliviercailloux/java-course/blob/main/Syntax/Inheritance.adoc[Inheritance]: extending interfaces and classes

== References
* https://docs.oracle.com/en/java/javase/13/docs/specs/man/jshell.html[jshell]
* https://arbitrary-but-fixed.net/teaching/java/jshell/2017/12/14/jshell-peculiarities.html[The peculiarities of the JShell]

