= Correction of exercice Three dice

* Eclipse config (/3) (using the correct Eclipse config, 3 if no warnings and no @SuppressWarnings used, 1.5 if only one warning or @SuppressWarnings used, 0 otherwise)
* TripletOfDice (/12)
** rollAllDice indeed rolls all dice, rollOneDie indeed rolls the die, getFirstDie (or getDie) indeed returns the last die result, instance (not static) methods and variables (/4)
** rollOneDie must throw if die number invalid (/4)
** better interface (/1, bonus): getDie(int die), must also throw argument if die number invalid. If getDie is there, getFirstDie and similar may have been omitted.
** Javadoc must mention what happens if I don’t roll and ask for a die (/4). No explanation, or explanation does not match behavior: 0. Example of a consistent explanation and behavior: Javadoc of the class indicates that “A die must be rolled before calling #getDie().”, Javadoc of the method getDie(int) (or of the methods getFirstDie, …) indicates “@throws IllegalStateException if the die is not rolled before calling”, and the code of getDie() indeed throws an IllegalStateException if the die is not rolled before calling.
* DiceUser (/5)
** rollOnce is static and performs correctly (/3)
** main prints exactly the expected text on three lines (/2)

