= Automated Eclipse install

Here is how I automate my Eclipse installation.

* `RELEASE=2022-06`
* Extract the source file: `tar -xf "eclipse-java-${RELEASE}-R-linux-gtk-x86_64.tar.gz"`
* `sudo mv eclipse/ "/usr/local/share/eclipse-java-${RELEASE}-R-linux-gtk-x86_64/"`
* Install any desired shared plugins (optional, see below)
* `sudo chown -R root:staff "/usr/local/share/eclipse-java-${RELEASE}-R-linux-gtk-x86_64/"`
* `sudo chmod -R o+rX "/usr/local/share/eclipse-java-${RELEASE}-R-linux-gtk-x86_64/"`
* Delete your `.eclipse` folder and your previous Eclipse workspace to forget possible unwanted residuals from previous installations
* (Optional) https://wiki.archlinux.org/title/desktop_entries[Adjust] desktop entry

////
== Automatic workspace selection
Tried the following; fails at start, Eclipse seems confused.
mkdir -p ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/.settings" ; printf "RECENT_WORKSPACES=/home/olivier/Local/eclipse-workspace\nSHOW_WORKSPACE_SELECTION_DIALOG=false" > ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/.settings/org.eclipse.ui.ide.prefs"
mkdir -p ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/.settings" ; echo "SHOW_WORKSPACE_SELECTION_DIALOG=false" > ".eclipse/org.eclipse.platform_4.14.0_1448112854_linux_gtk_x86_64/configuration/.settings/org.eclipse.ui.ide.prefs"
////

== Shared plugins
This uses the https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/misc/multi_user_installs.html[shared configuration] approach.

To install Papyrus (tested on Eclipse 2021-12): `"/usr/local/share/eclipse-java-${RELEASE}-R-linux-gtk-x86_64/eclipse" -nosplash -application "org.eclipse.equinox.p2.director" -repository "https://download.eclipse.org/modeling/mdt/papyrus/updates/releases/${RELEASE}, \https://download.eclipse.org/releases/${RELEASE}" -installIU "org.eclipse.papyrus.sdk.feature.feature.group"`. 

.Further technicalities
[%collapsible]
====
This (for version 2021-09) installs 42 papyrus features, the `org.eclipse.xwt.feature_1.6.0.202105260718` feature, 348 papyrus plugins, and 154 other plugins (some of which related to gmf and apache batik, for example). The installer may appear stuck; you can track its progress with `ls "/usr/local/share/eclipse-java-2021-09-R-linux-gtk-x86_64/plugins/" | wc -l`. Installation takes about 2 to 8 minutes.

“Papyrus uses XWT to generate the "Properties View" for UML model editing” -- https://projects.eclipse.org/projects/technology.xwt. Oddly enough, both the releases/2021-09 and the `\https://download.eclipse.org/xwt/milestones-1.7.0/1.7.0-S/` repositories were required for finding `org.eclipse.papyrus.infra.feature.feature.group` 3.1.0.202109161249.

On Eclipse version 2021-03, installing `org.eclipse.papyrus.uml.feature.feature.group` instead of `org.eclipse.papyrus.sdk.feature.feature.group`, which installs fewer features and plugins (18 and 360 instead of 42 and 477 on that version), does not seem to be sufficient; for example, Papyrus project files do not open in that case.
====

To install PyDev (tested on Eclipse 2022-06): `"/usr/local/share/eclipse-java-${RELEASE}-R-linux-gtk-x86_64/eclipse" -nosplash -application "org.eclipse.equinox.p2.director" -repository "https://www.pydev.org/updates" -installIU "org.python.pydev.feature.feature.group"` (installing only `org.python.pydev` leads to missing Run option).

To install HTML, CSS, JavaScript editors: `"/usr/local/share/eclipse-java-${RELEASE}-R-linux-gtk-x86_64/eclipse" -nosplash -application "org.eclipse.equinox.p2.director" -repository "https://download.eclipse.org/releases/${RELEASE}" -installIU "org.eclipse.wildwebdeveloper.feature.feature.group"`

https://stackoverflow.com/a/38956772[This] lets you find the data for other plugins.

== Others
Under Linux Gnome, consider https://bugs.eclipse.org/bugs/show_bug.cgi?id=473562[disabling] the Alt+F5 shortcut so that the Eclipse one works.

